SET DEFINE OFF;
Prompt Non-Foreign Key Constraints on Table SIE_01_ATRIB_MODL_COMNC;
ALTER TABLE SIE_01_ATRIB_MODL_COMNC ADD (
  CONSTRAINT SIE_01_ATRIB_MODL_COMNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_CODE_ERR_ORACL;
ALTER TABLE SIE_01_CODE_ERR_ORACL ADD (
  CONSTRAINT SIE_01_CODE_ERR_ORCL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_CONFG_EVENM_NOTFB;
ALTER TABLE SIE_01_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_CONFG_EVENM_NOTFB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_DESTN;
ALTER TABLE SIE_01_DESTN ADD (
  CONSTRAINT SIE_01_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_DESTN_CONFG_EVENM_NOTFB;
ALTER TABLE SIE_01_DESTN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_DESTN_CONFG_EN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_ELEMN_CONFG_EVENM_NOTFB;
ALTER TABLE SIE_01_ELEMN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_ELEMN_CONFG_EN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_EVENM_NOTFB;
ALTER TABLE SIE_01_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_EVENM_NOTFB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_HIERC_APLIC;
ALTER TABLE SIE_01_HIERC_APLIC ADD (
  CONSTRAINT SIE_12_HIERC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_LANG;
ALTER TABLE SIE_01_LANG ADD (
  CONSTRAINT SIE_01_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_LANG_LANG;
ALTER TABLE SIE_01_LANG_LANG ADD (
  CONSTRAINT SIE_01_LANG_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG;
ALTER TABLE SIE_01_MESG ADD (
  CONSTRAINT SIE_01_MESG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG_ERR_LIE;
ALTER TABLE SIE_01_MESG_ERR_LIE ADD (
  CONSTRAINT SIE_01_MESG_ERR_LIE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG_LANG;
ALTER TABLE SIE_01_MESG_LANG ADD (
  CONSTRAINT SIE_01_MESG_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG_TRADC_APEX;
ALTER TABLE SIE_01_MESG_TRADC_APEX ADD (
  CONSTRAINT SIE_01_MESG_TRADC_APEX_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MODL_AFICH_NOTFC;
ALTER TABLE SIE_01_MODL_AFICH_NOTFC ADD (
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MODL_COMNC;
ALTER TABLE SIE_01_MODL_COMNC ADD (
  CONSTRAINT SIE_01_MODL_COMNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MODL_MESG_NOTFC;
ALTER TABLE SIE_01_MODL_MESG_NOTFC ADD (
  CONSTRAINT SIE_01_MODL_MESG_NOTFC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_NOTFC;
ALTER TABLE SIE_01_NOTFC ADD (
  CONSTRAINT SIE_01_NOTFC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_RESLT_DESTN;
ALTER TABLE SIE_01_RESLT_DESTN ADD (
  CONSTRAINT SIE_01_RESLT_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_TYPE_COMNC;
ALTER TABLE SIE_01_TYPE_COMNC ADD (
  CONSTRAINT SIE_01_TYPE_COMNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_03_CLAS_INTER;
ALTER TABLE SIE_03_CLAS_INTER ADD (
  CONSTRAINT SIE_03_CLAS_INTER_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_03_LIEN_CLAS_INTER_UTILS;
ALTER TABLE SIE_03_LIEN_CLAS_INTER_UTILS ADD (
  CONSTRAINT SIE_03_LIEN_CLAS_INTER_UTIL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_04_CONTX;
ALTER TABLE SIE_04_CONTX ADD (
  CONSTRAINT SIE_04_CONTX_PK
  PRIMARY KEY
  (REF_FIL_ARIAN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_04_CONTX_ETEND;
ALTER TABLE SIE_04_CONTX_ETEND ADD (
  CONSTRAINT SIE_04_CONTX_ETEND_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_04_FIL_ARIAN;
ALTER TABLE SIE_04_FIL_ARIAN ADD (
  CONSTRAINT SIE_04_FIL_ARIAN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_04_NAVGT_HISTR;
ALTER TABLE SIE_04_NAVGT_HISTR ADD (
  CONSTRAINT SIE_04_NAVGT_HISTR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_07_AUDIT_STRUC_APLIC;
ALTER TABLE SIE_07_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT SIE_07_AUDIT_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_07_INSTA_SEMPH;
ALTER TABLE SIE_07_INSTA_SEMPH ADD (
  CONSTRAINT SIE_07_INSTA_SEMPH_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_07_SEMPH;
ALTER TABLE SIE_07_SEMPH ADD (
  CONSTRAINT SIE_07_SEMPH_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_07_VALR_AUDIT_STRUC_APLIC;
ALTER TABLE SIE_07_VALR_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT SIE_07_VALR_AUDIT_SA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_APLIC;
ALTER TABLE SIE_11_APLIC ADD (
  CONSTRAINT SIE_11_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_ATRIB_ENTIT;
ALTER TABLE SIE_11_ATRIB_ENTIT ADD (
  CONSTRAINT SIE_11_ATRIB_ENTIT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_ENTIT;
ALTER TABLE SIE_11_ENTIT ADD (
  CONSTRAINT SIE_11_ENTIT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PARMT_AFW;
ALTER TABLE SIE_11_PARMT_AFW ADD (
  CONSTRAINT SIE_11_PARMT_AFW_PK1
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PLUGN;
ALTER TABLE SIE_11_PLUGN ADD (
  CONSTRAINT SIE_11_PLUGN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PRODT;
ALTER TABLE SIE_11_PRODT ADD (
  CONSTRAINT SIE_11_PRODT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PRODT_LANG;
ALTER TABLE SIE_11_PRODT_LANG ADD (
  CONSTRAINT SIE_11_PRODT_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PRODT_RESRC;
ALTER TABLE SIE_11_PRODT_RESRC ADD (
  CONSTRAINT SIE_11_PRODT_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_UTILS;
ALTER TABLE SIE_11_UTILS ADD (
  CONSTRAINT SIE_11_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_VERSN;
ALTER TABLE SIE_11_VERSN ADD (
  CONSTRAINT SIE_11_VERSN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_ACTIO_AUDIT;
ALTER TABLE SIE_12_ACTIO_AUDIT ADD (
  CONSTRAINT SIE_12_ACTIO_AUDIT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_ARBRE;
ALTER TABLE SIE_12_ARBRE ADD (
  CONSTRAINT SIE_12_ARBRE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_ARBRE_NOEUD;
ALTER TABLE SIE_12_ARBRE_NOEUD ADD (
  CONSTRAINT SIE_12_ARBRE_NOEUD_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_ATRIB_STRUC_APLIC;
ALTER TABLE SIE_12_ATRIB_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_ATRIB_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_COMPT_PAYPL;
ALTER TABLE SIE_12_COMPT_PAYPL ADD (
  CONSTRAINT SIE_12_COMPT_PAYPL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DEFNT_ACCES;
ALTER TABLE SIE_12_DEFNT_ACCES ADD (
  CONSTRAINT SIE_12_DEFNT_ACCES_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DETL_FORML;
ALTER TABLE SIE_12_DETL_FORML ADD (
  CONSTRAINT SIE_12_DETL_FORML_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DOMN;
ALTER TABLE SIE_12_DOMN ADD (
  CONSTRAINT SIE_12_DOMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DOMN_FONCT;
ALTER TABLE SIE_12_DOMN_FONCT ADD (
  CONSTRAINT SIE_12_DOMN_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DOMN_UTILS;
ALTER TABLE SIE_12_DOMN_UTILS ADD (
  CONSTRAINT SIE_12_DOMN_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_EVOLT_STAT;
ALTER TABLE SIE_12_EVOLT_STAT ADD (
  CONSTRAINT SIE_12_EVOLT_STAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FAVR;
ALTER TABLE SIE_12_FAVR ADD (
  CONSTRAINT SIE_12_FAVR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FONCT;
ALTER TABLE SIE_12_FONCT ADD (
  CONSTRAINT SIE_12_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FONCT_STRUC_APLIC;
ALTER TABLE SIE_12_FONCT_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_FONCT_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FORML;
ALTER TABLE SIE_12_FORML ADD (
  CONSTRAINT SIE_12_FORML_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_GROUP_STAT;
ALTER TABLE SIE_12_GROUP_STAT ADD (
  CONSTRAINT SIE_12_GROUP_STAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_GROUP_UTILS;
ALTER TABLE SIE_12_GROUP_UTILS ADD (
  CONSTRAINT SIE_12_GROUP_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_GR_UT_OPERT_OPTIO_DOMN;
ALTER TABLE SIE_12_GR_UT_OPERT_OPTIO_DOMN ADD (
  CONSTRAINT SIE_12_GU_OPER_OPT_DOMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_HISTR_ACCES;
ALTER TABLE SIE_12_HISTR_ACCES ADD (
  CONSTRAINT SIE_12_HISTR_ACCES_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_LIEN_GROUP_UTILS;
ALTER TABLE SIE_12_LIEN_GROUP_UTILS ADD (
  CONSTRAINT SIE_12_LIEN_GROUP_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_LIEN_STRUC;
ALTER TABLE SIE_12_LIEN_STRUC ADD (
  CONSTRAINT SIE_12_LIEN_STRUC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_MEMBR_STRUC;
ALTER TABLE SIE_12_MEMBR_STRUC ADD (
  CONSTRAINT SIE_12_MEMBR_STRUC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_PAYPL_RETR_APLIC;
ALTER TABLE SIE_12_PAYPL_RETR_APLIC ADD (
  CONSTRAINT SIE_12_PAYPL_RETR_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_REQT_INTER_UTILS;
ALTER TABLE SIE_12_REQT_INTER_UTILS ADD (
  CONSTRAINT SIE_12_REQT_INTER_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_SESN;
ALTER TABLE SIE_12_SESN ADD (
  CONSTRAINT SIE_12_SESN_PK
  PRIMARY KEY
  (ID_SESN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STAT;
ALTER TABLE SIE_12_STAT ADD (
  CONSTRAINT SIE_12_STAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STRUC_ADMIN;
ALTER TABLE SIE_12_STRUC_ADMIN ADD (
  CONSTRAINT SIE_12_STRUC_ADMIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STRUC_APLIC;
ALTER TABLE SIE_12_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STRUC_APLIC_DESTN;
ALTER TABLE SIE_12_STRUC_APLIC_DESTN ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STRUC_APLIC_LANG;
ALTER TABLE SIE_12_STRUC_APLIC_LANG ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_TYPE_STRUC;
ALTER TABLE SIE_12_TYPE_STRUC ADD (
  CONSTRAINT SIE_12_TYPE_STRUC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_UTILS;
ALTER TABLE SIE_12_UTILS ADD (
  CONSTRAINT SIE_12_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_CONDT_EXECT;
ALTER TABLE SIE_13_CONDT_EXECT ADD (
  CONSTRAINT SIE_13_CONDT_EXECT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_CONDT_PILTB;
ALTER TABLE SIE_13_CONDT_PILTB ADD (
  CONSTRAINT SIE_13_CONDT_PILTB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_DOSR_VIRTL;
ALTER TABLE SIE_13_DOSR_VIRTL ADD (
  CONSTRAINT SIE_13_DOSR_VIRTL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_EMPLA_DOSR_VIRTL;
ALTER TABLE SIE_13_EMPLA_DOSR_VIRTL ADD (
  CONSTRAINT SIE_13_EMPLA_DOSR_VIRTL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_EXPOR_APLIC;
ALTER TABLE SIE_13_EXPOR_APLIC ADD (
  CONSTRAINT SIE_13_EXPOR_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_FORMT_RESRC;
ALTER TABLE SIE_13_FORMT_RESRC ADD (
  CONSTRAINT SIE_13_FORMT_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_INSTA_PREFR;
ALTER TABLE SIE_13_INSTA_PREFR ADD (
  CONSTRAINT SIE_13_INSTA_PREFR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_ITEM_MENU;
ALTER TABLE SIE_13_ITEM_MENU ADD (
  CONSTRAINT SIE_13_ITEM_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_LIEN_CONDT_PILTB;
ALTER TABLE SIE_13_LIEN_CONDT_PILTB ADD (
  CONSTRAINT SIE_13_LIEN_CONDT_PILTB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_LISTE_NAVGT;
ALTER TABLE SIE_13_LISTE_NAVGT ADD (
  CONSTRAINT SIE_13_LISTE_NAVGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_MENU;
ALTER TABLE SIE_13_MENU ADD (
  CONSTRAINT SIE_13_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_MIME_TYPE;
ALTER TABLE SIE_13_MIME_TYPE ADD (
  CONSTRAINT SIE_13_MIME_TYPE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_NAVGT;
ALTER TABLE SIE_13_NAVGT ADD (
  CONSTRAINT SIE_13_NAVGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_NAVGT_ELEMN;
ALTER TABLE SIE_13_NAVGT_ELEMN ADD (
  CONSTRAINT SIE_13_NAVGT_ELEMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_OCURN_RESRC;
ALTER TABLE SIE_13_OCURN_RESRC ADD (
  CONSTRAINT SIE_13_OCURN_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_OPERT;
ALTER TABLE SIE_13_OPERT ADD (
  CONSTRAINT SIE_13_OPERT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_OPERT_OPTIO;
ALTER TABLE SIE_13_OPERT_OPTIO ADD (
  CONSTRAINT SIE_13_OPERT_OPTIO_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE;
ALTER TABLE SIE_13_PAGE ADD (
  CONSTRAINT SIE_13_PAGE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_IR;
ALTER TABLE SIE_13_PAGE_IR ADD (
  CONSTRAINT SIE_13_PAGE_IR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_IR_COLN;
ALTER TABLE SIE_13_PAGE_IR_COLN ADD (
  CONSTRAINT SIE_13_PAGE_IR_COLN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_ITEM;
ALTER TABLE SIE_13_PAGE_ITEM ADD (
  CONSTRAINT SIE_13_PAGE_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_ITEM_LANG;
ALTER TABLE SIE_13_PAGE_ITEM_LANG ADD (
  CONSTRAINT SIE_13_PAGE_ITEM_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_LANG;
ALTER TABLE SIE_13_PAGE_LANG ADD (
  CONSTRAINT SIE_13_PAGE_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_PREFR_NAVGT;
ALTER TABLE SIE_13_PAGE_PREFR_NAVGT ADD (
  CONSTRAINT SIE_13_PAGE_PREFR_NAVGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PREFR;
ALTER TABLE SIE_13_PREFR ADD (
  CONSTRAINT SIE_13_PREFR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_REGN_PILTB;
ALTER TABLE SIE_13_REGN_PILTB ADD (
  CONSTRAINT SIE_13_REGN_PILTB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_REGN_PILTB_LANG;
ALTER TABLE SIE_13_REGN_PILTB_LANG ADD (
  CONSTRAINT SIE_13_REGN_PILTB_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_RESRC;
ALTER TABLE SIE_13_RESRC ADD (
  CONSTRAINT SIE_13_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_TYPE_FICHR;
ALTER TABLE SIE_13_TYPE_FICHR ADD (
  CONSTRAINT SIE_13_TYPE_FICHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_DETL_DOMN_VALR;
ALTER TABLE SIE_14_DETL_DOMN_VALR ADD (
  CONSTRAINT SIE_14_DETL_DOMN_VALR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_DOMN_VALR;
ALTER TABLE SIE_14_DOMN_VALR ADD (
  CONSTRAINT SIE_14_DOMN_VALR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_FORMT;
ALTER TABLE SIE_14_FORMT ADD (
  CONSTRAINT SIE_14_FORMT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_TYPE_DOMN_VALR;
ALTER TABLE SIE_14_TYPE_DOMN_VALR ADD (
  CONSTRAINT SIE_14_TYPE_DOMN_VALR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_ATACH_COURL_ENTRA;
ALTER TABLE SIE_17_ATACH_COURL_ENTRA ADD (
  CONSTRAINT SIE_17_ATACH_COURL_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COMPT_AXIAT;
ALTER TABLE SIE_17_COMPT_AXIAT ADD (
  CONSTRAINT SIE_17_COMPT_AXIAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COMPT_TWILI;
ALTER TABLE SIE_17_COMPT_TWILI ADD (
  CONSTRAINT SIE_17_COMPT_TWILI_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COURL;
ALTER TABLE SIE_17_COURL ADD (
  CONSTRAINT SIE_17_COURL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COURL_DESTN;
ALTER TABLE SIE_17_COURL_DESTN ADD (
  CONSTRAINT SIE_17_COURL_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COURL_ENTRA;
ALTER TABLE SIE_17_COURL_ENTRA ADD (
  CONSTRAINT SIE_17_COURL_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COURL_PIECE_JOINT;
ALTER TABLE SIE_17_COURL_PIECE_JOINT ADD (
  CONSTRAINT SIE_17_COURL_PIECE_JOINT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_PIECE_TELCP_AXIAT;
ALTER TABLE SIE_17_PIECE_TELCP_AXIAT ADD (
  CONSTRAINT SIE_17_PIECE_TELCP_AXIAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_PROFL_COURL;
ALTER TABLE SIE_17_PROFL_COURL ADD (
  CONSTRAINT SIE_17_PROFL_COURL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_PROPR_COURL_ENTRA;
ALTER TABLE SIE_17_PROPR_COURL_ENTRA ADD (
  CONSTRAINT SIE_17_PROPR_COURL_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_SMS_TWILI;
ALTER TABLE SIE_17_SMS_TWILI ADD (
  CONSTRAINT SIE_17_SMS_TWILI_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_SMS_TWILI_ENTRA;
ALTER TABLE SIE_17_SMS_TWILI_ENTRA ADD (
  CONSTRAINT SIE_17_SMS_TWILI_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_TELCP_AXIAT;
ALTER TABLE SIE_17_TELCP_AXIAT ADD (
  CONSTRAINT SIE_17_TELCP_AXIAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_BOUTN;
ALTER TABLE SIE_19_BOUTN ADD (
  CONSTRAINT SIE_19_BOUTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_CLE;
ALTER TABLE SIE_19_CLE ADD (
  CONSTRAINT SIE_19_CLE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_DISPN_FONCT;
ALTER TABLE SIE_19_DISPN_FONCT ADD (
  CONSTRAINT SIE_19_DISPN_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_FONCT;
ALTER TABLE SIE_19_FONCT ADD (
  CONSTRAINT SIE_19_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_FONCT_LANG;
ALTER TABLE SIE_19_FONCT_LANG ADD (
  CONSTRAINT SIE_19_FONCT_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_SPECF_FONCT;
ALTER TABLE SIE_19_SPECF_FONCT ADD (
  CONSTRAINT SIE_19_SPECF_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_DEPLM;
ALTER TABLE SIE_20_DEPLM ADD (
  CONSTRAINT "sie_20_deplm_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_DETL_DOCMN;
ALTER TABLE SIE_20_DETL_DOCMN ADD (
  CONSTRAINT "sie_20_detl_docmn_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_DOCMN;
ALTER TABLE SIE_20_DOCMN ADD (
  CONSTRAINT "sie_20_docmn_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_MODL;
ALTER TABLE SIE_20_MODL ADD (
  CONSTRAINT "sie_20_modl_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_MODL_EXCEP;
ALTER TABLE SIE_20_MODL_EXCEP ADD (
  CONSTRAINT "sie_20_modl_excep_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_MODL_PARMT;
ALTER TABLE SIE_20_MODL_PARMT ADD (
  CONSTRAINT "sie_20_modl_parmt_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_20_SECTN_DOCMN;
ALTER TABLE SIE_20_SECTN_DOCMN ADD (
  CONSTRAINT "sie_20_sectn_docmn_pk"
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_ARBRE;
ALTER TABLE SIE_21_PLUGN_ARBRE ADD (
  CONSTRAINT SIE_21_PLUGN_ARBRE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_ARBRE_NOEUD;
ALTER TABLE SIE_21_PLUGN_ARBRE_NOEUD ADD (
  CONSTRAINT SIE_21_PLUGN_ARBRE_NOEUD_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_CALND;
ALTER TABLE SIE_21_PLUGN_CALND ADD (
  CONSTRAINT SIE_21_PLUGN_CALND_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_CALND_TYPE;
ALTER TABLE SIE_21_PLUGN_CALND_TYPE ADD (
  CONSTRAINT SIE_21_PLUGN_CALND_TYPE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_ITEM_MENU;
ALTER TABLE SIE_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT SIE_21_PLUGN_ITEM_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_MENU;
ALTER TABLE SIE_21_PLUGN_MENU ADD (
  CONSTRAINT SIE_21_PLUGN_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_APLIC_MODL_RECHR;
ALTER TABLE SIE_23_APLIC_MODL_RECHR ADD (
  CONSTRAINT SIE_23_APLIC_MODL_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_DETL_APLIC_MODL_RECHR;
ALTER TABLE SIE_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT SIE_23_DETL_APLIC_MODL_REC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_DETL_RESLT_RECHR;
ALTER TABLE SIE_23_DETL_RESLT_RECHR ADD (
  CONSTRAINT SIE_23_DETL_RESLT_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_ENONC_RECHR;
ALTER TABLE SIE_23_ENONC_RECHR ADD (
  CONSTRAINT SIE_23_ENONC_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_MODL_RECHR;
ALTER TABLE SIE_23_MODL_RECHR ADD (
  CONSTRAINT SIE_23_MODL_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_PATRN_RECHR;
ALTER TABLE SIE_23_PATRN_RECHR ADD (
  CONSTRAINT SIE_23_PATRN_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_RECHR;
ALTER TABLE SIE_23_RECHR ADD (
  CONSTRAINT SIE_23_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_RESLT_RECHR;
ALTER TABLE SIE_23_RESLT_RECHR ADD (
  CONSTRAINT SIE_23_RESLT_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_CHAMP;
ALTER TABLE SIE_25_CHAMP ADD (
  CONSTRAINT SIE_25_CHAMP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_CHAMP_PUBLC_TRAVL;
ALTER TABLE SIE_25_CHAMP_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_CHAMP_PUBLC_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_DOMN_TYPE_PUBLC;
ALTER TABLE SIE_25_DOMN_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_DOMN_TYPE_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_ELEMN_CONFG_PUBLC;
ALTER TABLE SIE_25_ELEMN_CONFG_PUBLC ADD (
  CONSTRAINT SIE_25_ELEMN_CONFG_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_ENGIN;
ALTER TABLE SIE_25_ENGIN ADD (
  CONSTRAINT SIE_25_ENGIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_ENGIN_VERSN_PUBLC;
ALTER TABLE SIE_25_ENGIN_VERSN_PUBLC ADD (
  CONSTRAINT SIE_25_ENGIN_VERSN_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_GROUP_PUBLC;
ALTER TABLE SIE_25_GROUP_PUBLC ADD (
  CONSTRAINT SIE_25_GROUP_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_JOURN_TRAVL_EXECT;
ALTER TABLE SIE_25_JOURN_TRAVL_EXECT ADD (
  CONSTRAINT SIE_25_JOURN_TRAVL_EXECT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_OCURN_PARMT_PUBLC_TRAVL;
ALTER TABLE SIE_25_OCURN_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_OCURN_PARMT_PUB_TRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PARMT_PUBLC_TRAVL;
ALTER TABLE SIE_25_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_PARMT_PUBLC_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PARMT_PUBLC_TRAVL_EXECT;
ALTER TABLE SIE_25_PARMT_PUBLC_TRAVL_EXECT ADD (
  CONSTRAINT SIE_25_PARMT_PUBLC_TRAVL_E_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PARMT_TYPE_PUBLC;
ALTER TABLE SIE_25_PARMT_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_PARMT_TYPE_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PUBLC;
ALTER TABLE SIE_25_PUBLC ADD (
  CONSTRAINT SIE_25_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PUBLC_TRAVL;
ALTER TABLE SIE_25_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_PUBLC_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_TRAVL;
ALTER TABLE SIE_25_TRAVL ADD (
  CONSTRAINT SIE_25_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_TYPE_PUBLC;
ALTER TABLE SIE_25_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_TYPE_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_TYPE_TRAVL;
ALTER TABLE SIE_25_TYPE_TRAVL ADD (
  CONSTRAINT SIE_25_TYPE_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_VALR_CHAMP;
ALTER TABLE SIE_25_VALR_CHAMP ADD (
  CONSTRAINT SIE_25_VALR_CHAMP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_VALR_ELEMN_CONFG;
ALTER TABLE SIE_25_VALR_ELEMN_CONFG ADD (
  CONSTRAINT SIE_25_VALR_ELEMN_CONFG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_VERSN_PUBLC;
ALTER TABLE SIE_25_VERSN_PUBLC ADD (
  CONSTRAINT SIE_25_VERSN_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_29_CONTR;
ALTER TABLE SIE_29_CONTR ADD (
  CONSTRAINT SIE_29_CONTR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_AFECT_ITEM;
ALTER TABLE SIE_30_AFECT_ITEM ADD (
  CONSTRAINT SIE_30_AFECT_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CARNT_APLIC;
ALTER TABLE SIE_30_CARNT_APLIC ADD (
  CONSTRAINT SIE_30_CARNT_PRODT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CARNT_PRODT;
ALTER TABLE SIE_30_CARNT_PRODT ADD (
  CONSTRAINT SIE_30_CARNT_SYSTM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CARNT_SPRIN;
ALTER TABLE SIE_30_CARNT_SPRIN ADD (
  CONSTRAINT SIE_30_CARNT_SPRIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CAS_UTILS;
ALTER TABLE SIE_30_CAS_UTILS ADD (
  CONSTRAINT SIE_30_CAS_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_EFORT_ITEM;
ALTER TABLE SIE_30_EFORT_ITEM ADD (
  CONSTRAINT SIE_30_EFORT_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_HISTR_EFORT_RESTN;
ALTER TABLE SIE_30_HISTR_EFORT_RESTN ADD (
  CONSTRAINT SIE_30_HISTR_EFORT_RESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_ITEM_CARNT_PRODT;
ALTER TABLE SIE_30_ITEM_CARNT_PRODT ADD (
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_ITEM_CARNT_SPRIN;
ALTER TABLE SIE_30_ITEM_CARNT_SPRIN ADD (
  CONSTRAINT SIE_30_ITEM_CARNT_SPRIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_PAGE;
ALTER TABLE SIE_30_PAGE ADD (
  CONSTRAINT SIE_30_PAGE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_PAGE_ITEM;
ALTER TABLE SIE_30_PAGE_ITEM ADD (
  CONSTRAINT SIE_30_PAGE_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);
