SET DEFINE OFF;
Prompt Foreign Key Constraints on Table SIE_01_ATRIB_MODL_COMNC;
ALTER TABLE SIE_01_ATRIB_MODL_COMNC ADD (
  CONSTRAINT SIE_01_ATRIB_MODL_COMNC_FK1 
  FOREIGN KEY (REF_MODL_COMNC) 
  REFERENCES SIE_01_MODL_COMNC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_CONFG_EVENM_NOTFB;
ALTER TABLE SIE_01_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_CONFG_EVENM_NOTFB_FK1 
  FOREIGN KEY (REF_EVENM_NOTFB) 
  REFERENCES SIE_01_EVENM_NOTFB (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_CONFG_EVENM_NOTFB_FK2 
  FOREIGN KEY (REF_TYPE_COMNC) 
  REFERENCES SIE_01_TYPE_COMNC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_CONFG_EVENM_NOTFB_FK3 
  FOREIGN KEY (REF_PROFL_COURL) 
  REFERENCES SIE_17_PROFL_COURL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_CONFG_EVENM_NOTFB_FK4 
  FOREIGN KEY (REF_COMPT_TWILI) 
  REFERENCES SIE_17_COMPT_TWILI (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_CONFG_EVENM_NOTFB_FK5 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_DESTN;
ALTER TABLE SIE_01_DESTN ADD (
  CONSTRAINT SIE_01_DESTN_FK2 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_DESTN_CONFG_EVENM_NOTFB;
ALTER TABLE SIE_01_DESTN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_DESTN_CONFG_EN_FK1 
  FOREIGN KEY (REF_DV_NATR_DESTN) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_DESTN_CONFG_EN_FK2 
  FOREIGN KEY (REF_CONFG_EVENM_NOTFB) 
  REFERENCES SIE_01_CONFG_EVENM_NOTFB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_DESTN_CONFG_EN_FK3 
  FOREIGN KEY (REF_DESTN) 
  REFERENCES SIE_01_DESTN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_DESTN_CONFG_EVENM_FK4 
  FOREIGN KEY (REF_RESLT_DESTN) 
  REFERENCES SIE_01_RESLT_DESTN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_DESTN_CONFG_EVENM_FK5 
  FOREIGN KEY (REF_ATRIB_SA_NOM_FORMT) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_DESTN_CONFG_EVENM_FK6 
  FOREIGN KEY (REF_ATRIB_SA_ADRES_DESTN) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_ELEMN_CONFG_EVENM_NOTFB;
ALTER TABLE SIE_01_ELEMN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_ELEMN_CONFG_EN_FK1 
  FOREIGN KEY (REF_CONFG_EVENM_NOTFB) 
  REFERENCES SIE_01_CONFG_EVENM_NOTFB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_EVENM_NOTFB;
ALTER TABLE SIE_01_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_EVENM_NOTFB_FK1 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_HIERC_APLIC;
ALTER TABLE SIE_01_HIERC_APLIC ADD (
  CONSTRAINT SIE_12_HIERC_APLIC_FK1 
  FOREIGN KEY (REF_EVENM_NOTFB) 
  REFERENCES SIE_01_EVENM_NOTFB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_HIERC_APLIC_FK2 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_LANG_LANG;
ALTER TABLE SIE_01_LANG_LANG ADD (
  CONSTRAINT SIE_01_LANG_LANG_FK1 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_LANG_LANG_FK2 
  FOREIGN KEY (REF_LANG_CIBLE) 
  REFERENCES SIE_01_LANG (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MESG;
ALTER TABLE SIE_01_MESG ADD (
  CONSTRAINT SIE_01_MESG_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MESG_ERR_LIE;
ALTER TABLE SIE_01_MESG_ERR_LIE ADD (
  CONSTRAINT SIE_01_MESG_ERR_LIE_FK1 
  FOREIGN KEY (REF_CODE_ERR_ORACL) 
  REFERENCES SIE_01_CODE_ERR_ORACL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MESG_ERR_LIE_FK2 
  FOREIGN KEY (REF_MESG) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MESG_ERR_LIE_FK3 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MESG_INFOR;
ALTER TABLE SIE_01_MESG_INFOR ADD (
  CONSTRAINT SIE_01_MESG_INFOR_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MESG_INFOR_FK2 
  FOREIGN KEY (SESS_ID) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MESG_INFOR_FK3 
  FOREIGN KEY (REF_MESG_LANG) 
  REFERENCES SIE_01_MESG_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MESG_LANG;
ALTER TABLE SIE_01_MESG_LANG ADD (
  CONSTRAINT SIE_01_MESG_LANG_FK1 
  FOREIGN KEY (REF_MESG) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MESG_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MESG_TRADC_APEX;
ALTER TABLE SIE_01_MESG_TRADC_APEX ADD (
  CONSTRAINT SIE_01_MESG_TRADC_APEX_FK1 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MODL_AFICH_NOTFC;
ALTER TABLE SIE_01_MODL_AFICH_NOTFC ADD (
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_FK1 
  FOREIGN KEY (REF_RESRC_ICON) 
  REFERENCES SIE_13_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_FK2 
  FOREIGN KEY (REF_FORMT_RESRC_ICON) 
  REFERENCES SIE_13_FORMT_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_FK3 
  FOREIGN KEY (REF_OCURN_RESRC_ICON) 
  REFERENCES SIE_13_OCURN_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_FK4 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_FK5 
  FOREIGN KEY (REF_TYPE_COMNC) 
  REFERENCES SIE_01_TYPE_COMNC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_FK6 
  FOREIGN KEY (REF_MODL_COMNC) 
  REFERENCES SIE_01_MODL_COMNC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MODL_COMNC;
ALTER TABLE SIE_01_MODL_COMNC ADD (
  CONSTRAINT SIE_01_MODL_COMNC_FK1 
  FOREIGN KEY (REF_TYPE_COMNC) 
  REFERENCES SIE_01_TYPE_COMNC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_MODL_COMNC_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_MODL_MESG_NOTFC;
ALTER TABLE SIE_01_MODL_MESG_NOTFC ADD (
  CONSTRAINT SIE_01_MODL_MESG_NOTFC_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_NOTFC;
ALTER TABLE SIE_01_NOTFC ADD (
  CONSTRAINT SIE_01_NOTFC_FK1 
  FOREIGN KEY (REF_MODL_AFICH_NOTFC) 
  REFERENCES SIE_01_MODL_AFICH_NOTFC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_NOTFC_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_OCURN_SA_EVENM_NOTFB;
ALTER TABLE SIE_01_OCURN_SA_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_OCURN_SA_EVENM_NOTF_FK1 
  FOREIGN KEY (REF_HIERC_APLIC) 
  REFERENCES SIE_01_HIERC_APLIC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_OCURN_SA_EVENM_NOTF_FK2 
  FOREIGN KEY (REF_CONFG_EVENM_NOTFB) 
  REFERENCES SIE_01_CONFG_EVENM_NOTFB (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_01_RESLT_DESTN;
ALTER TABLE SIE_01_RESLT_DESTN ADD (
  CONSTRAINT SIE_01_RESLT_DESTN_FK2 
  FOREIGN KEY (REF_DESTN) 
  REFERENCES SIE_01_DESTN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_RESLT_DESTN_FK3 
  FOREIGN KEY (DNR_REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_RESLT_DESTN_FK4 
  FOREIGN KEY (REF_STRUC_APLIC_ACCES) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_03_CLAS_INTER;
ALTER TABLE SIE_03_CLAS_INTER ADD (
  CONSTRAINT SIE_03_CLAS_INTER_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_03_CLAS_INTER_FK2 
  FOREIGN KEY (REF_PROFL_COURL) 
  REFERENCES SIE_17_PROFL_COURL (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_03_JOURN_STRUC_APLIC;
ALTER TABLE SIE_03_JOURN_STRUC_APLIC ADD (
  CONSTRAINT SIE_03_JOURN_STRUC_APLIC_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_03_LIEN_CLAS_INTER_UTILS;
ALTER TABLE SIE_03_LIEN_CLAS_INTER_UTILS ADD (
  CONSTRAINT SIE_03_LIEN_CLAS_INTER_UTI_FK1 
  FOREIGN KEY (REF_CLAS_INTER) 
  REFERENCES SIE_03_CLAS_INTER (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_03_LIEN_CLAS_INTER_UTI_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_03_LIEN_CLAS_INTER_UTI_FK3 
  FOREIGN KEY (REF_GROUP_UTILS) 
  REFERENCES SIE_12_GROUP_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_04_CONTX;
ALTER TABLE SIE_04_CONTX ADD (
  CONSTRAINT SIE_04_CONTX_FK1 
  FOREIGN KEY (REF_FIL_ARIAN) 
  REFERENCES SIE_04_FIL_ARIAN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_04_CONTX_ETEND;
ALTER TABLE SIE_04_CONTX_ETEND ADD (
  CONSTRAINT SIE_04_CONTX_ETEND_FK1 
  FOREIGN KEY (REF_CONTX) 
  REFERENCES SIE_04_CONTX (REF_FIL_ARIAN)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_04_FIL_ARIAN;
ALTER TABLE SIE_04_FIL_ARIAN ADD (
  CONSTRAINT SIE_04_FIL_ARIAN_FK1 
  FOREIGN KEY (SESSION_ID) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_04_FIL_ARIAN_FK2 
  FOREIGN KEY (REF_ELEMN_SUP) 
  REFERENCES SIE_04_FIL_ARIAN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_04_FIL_ARIAN_FK3 
  FOREIGN KEY (REF_NAVGT_HISTR) 
  REFERENCES SIE_04_NAVGT_HISTR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_04_NAVGT_HISTR;
ALTER TABLE SIE_04_NAVGT_HISTR ADD (
  CONSTRAINT SIE_04_NAVGT_HISTR_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_07_AUDIT_STRUC_APLIC;
ALTER TABLE SIE_07_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT SIE_07_AUDIT_STRUC_APLIC_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_07_AUDIT_STRUC_APLIC_FK2 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_07_AUDIT_STRUC_APLIC_FK3 
  FOREIGN KEY (REF_ACTIO_AUDIT) 
  REFERENCES SIE_12_ACTIO_AUDIT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_07_AUDIT_STRUC_APLIC_FK4 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_07_AUDIT_STRUC_APLIC_FK5 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_07_ETAT_SESN;
ALTER TABLE SIE_07_ETAT_SESN ADD (
  CONSTRAINT SIE_07_ETAT_SESN_FK1 
  FOREIGN KEY (SESSION_ID) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_07_INSTA_SEMPH;
ALTER TABLE SIE_07_INSTA_SEMPH ADD (
  CONSTRAINT SIE_07_INSTA_SEMPH_FK1 
  FOREIGN KEY (REF_SEMPH) 
  REFERENCES SIE_07_SEMPH (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_07_INSTA_SEMPH_FK2 
  FOREIGN KEY (ID_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_07_VALR_AUDIT_STRUC_APLIC;
ALTER TABLE SIE_07_VALR_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT SIE_07_VALR_AUDIT_SA_FK1 
  FOREIGN KEY (REF_AUDIT_STRUC_APLIC) 
  REFERENCES SIE_07_AUDIT_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_APLIC;
ALTER TABLE SIE_11_APLIC ADD (
  CONSTRAINT SIE_11_APLIC_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_APLIC_FK2 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_APLIC_FK3 
  FOREIGN KEY (REF_APLIC_AUTHE) 
  REFERENCES SIE_11_APLIC (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_APLIC_FK4 
  FOREIGN KEY (REF_PAGE_CONXN) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_APLIC_FK5 
  FOREIGN KEY (REF_PAGE_ACUEI) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_ATRIB_ENTIT;
ALTER TABLE SIE_11_ATRIB_ENTIT ADD (
  CONSTRAINT SIE_11_ATRIB_ENTIT_FK1 
  FOREIGN KEY (REF_ENTIT) 
  REFERENCES SIE_11_ENTIT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_ATRIB_ENTIT_FK2 
  FOREIGN KEY (REF_ENTIT_REFRN) 
  REFERENCES SIE_11_ENTIT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_ENTIT;
ALTER TABLE SIE_11_ENTIT ADD (
  CONSTRAINT SIE_11_ENTIT_FK1 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_ENTIT_FK2 
  FOREIGN KEY (REF_ATRIB_ENTIT_SUPR) 
  REFERENCES SIE_11_ATRIB_ENTIT (SEQNC)
  ON DELETE SET NULL
  DISABLE NOVALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_PLUGN;
ALTER TABLE SIE_11_PLUGN ADD (
  CONSTRAINT SIE_11_PLUGN_FK1 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_PRODT;
ALTER TABLE SIE_11_PRODT ADD (
  CONSTRAINT SIE_11_PRODT_FK1 
  FOREIGN KEY (REF_GROUP_UTILS_ADMIN) 
  REFERENCES SIE_12_GROUP_UTILS (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK10 
  FOREIGN KEY (REF_MESG_RANGE_MODF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK11 
  FOREIGN KEY (REF_MESG_RANGE_INSER) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK12 
  FOREIGN KEY (REF_MESG_AUCUN_DON_TROUV) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK13 
  FOREIGN KEY (REF_MESG_TROP_DON_TROUV) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK14 
  FOREIGN KEY (REF_MESG_AUDIT_CREAT) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK15 
  FOREIGN KEY (REF_MESG_AUDIT_MODFC) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK16 
  FOREIGN KEY (REF_MESG_AUDIT_SUPRS) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK3 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK6 
  FOREIGN KEY (REF_MESG_SUCS) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK7 
  FOREIGN KEY (REF_MESG_ECHEC) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK8 
  FOREIGN KEY (REF_MESG_FETCH) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_FK9 
  FOREIGN KEY (REF_MESG_RANGE_SUPRM) 
  REFERENCES SIE_01_MESG (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_PRODT_LANG;
ALTER TABLE SIE_11_PRODT_LANG ADD (
  CONSTRAINT SIE_11_PRODT_LANG_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_PRODT_RESRC;
ALTER TABLE SIE_11_PRODT_RESRC ADD (
  CONSTRAINT SIE_11_PRODT_RESRC_FK2 
  FOREIGN KEY (REF_RESRC) 
  REFERENCES SIE_13_RESRC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_PRODT_RESRC_FK3 
  FOREIGN KEY (REF_FORMT) 
  REFERENCES SIE_13_FORMT_RESRC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_UTILS;
ALTER TABLE SIE_11_UTILS ADD (
  CONSTRAINT SIE_11_UTILS_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_UTILS_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_11_VERSN;
ALTER TABLE SIE_11_VERSN ADD (
  CONSTRAINT SIE_11_VERSN_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_VERSN_FK2 
  FOREIGN KEY (REF_PLUGN) 
  REFERENCES SIE_11_PLUGN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_VERSN_FK90 
  FOREIGN KEY (REF_APLIC) 
  REFERENCES SIE_11_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_ACTIO_AUDIT;
ALTER TABLE SIE_12_ACTIO_AUDIT ADD (
  CONSTRAINT SIE_12_ACTIO_AUDIT_FK1 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_ACTIO_AUDIT_FK2 
  FOREIGN KEY (REF_MESG) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_ARBRE;
ALTER TABLE SIE_12_ARBRE ADD (
  CONSTRAINT SIE_12_ARBRE_FK2 
  FOREIGN KEY (REF_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_ARBRE_NOEUD;
ALTER TABLE SIE_12_ARBRE_NOEUD ADD (
  CONSTRAINT SIE_12_ARBRE_NOEUD_FK1 
  FOREIGN KEY (REF_ARBRE) 
  REFERENCES SIE_12_ARBRE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_ATRIB_STRUC_APLIC;
ALTER TABLE SIE_12_ATRIB_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_ATRIB_STRUC_APLIC_FK1 
  FOREIGN KEY (REF_DV_NATR_INFOR) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_ATRIB_STRUC_APLIC_FK2 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_ATRIB_STRUC_APLIC_FK3 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_COMPT_PAYPL;
ALTER TABLE SIE_12_COMPT_PAYPL ADD (
  CONSTRAINT SIE_12_COMPT_PAYPL_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_DEFNT_ACCES;
ALTER TABLE SIE_12_DEFNT_ACCES ADD (
  CONSTRAINT SIE_12_DEFNT_ACCES_FK2 
  FOREIGN KEY (REF_GROUP_UTILS) 
  REFERENCES SIE_12_GROUP_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DEFNT_ACCES_FK4 
  FOREIGN KEY (REF_OPERT) 
  REFERENCES SIE_13_OPERT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DEFNT_ACCES_FK6 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DEFNT_ACCES_FK7 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_DETL_FORML;
ALTER TABLE SIE_12_DETL_FORML ADD (
  CONSTRAINT SIE_12_DETL_FORML_FK1 
  FOREIGN KEY (REF_FORML) 
  REFERENCES SIE_12_FORML (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DETL_FORML_FK3 
  FOREIGN KEY (REF_DOMN_VALR) 
  REFERENCES SIE_14_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_DOMN;
ALTER TABLE SIE_12_DOMN ADD (
  CONSTRAINT SIE_12_DOMN_FK1 
  FOREIGN KEY (REF_MODL_RECHR_DEFT) 
  REFERENCES SIE_23_MODL_RECHR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DOMN_FK2 
  FOREIGN KEY (TYPE_TRAVL_DEFT) 
  REFERENCES SIE_25_TYPE_TRAVL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DOMN_FK4 
  FOREIGN KEY (REF_PROFL_COURL_NOTFC) 
  REFERENCES SIE_17_PROFL_COURL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DOMN_FK5 
  FOREIGN KEY (REF_PROFL_SMS_NOTFC) 
  REFERENCES SIE_17_COMPT_TWILI (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DOMN_FK6 
  FOREIGN KEY (REF_COMPT_AXIAT_DEFT) 
  REFERENCES SIE_17_COMPT_AXIAT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_DOMN_FONCT;
ALTER TABLE SIE_12_DOMN_FONCT ADD (
  CONSTRAINT SIE_12_DOMN_FONCT_FK1 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES SIE_12_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DOMN_FONCT_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_DOMN_UTILS;
ALTER TABLE SIE_12_DOMN_UTILS ADD (
  CONSTRAINT SIE_12_DOMN_UTILS_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_DOMN_UTILS_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_EVOLT_STAT;
ALTER TABLE SIE_12_EVOLT_STAT ADD (
  CONSTRAINT SIE_12_EVOLT_STAT_FK1 
  FOREIGN KEY (REF_STAT) 
  REFERENCES SIE_12_STAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_EVOLT_STAT_FK2 
  FOREIGN KEY (REF_STAT_EVOLT) 
  REFERENCES SIE_12_STAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_FAVR;
ALTER TABLE SIE_12_FAVR ADD (
  CONSTRAINT SIE_12_FAVR_FK1 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_FAVR_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_FONCT;
ALTER TABLE SIE_12_FONCT ADD (
  CONSTRAINT SIE_12_FONCT_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_FONCT_STRUC_APLIC;
ALTER TABLE SIE_12_FONCT_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_FONCT_STRUC_APLIC_FK1 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES SIE_12_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_FONCT_STRUC_APLIC_FK2 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_FORML;
ALTER TABLE SIE_12_FORML ADD (
  CONSTRAINT SIE_12_FORML_FK1 
  FOREIGN KEY (REF_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_GROUP_STAT;
ALTER TABLE SIE_12_GROUP_STAT ADD (
  CONSTRAINT SIE_12_GROUP_STAT_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_GROUP_UTILS;
ALTER TABLE SIE_12_GROUP_UTILS ADD (
  CONSTRAINT SIE_12_GROUP_UTILS_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_GROUP_UTILS_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_GROUP_UTILS_FK3 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES SIE_12_FONCT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_GR_UT_OPERT_OPTIO_DOMN;
ALTER TABLE SIE_12_GR_UT_OPERT_OPTIO_DOMN ADD (
  CONSTRAINT SIE_12_GU_OPER_OPT_DOMN_FK1 
  FOREIGN KEY (REF_GROUP_UTILS) 
  REFERENCES SIE_12_GROUP_UTILS (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_GU_OPER_OPT_DOMN_FK2 
  FOREIGN KEY (REF_OPERT) 
  REFERENCES SIE_13_OPERT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_GU_OPER_OPT_DOMN_FK3 
  FOREIGN KEY (REF_OPERT_OPTIO) 
  REFERENCES SIE_13_OPERT_OPTIO (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_GU_OPER_OPT_DOMN_FK4 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_HISTR_ACCES;
ALTER TABLE SIE_12_HISTR_ACCES ADD (
  CONSTRAINT SIE_12_HISTR_ACCES_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_HISTR_ACCES_FK2 
  FOREIGN KEY (REF_DV_TYPE_EVENM) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_HISTR_ACCES_FK3 
  FOREIGN KEY (REF_UTILS_POUR) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_LIEN_GROUP_UTILS;
ALTER TABLE SIE_12_LIEN_GROUP_UTILS ADD (
  CONSTRAINT SIE_12_LIEN_GROUP_UTILS_FK1 
  FOREIGN KEY (REF_GROUP) 
  REFERENCES SIE_12_GROUP_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_LIEN_GROUP_UTILS_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_LIEN_GROUP_UTILS_FK3 
  FOREIGN KEY (REF_GROUP_UTILS_LIE) 
  REFERENCES SIE_12_GROUP_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_LIEN_GROUP_UTILS_FK4 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_LIEN_STRUC;
ALTER TABLE SIE_12_LIEN_STRUC ADD (
  CONSTRAINT SIE_12_LIEN_STRUC_FK1 
  FOREIGN KEY (REF_STRUC_ADMIN) 
  REFERENCES SIE_12_STRUC_ADMIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_LIEN_STRUC_FK3 
  FOREIGN KEY (REF_STRUC_LIE) 
  REFERENCES SIE_12_STRUC_ADMIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_MEMBR_STRUC;
ALTER TABLE SIE_12_MEMBR_STRUC ADD (
  CONSTRAINT SIE_12_MEMBR_STRUC_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_MEMBR_STRUC_FK2 
  FOREIGN KEY (REF_STRUC_ADMIN) 
  REFERENCES SIE_12_STRUC_ADMIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_PAYPL_RETR_APLIC;
ALTER TABLE SIE_12_PAYPL_RETR_APLIC ADD (
  CONSTRAINT SIE_12_PAYPL_RETR_APLIC_FK1 
  FOREIGN KEY (REF_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_PAYPL_RETR_APLIC_FK4 
  FOREIGN KEY (REF_COMPT_PAYPL) 
  REFERENCES SIE_12_COMPT_PAYPL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_PAYPL_RETR_APLIC_FK5 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_REQT_INTER_UTILS;
ALTER TABLE SIE_12_REQT_INTER_UTILS ADD (
  CONSTRAINT SIE_12_REQT_INTER_UTILS_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_REQT_INTER_UTILS_FK2 
  FOREIGN KEY (REF_DV_TYPE_REQT_INTER) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_REQT_INTER_UTILS_FK3 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_REQT_INTER_UTILS_FK4 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_SESN;
ALTER TABLE SIE_12_SESN ADD (
  CONSTRAINT SIE_12_SESN_FK1 
  FOREIGN KEY (ID_SESN) 
  REFERENCES APEX_040200.WWV_FLOW_SESSIONS$ (ID)
  ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_SESN_FK2 
  FOREIGN KEY (REF_ID_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_SESN_FK3 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_STAT;
ALTER TABLE SIE_12_STAT ADD (
  CONSTRAINT SIE_12_STAT_FK1 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STAT_FK2 
  FOREIGN KEY (REF_GROUP_STAT) 
  REFERENCES SIE_12_GROUP_STAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_STRUC_ADMIN;
ALTER TABLE SIE_12_STRUC_ADMIN ADD (
  CONSTRAINT SIE_12_STRUC_ADMIN_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_ADMIN_FK2 
  FOREIGN KEY (REF_TYPE_STRUC) 
  REFERENCES SIE_12_TYPE_STRUC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_ADMIN_FK3 
  FOREIGN KEY (REF_RESPN) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_STRUC_APLIC;
ALTER TABLE SIE_12_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_APLIC_FK2 
  FOREIGN KEY (REF_MESG_ERR_SUPRS) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_APLIC_FK3 
  FOREIGN KEY (REF_PAGE_LISTE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_APLIC_FK4 
  FOREIGN KEY (REF_PAGE_FORML) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_APLIC_FK6 
  FOREIGN KEY (DNR_REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_STRUC_APLIC_DESTN;
ALTER TABLE SIE_12_STRUC_APLIC_DESTN ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_DESTN_FK2 
  FOREIGN KEY (REF_DESTN) 
  REFERENCES SIE_01_DESTN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_STRUC_APLIC_LANG;
ALTER TABLE SIE_12_STRUC_APLIC_LANG ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_LANG_FK1 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_STRUC_APLIC_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_TYPE_STRUC;
ALTER TABLE SIE_12_TYPE_STRUC ADD (
  CONSTRAINT SIE_12_TYPE_STRUC_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_12_UTILS;
ALTER TABLE SIE_12_UTILS ADD (
  CONSTRAINT SIE_12_UTILS_FK1 
  FOREIGN KEY (REF_DV_COMPL_MAXM) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_CONDT_PILTB;
ALTER TABLE SIE_13_CONDT_PILTB ADD (
  CONSTRAINT SIE_13_CONDT_PILTB_FK1 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_CONDT_PILTB_FK2 
  FOREIGN KEY (REF_PAGE_ITEM_FOCUS) 
  REFERENCES SIE_13_PAGE_ITEM (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_DOSR_VIRTL;
ALTER TABLE SIE_13_DOSR_VIRTL ADD (
  CONSTRAINT SIE_13_DOSR_VIRTL_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_EMPLA_DOSR_VIRTL;
ALTER TABLE SIE_13_EMPLA_DOSR_VIRTL ADD (
  CONSTRAINT SIE_13_EMPLA_DOSR_VIRTL_FK1 
  FOREIGN KEY (REF_DOSR_VIRTL) 
  REFERENCES SIE_13_DOSR_VIRTL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_EMPLA_DOSR_VIRTL_FK2 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_EXPOR_APLIC;
ALTER TABLE SIE_13_EXPOR_APLIC ADD (
  CONSTRAINT SIE_13_EXPOR_APLIC_FK1 
  FOREIGN KEY (REF_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_EXPOR_APLIC_FK2 
  FOREIGN KEY (REF_APLIC) 
  REFERENCES SIE_11_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_FORMT_RESRC;
ALTER TABLE SIE_13_FORMT_RESRC ADD (
  CONSTRAINT SIE_13_FORMT_RESRC_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_FORMT_RESRC_FK2 
  FOREIGN KEY (REF_TYPE_FICHR) 
  REFERENCES SIE_13_TYPE_FICHR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_INSTA_PREFR;
ALTER TABLE SIE_13_INSTA_PREFR ADD (
  CONSTRAINT SIE_13_INSTA_PREFR_FK1 
  FOREIGN KEY (REF_PREFR) 
  REFERENCES SIE_13_PREFR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_INSTA_PREFR_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_INSTA_PREFR_FK3 
  FOREIGN KEY (REF_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_INSTA_PREFR_FK4 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_ITEM_MENU;
ALTER TABLE SIE_13_ITEM_MENU ADD (
  CONSTRAINT SIE_13_ITEM_MENU_FK1 
  FOREIGN KEY (REF_MENU) 
  REFERENCES SIE_13_MENU (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK10 
  FOREIGN KEY (REF_DV_VALR_SAPC) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK11 
  FOREIGN KEY (REF_DV_VALR_SAPI) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK12 
  FOREIGN KEY (REF_DV_VALR_SCPC) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK13 
  FOREIGN KEY (REF_DV_VALR_SCPI) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK14 
  FOREIGN KEY (REF_DV_VALR_SNPI) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK15 
  FOREIGN KEY (REF_DV_VALR_SSPC) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK16 
  FOREIGN KEY (REF_DV_VALR_SSPI) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK17 
  FOREIGN KEY (REF_DV_VALR_URL) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK18 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK19 
  FOREIGN KEY (REF_DV_VALR_INSTA_CONDT_AFICH) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK3 
  FOREIGN KEY (REF_DV_VALR_INSTA_LIBL) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK4 
  FOREIGN KEY (REF_RESRC) 
  REFERENCES SIE_13_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK5 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK6 
  FOREIGN KEY (REF_FORMT_RESRC) 
  REFERENCES SIE_13_FORMT_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK7 
  FOREIGN KEY (REF_OCURN_RESRC) 
  REFERENCES SIE_13_OCURN_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK8 
  FOREIGN KEY (REF_ITEM_MENU) 
  REFERENCES SIE_13_ITEM_MENU (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK9 
  FOREIGN KEY (REF_DV_VALR_REQST) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_ITEM_MENU_FK90 
  FOREIGN KEY (REF_APLIC) 
  REFERENCES SIE_11_APLIC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_LIEN_CONDT_PILTB;
ALTER TABLE SIE_13_LIEN_CONDT_PILTB ADD (
  CONSTRAINT SIE_13_LIEN_CONDT_PILTB_FK1 
  FOREIGN KEY (REF_PAGE_ITEM) 
  REFERENCES SIE_13_PAGE_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_LIEN_CONDT_PILTB_FK2 
  FOREIGN KEY (REF_CONDT_PILTB) 
  REFERENCES SIE_13_CONDT_PILTB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_LISTE_NAVGT;
ALTER TABLE SIE_13_LISTE_NAVGT ADD (
  CONSTRAINT SIE_13_LISTE_NAVGT_FK1 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_MENU;
ALTER TABLE SIE_13_MENU ADD (
  CONSTRAINT SIE_13_MENU_FK2 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_MIME_TYPE;
ALTER TABLE SIE_13_MIME_TYPE ADD (
  CONSTRAINT SIE_13_MIME_TYPE_FK1 
  FOREIGN KEY (REF_TYPE_FICHR) 
  REFERENCES SIE_13_TYPE_FICHR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_NAVGT;
ALTER TABLE SIE_13_NAVGT ADD (
  CONSTRAINT SIE_13_NAVGT_FK1 
  FOREIGN KEY (REF_ID_SESN) 
  REFERENCES SIE_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_NAVGT_FK2 
  FOREIGN KEY (REF_FIL_ARIAN) 
  REFERENCES SIE_04_FIL_ARIAN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_NAVGT_FK3 
  FOREIGN KEY (REF_RAPRT_INTER) 
  REFERENCES SIE_13_PAGE_IR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_NAVGT_ELEMN;
ALTER TABLE SIE_13_NAVGT_ELEMN ADD (
  CONSTRAINT SIE_13_NAVGT_ELEMN_FK1 
  FOREIGN KEY (REF_NAVGT) 
  REFERENCES SIE_13_NAVGT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_OCURN_RESRC;
ALTER TABLE SIE_13_OCURN_RESRC ADD (
  CONSTRAINT SIE_13_OCURN_RESRC_FK1 
  FOREIGN KEY (REF_RESRC) 
  REFERENCES SIE_13_RESRC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_OCURN_RESRC_FK2 
  FOREIGN KEY (REF_FORMT_RESRC) 
  REFERENCES SIE_13_FORMT_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_OCURN_RESRC_FK3 
  FOREIGN KEY (REF_MIME_TYPE) 
  REFERENCES SIE_13_MIME_TYPE (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_OCURN_RESRC_FK4 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_OCURN_RESRC_FK5 
  FOREIGN KEY (REF_DOSR_VIRTL) 
  REFERENCES SIE_13_DOSR_VIRTL (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_OPERT;
ALTER TABLE SIE_13_OPERT ADD (
  CONSTRAINT SIE_13_OPERT_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_OPERT_FK2 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES SIE_12_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_OPERT_OPTIO;
ALTER TABLE SIE_13_OPERT_OPTIO ADD (
  CONSTRAINT SIE_13_OPERT_OPTIO_FK1 
  FOREIGN KEY (REF_OPERT) 
  REFERENCES SIE_13_OPERT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PAGE;
ALTER TABLE SIE_13_PAGE ADD (
  CONSTRAINT SIE_13_PAGE_FK10 
  FOREIGN KEY (REF_MESG_RANGE_MODF_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK11 
  FOREIGN KEY (REF_MESG_RANGE_INSER_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK12 
  FOREIGN KEY (REF_MESG_AUCUN_DON_TROUV) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK13 
  FOREIGN KEY (REF_MESG_TROP_DON_TROUV) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK3 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK4 
  FOREIGN KEY (REF_MESG_SUPRS_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK5 
  FOREIGN KEY (REF_PAGE_RECHR) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK6 
  FOREIGN KEY (REF_MESG_SUCS_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK7 
  FOREIGN KEY (REF_MESG_ECHEC_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK8 
  FOREIGN KEY (REF_MESG_FETCH_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK9 
  FOREIGN KEY (REF_MESG_RANGE_SUPRM_SPECF) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_FK90 
  FOREIGN KEY (REF_APLIC) 
  REFERENCES SIE_11_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PAGE_IR;
ALTER TABLE SIE_13_PAGE_IR ADD (
  CONSTRAINT SIE_13_PAGE_IR_FK1 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PAGE_IR_COLN;
ALTER TABLE SIE_13_PAGE_IR_COLN ADD (
  CONSTRAINT SIE_13_PAGE_IR_COLN_FK1 
  FOREIGN KEY (REF_PAGE_IR) 
  REFERENCES SIE_13_PAGE_IR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_IR_COLN_FK2 
  FOREIGN KEY (REF_MESG_AIDE) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PAGE_ITEM;
ALTER TABLE SIE_13_PAGE_ITEM ADD (
  CONSTRAINT SIE_13_PAGE_ITEM_FK1 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_ITEM_FK2 
  FOREIGN KEY (REF_MESG_AIDE) 
  REFERENCES SIE_01_MESG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_ITEM_FK3 
  FOREIGN KEY (REF_OPERT) 
  REFERENCES SIE_13_OPERT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PAGE_ITEM_LANG;
ALTER TABLE SIE_13_PAGE_ITEM_LANG ADD (
  CONSTRAINT SIE_13_PAGE_ITEM_LANG_FK1 
  FOREIGN KEY (REF_PAGE_ITEM) 
  REFERENCES SIE_13_PAGE_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_ITEM_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PAGE_LANG;
ALTER TABLE SIE_13_PAGE_LANG ADD (
  CONSTRAINT SIE_13_PAGE_LANG_FK1 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_PREFR;
ALTER TABLE SIE_13_PREFR ADD (
  CONSTRAINT SIE_13_PREFR_FK1 
  FOREIGN KEY (REF_DV_CONDT_UTILS) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PREFR_FK2 
  FOREIGN KEY (REF_DV_CONDT_SAUVG) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PREFR_FK3 
  FOREIGN KEY (REF_DV_TYPE_INSTA) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PREFR_FK4 
  FOREIGN KEY (REF_DV_VALR_INSTA) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PREFR_FK6 
  FOREIGN KEY (REF_ITEM) 
  REFERENCES SIE_13_PAGE_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_REGN_PILTB;
ALTER TABLE SIE_13_REGN_PILTB ADD (
  CONSTRAINT SIE_13_REGN_PILTB_FK1 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_REGN_PILTB_FK2 
  FOREIGN KEY (REF_DV_TYPE_REGN_PILTB) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_REGN_PILTB_LANG;
ALTER TABLE SIE_13_REGN_PILTB_LANG ADD (
  CONSTRAINT SIE_13_REGN_PILTB_LANG_FK1 
  FOREIGN KEY (REF_REGN_PILTB) 
  REFERENCES SIE_13_REGN_PILTB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_REGN_PILTB_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_13_RESRC;
ALTER TABLE SIE_13_RESRC ADD (
  CONSTRAINT SIE_13_RESRC_FK1 
  FOREIGN KEY (REF_TYPE_FICHR) 
  REFERENCES SIE_13_TYPE_FICHR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_RESRC_FK2 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_RESRC_FK3 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_RESRC_FK4 
  FOREIGN KEY (REF_DOSR_VIRTL) 
  REFERENCES SIE_13_DOSR_VIRTL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_14_DETL_DOMN_VALR;
ALTER TABLE SIE_14_DETL_DOMN_VALR ADD (
  CONSTRAINT SIE_14_DETL_DOMN_VALR_FK1 
  FOREIGN KEY (REF_DOMN_VALR) 
  REFERENCES SIE_14_DOMN_VALR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_14_DOMN_VALR;
ALTER TABLE SIE_14_DOMN_VALR ADD (
  CONSTRAINT SIE_14_DOMN_VALR_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_14_DOMN_VALR_FK2 
  FOREIGN KEY (REF_FORMT) 
  REFERENCES SIE_14_FORMT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_14_DOMN_VALR_FK3 
  FOREIGN KEY (REF_TYPE_DOMN_VALR) 
  REFERENCES SIE_14_TYPE_DOMN_VALR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_14_DOMN_VALR_FK4 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_14_FORMT;
ALTER TABLE SIE_14_FORMT ADD (
  CONSTRAINT SIE_14_FORMT_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_14_TYPE_DOMN_VALR;
ALTER TABLE SIE_14_TYPE_DOMN_VALR ADD (
  CONSTRAINT SIE_14_TYPE_DOMN_VALR_FK1 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_ATACH_COURL_ENTRA;
ALTER TABLE SIE_17_ATACH_COURL_ENTRA ADD (
  CONSTRAINT SIE_17_ATACH_COURL_ENTRA_FK1 
  FOREIGN KEY (REF_COURL_ENTRA) 
  REFERENCES SIE_17_COURL_ENTRA (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_17_ATACH_COURL_ENTRA_FK2 
  FOREIGN KEY (REF_MIME_TYPE) 
  REFERENCES SIE_13_MIME_TYPE (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_COMPT_AXIAT;
ALTER TABLE SIE_17_COMPT_AXIAT ADD (
  CONSTRAINT SIE_17_COMPT_AXIAT_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_17_COMPT_AXIAT_FK2 
  FOREIGN KEY (REF_PROFL_COURL) 
  REFERENCES SIE_17_PROFL_COURL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_17_COMPT_AXIAT_FK3 
  FOREIGN KEY (REF_PUBLC_PAGE_GARDE) 
  REFERENCES SIE_25_PUBLC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_COMPT_TWILI;
ALTER TABLE SIE_17_COMPT_TWILI ADD (
  CONSTRAINT SIE_17_COOMPT_TWILI_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_COURL_DESTN;
ALTER TABLE SIE_17_COURL_DESTN ADD (
  CONSTRAINT SIE_17_FIL_ATENT_DESTN_FK1 
  FOREIGN KEY (REF_FIL_ATENT) 
  REFERENCES SIE_17_COURL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_COURL_ENTRA;
ALTER TABLE SIE_17_COURL_ENTRA ADD (
  CONSTRAINT SIE_17_COURL_ENTRA_FK1 
  FOREIGN KEY (REF_PROFL_COURL) 
  REFERENCES SIE_17_PROFL_COURL (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_COURL_PIECE_JOINT;
ALTER TABLE SIE_17_COURL_PIECE_JOINT ADD (
  CONSTRAINT SIE_17_COURL_PIECE_JOINT_FK1 
  FOREIGN KEY (REF_COURL) 
  REFERENCES SIE_17_COURL (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_PIECE_TELCP_AXIAT;
ALTER TABLE SIE_17_PIECE_TELCP_AXIAT ADD (
  CONSTRAINT SIE_17_PIECE_TELCP_AXIAT_FK1 
  FOREIGN KEY (REF_TELCP_AXIAT) 
  REFERENCES SIE_17_TELCP_AXIAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_PROFL_COURL;
ALTER TABLE SIE_17_PROFL_COURL ADD (
  CONSTRAINT SIE_17_PROFL_COURL_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_PROPR_COURL_ENTRA;
ALTER TABLE SIE_17_PROPR_COURL_ENTRA ADD (
  CONSTRAINT SIE_17_PROPR_COURL_ENTRA_FK1 
  FOREIGN KEY (REF_COURL_ENTRA) 
  REFERENCES SIE_17_COURL_ENTRA (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_SMS_TWILI;
ALTER TABLE SIE_17_SMS_TWILI ADD (
  CONSTRAINT SIE_17_SMS_TWILI_FK1 
  FOREIGN KEY (REF_COMPT_TWILI) 
  REFERENCES SIE_17_COMPT_TWILI (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_17_TELCP_AXIAT;
ALTER TABLE SIE_17_TELCP_AXIAT ADD (
  CONSTRAINT SIE_17_TELCP_AXIAT_FK1 
  FOREIGN KEY (REF_COMPT_AXIAT) 
  REFERENCES SIE_17_COMPT_AXIAT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_19_BOUTN;
ALTER TABLE SIE_19_BOUTN ADD (
  CONSTRAINT SIE_19_BOUTN_FK1 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_BOUTN_FK2 
  FOREIGN KEY (REF_DISPN_FONCT) 
  REFERENCES SIE_19_DISPN_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_BOUTN_FK3 
  FOREIGN KEY (REF_DV_TYPE_MESG_AIDE_CONTX) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_19_CLE;
ALTER TABLE SIE_19_CLE ADD (
  CONSTRAINT SIE_19_CLE_FK1 
  FOREIGN KEY (REF_DISPN_FONCT) 
  REFERENCES SIE_19_DISPN_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_CLE_FK3 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_19_DISPN_FONCT;
ALTER TABLE SIE_19_DISPN_FONCT ADD (
  CONSTRAINT SIE_19_DISPN_FONCT_FK2 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES SIE_19_FONCT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_19_FONCT;
ALTER TABLE SIE_19_FONCT ADD (
  CONSTRAINT SIE_19_FONCT_FK1 
  FOREIGN KEY (REF_DV_TYPE_ATRIB1) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_FK2 
  FOREIGN KEY (REF_DV_TYPE_ATRIB2) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_FK3 
  FOREIGN KEY (REF_DV_TYPE_ATRIB3) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_FK4 
  FOREIGN KEY (REF_DV_TYPE_ATRIB4) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_FK5 
  FOREIGN KEY (REF_DV_TYPE_ATRIB5) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_FK6 
  FOREIGN KEY (REF_DV_TYPE_ACTIO) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_FK7 
  FOREIGN KEY (REF_DV_TYPE_EXPRE) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_19_FONCT_LANG;
ALTER TABLE SIE_19_FONCT_LANG ADD (
  CONSTRAINT SIE_19_FONCT_LANG_FK1 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES SIE_19_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_FONCT_LANG_FK2 
  FOREIGN KEY (REF_LANG) 
  REFERENCES SIE_01_LANG (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_19_SPECF_FONCT;
ALTER TABLE SIE_19_SPECF_FONCT ADD (
  CONSTRAINT SIE_19_SPECF_FONCT_FK1 
  FOREIGN KEY (REF_DISPN_FONCT) 
  REFERENCES SIE_19_DISPN_FONCT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_SPECF_FONCT_FK2 
  FOREIGN KEY (REF_ITEM) 
  REFERENCES SIE_13_PAGE_ITEM (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_SPECF_FONCT_FK3 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_SPECF_FONCT_FK4 
  FOREIGN KEY (REF_DV_TYPE_SUBST) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_19_SPECF_FONCT_FK98 
  FOREIGN KEY (DNR_REF_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_20_DEPLM;
ALTER TABLE SIE_20_DEPLM ADD (
  CONSTRAINT SIE_20_DEPLM_FK1 
  FOREIGN KEY (REF_MODL) 
  REFERENCES SIE_20_MODL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_20_DEPLM_FK2 
  FOREIGN KEY (REF_MODL_PARMT) 
  REFERENCES SIE_20_MODL_PARMT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_20_DETL_DOCMN;
ALTER TABLE SIE_20_DETL_DOCMN ADD (
  CONSTRAINT SIE_20_DETL_DOCMN_FK1 
  FOREIGN KEY (REF_DOCMN) 
  REFERENCES SIE_20_DOCMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_20_DETL_DOCMN_FK2 
  FOREIGN KEY (REF_SECTN_DOCMN) 
  REFERENCES SIE_20_SECTN_DOCMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_20_DETL_DOCMN_FK3 
  FOREIGN KEY (REF_DETL_DOCMN) 
  REFERENCES SIE_20_DETL_DOCMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_20_MODL;
ALTER TABLE SIE_20_MODL ADD (
  CONSTRAINT SIE_20_MODL_FK1 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES SIE_11_VERSN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_20_MODL_FK2 
  FOREIGN KEY (REF_MODL) 
  REFERENCES SIE_20_MODL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_20_MODL_FK3 
  FOREIGN KEY (REF_DV_TYPE_MODL) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_20_MODL_EXCEP;
ALTER TABLE SIE_20_MODL_EXCEP ADD (
  CONSTRAINT SIE_20_MODL_EXCEP_FK1 
  FOREIGN KEY (REF_MODL) 
  REFERENCES SIE_20_MODL (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_20_MODL_PARMT;
ALTER TABLE SIE_20_MODL_PARMT ADD (
  CONSTRAINT SIE_20_MODL_PARMT_FK1 
  FOREIGN KEY (REF_MODL) 
  REFERENCES SIE_20_MODL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_20_MODL_PARMT_FK2 
  FOREIGN KEY (REF_DV_TYPE_DON) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_20_SECTN_DOCMN;
ALTER TABLE SIE_20_SECTN_DOCMN ADD (
  CONSTRAINT SIE_20_SECTN_DOCMN_FK1 
  FOREIGN KEY (REF_SECTN_DOCMN) 
  REFERENCES SIE_20_SECTN_DOCMN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_21_PLUGN_ARBRE;
ALTER TABLE SIE_21_PLUGN_ARBRE ADD (
  CONSTRAINT SIE_21_PLUGN_ARBRE_FK2 
  FOREIGN KEY (REF_PLUGN_ARBRE_NOEUD) 
  REFERENCES SIE_21_PLUGN_ARBRE_NOEUD (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ARBRE_FK3 
  FOREIGN KEY (REF_FORMT_RESRC) 
  REFERENCES SIE_13_FORMT_RESRC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ARBRE_FK4 
  FOREIGN KEY (REF_DV_CURSR_AIDE_INSTA) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_21_PLUGN_ARBRE_NOEUD;
ALTER TABLE SIE_21_PLUGN_ARBRE_NOEUD ADD (
  CONSTRAINT SIE_21_PLUGN_ARBRE_NOEUD_FK1 
  FOREIGN KEY (REF_PLUGN_ARBRE) 
  REFERENCES SIE_21_PLUGN_ARBRE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ARBRE_NOEUD_FK2 
  FOREIGN KEY (REF_RESRC) 
  REFERENCES SIE_13_RESRC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ARBRE_NOEUD_FK3 
  FOREIGN KEY (REF_OCURN_RESRC) 
  REFERENCES SIE_13_OCURN_RESRC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_21_PLUGN_CALND;
ALTER TABLE SIE_21_PLUGN_CALND ADD (
  CONSTRAINT SIE_21_PLUGN_CALND_FK2 
  FOREIGN KEY (REF_DV_VUE_DEFT) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_21_PLUGN_CALND_TYPE;
ALTER TABLE SIE_21_PLUGN_CALND_TYPE ADD (
  CONSTRAINT SIE_21_PLUGN_CALND_TYPE_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_21_PLUGN_ITEM_MENU;
ALTER TABLE SIE_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT SIE_21_PLUGN_ITEM_MENU_FK1 
  FOREIGN KEY (REF_ITEM_MENU) 
  REFERENCES SIE_13_ITEM_MENU (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ITEM_MENU_FK2 
  FOREIGN KEY (REF_PLUGN_MENU) 
  REFERENCES SIE_21_PLUGN_MENU (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ITEM_MENU_FK3 
  FOREIGN KEY (REF_DV_CONTN_ITEM_MENU) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_ITEM_MENU_FK4 
  FOREIGN KEY (REF_DV_ALIGN) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_21_PLUGN_MENU;
ALTER TABLE SIE_21_PLUGN_MENU ADD (
  CONSTRAINT SIE_21_PLUGN_MENU_FK2 
  FOREIGN KEY (REF_DV_TYPE_MENU) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_MENU_FK3 
  FOREIGN KEY (REF_DV_COULR_PRINC) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_MENU_FK4 
  FOREIGN KEY (REF_DV_COULR_THEME) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_MENU_FK5 
  FOREIGN KEY (REF_MENU) 
  REFERENCES SIE_13_MENU (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_MENU_FK6 
  FOREIGN KEY (REF_DV_FORMT_MENU) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_21_PLUGN_MENU_FK7 
  FOREIGN KEY (REF_DV_ORIEN_MENU) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_APLIC_MODL_RECHR;
ALTER TABLE SIE_23_APLIC_MODL_RECHR ADD (
  CONSTRAINT SIE_23_APLIC_MODL_RECHR_FK1 
  FOREIGN KEY (REF_MODL_RECHR) 
  REFERENCES SIE_23_MODL_RECHR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_APLIC_MODL_RECHR_FK2 
  FOREIGN KEY (REF_STRUC_APLIC_RECHR) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_APLIC_MODL_RECHR_FK3 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC_AFICH) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_APLIC_MODL_RECHR_FK4 
  FOREIGN KEY (REF_STRUC_APLIC_LIEN) 
  REFERENCES SIE_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_DETL_APLIC_MODL_RECHR;
ALTER TABLE SIE_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT SIE_23_DETL_APLIC_MODL_REC_FK1 
  FOREIGN KEY (REF_APLIC_MODL_RECHR) 
  REFERENCES SIE_23_APLIC_MODL_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_DETL_APLIC_MODL_REC_FK2 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC) 
  REFERENCES SIE_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_DETL_APLIC_MODL_REC_FK3 
  FOREIGN KEY (REF_PATRN_RECHR) 
  REFERENCES SIE_23_PATRN_RECHR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_DETL_RESLT_RECHR;
ALTER TABLE SIE_23_DETL_RESLT_RECHR ADD (
  CONSTRAINT SIE_23_DETL_RESLT_RECHR_FK1 
  FOREIGN KEY (REF_RECHR) 
  REFERENCES SIE_23_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_DETL_RESLT_RECHR_FK2 
  FOREIGN KEY (REF_ENONC_RECHR) 
  REFERENCES SIE_23_ENONC_RECHR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_DETL_RESLT_RECHR_FK3 
  FOREIGN KEY (REF_DETL_APLIC_MODL_RECHR) 
  REFERENCES SIE_23_DETL_APLIC_MODL_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_ENONC_RECHR;
ALTER TABLE SIE_23_ENONC_RECHR ADD (
  CONSTRAINT SIE_23_ENONC_RECHR_FK1 
  FOREIGN KEY (REF_RECHR) 
  REFERENCES SIE_23_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_MODL_RECHR;
ALTER TABLE SIE_23_MODL_RECHR ADD (
  CONSTRAINT SIE_23_MODL_RECHR_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_MODL_RECHR_FK50 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_PATRN_RECHR;
ALTER TABLE SIE_23_PATRN_RECHR ADD (
  CONSTRAINT SIE_23_PATRN_RECHR_FK50 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_RECHR;
ALTER TABLE SIE_23_RECHR ADD (
  CONSTRAINT SIE_23_RECHR_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_RECHR_FK2 
  FOREIGN KEY (REF_MODL_RECHR) 
  REFERENCES SIE_23_MODL_RECHR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_23_RESLT_RECHR;
ALTER TABLE SIE_23_RESLT_RECHR ADD (
  CONSTRAINT SIE_23_RESLT_RECHR_FK2 
  FOREIGN KEY (REF_APLIC_MODL_RECHR) 
  REFERENCES SIE_23_APLIC_MODL_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_23_SOMR_RECHR_FK1 
  FOREIGN KEY (REF_RECHR) 
  REFERENCES SIE_23_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_CHAMP;
ALTER TABLE SIE_25_CHAMP ADD (
  CONSTRAINT SIE_25_CHAMP_FK1 
  FOREIGN KEY (REF_VERSN_PUBLC) 
  REFERENCES SIE_25_VERSN_PUBLC (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_CHAMP_FK2 
  FOREIGN KEY (REF_FORMT) 
  REFERENCES SIE_14_FORMT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_CHAMP_FK3 
  FOREIGN KEY (REF_DV_TYPE_CHAMP) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_CHAMP_PUBLC_TRAVL;
ALTER TABLE SIE_25_CHAMP_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_CHAMP_PUBLC_TRAVL_FK1 
  FOREIGN KEY (REF_CHAMP) 
  REFERENCES SIE_25_CHAMP (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_CHAMP_PUBLC_TRAVL_FK2 
  FOREIGN KEY (REF_PUBLC_TRAVL) 
  REFERENCES SIE_25_PUBLC_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_DOMN_TYPE_PUBLC;
ALTER TABLE SIE_25_DOMN_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_DOMN_TYPE_PUBLC_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_DOMN_TYPE_PUBLC_FK2 
  FOREIGN KEY (REF_TYPE_PUBLC) 
  REFERENCES SIE_25_TYPE_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_DOMN_TYPE_PUBLC_FK3 
  FOREIGN KEY (REF_PUBLC) 
  REFERENCES SIE_25_PUBLC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_ELEMN_CONFG_PUBLC;
ALTER TABLE SIE_25_ELEMN_CONFG_PUBLC ADD (
  CONSTRAINT SIE_25_ELEMN_CONFG_PUBLC_FK1 
  FOREIGN KEY (REF_TYPE_PUBLC) 
  REFERENCES SIE_25_TYPE_PUBLC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_ENGIN;
ALTER TABLE SIE_25_ENGIN ADD (
  CONSTRAINT SIE_25_ENGIN_FK1 
  FOREIGN KEY (REF_DV_FORMT_SORT) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_ENGIN_VERSN_PUBLC;
ALTER TABLE SIE_25_ENGIN_VERSN_PUBLC ADD (
  CONSTRAINT SIE_25_ENGIN_VERSN_PUBLC_FK1 
  FOREIGN KEY (REF_VERSN_PUBLC) 
  REFERENCES SIE_25_VERSN_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_ENGIN_VERSN_PUBLC_FK2 
  FOREIGN KEY (REF_ENGIN) 
  REFERENCES SIE_25_ENGIN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_JOURN_TRAVL_EXECT;
ALTER TABLE SIE_25_JOURN_TRAVL_EXECT ADD (
  CONSTRAINT SIE_25_JOURN_TRAVL_EXECT_FK1 
  FOREIGN KEY (REF_TRAVL) 
  REFERENCES SIE_25_TRAVL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_JOURN_TRAVL_EXECT_FK2 
  FOREIGN KEY (REF_PUBLC_TRAVL) 
  REFERENCES SIE_25_PUBLC_TRAVL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_JOURN_TRAVL_EXECT_FK3 
  FOREIGN KEY (REF_DV_TYPE_ECRIT) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_OCURN_PARMT_PUBLC_TRAVL;
ALTER TABLE SIE_25_OCURN_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_OCURN_PARMT_PUB_TRA_FK1 
  FOREIGN KEY (REF_PARMT_PUBLC_TRAVL) 
  REFERENCES SIE_25_PARMT_PUBLC_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_PARMT_PUBLC_TRAVL;
ALTER TABLE SIE_25_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_PARMT_PUBLC_TRAVL_FK1 
  FOREIGN KEY (REF_PUBLC_TRAVL) 
  REFERENCES SIE_25_PUBLC_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_PARMT_PUBLC_TRAVL_FK2 
  FOREIGN KEY (REF_PARMT_TYPE_PUBLC) 
  REFERENCES SIE_25_PARMT_TYPE_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_PARMT_PUBLC_TRAVL_EXECT;
ALTER TABLE SIE_25_PARMT_PUBLC_TRAVL_EXECT ADD (
  CONSTRAINT SIE_25_PARMT_PUBLC_TRAVL_E_FK1 
  FOREIGN KEY (REF_TRAVL_PUBLC) 
  REFERENCES SIE_25_PUBLC_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_PARMT_PUBLC_TRAVL_E_FK2 
  FOREIGN KEY (REF_TRAVL) 
  REFERENCES SIE_25_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_PARMT_TYPE_PUBLC;
ALTER TABLE SIE_25_PARMT_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_PARMT_TYPE_PUBLC_FK1 
  FOREIGN KEY (REF_TYPE_PUBLC) 
  REFERENCES SIE_25_TYPE_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_PARMT_TYPE_PUBLC_FK2 
  FOREIGN KEY (REF_ENGIN) 
  REFERENCES SIE_25_ENGIN (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_PUBLC;
ALTER TABLE SIE_25_PUBLC ADD (
  CONSTRAINT SIE_25_PUBLC_FK1 
  FOREIGN KEY (REF_TYPE_PUBLC) 
  REFERENCES SIE_25_TYPE_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_PUBLC_FK2 
  FOREIGN KEY (REF_GROUP_PUBLC) 
  REFERENCES SIE_25_GROUP_PUBLC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_PUBLC_TRAVL;
ALTER TABLE SIE_25_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_PUBLC_TRAVL_FK1 
  FOREIGN KEY (REF_VERSN_PUBLC) 
  REFERENCES SIE_25_VERSN_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_PUBLC_TRAVL_FK2 
  FOREIGN KEY (REF_TRAVL) 
  REFERENCES SIE_25_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_PUBLC_TRAVL_FK7 
  FOREIGN KEY (REF_PUBLC) 
  REFERENCES SIE_25_PUBLC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_TRAVL;
ALTER TABLE SIE_25_TRAVL ADD (
  CONSTRAINT SIE_25_TRAVL_FK2 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_TRAVL_FK4 
  FOREIGN KEY (REF_TYPE_TRAVL) 
  REFERENCES SIE_25_TYPE_TRAVL (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_TYPE_TRAVL;
ALTER TABLE SIE_25_TYPE_TRAVL ADD (
  CONSTRAINT SIE_25_TYPE_TRAVL_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_VALR_CHAMP;
ALTER TABLE SIE_25_VALR_CHAMP ADD (
  CONSTRAINT SIE_25_VALR_CHAMP_FK1 
  FOREIGN KEY (REF_PUBLC_TRAVL) 
  REFERENCES SIE_25_PUBLC_TRAVL (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_VALR_CHAMP_FK2 
  FOREIGN KEY (REF_CHAMP) 
  REFERENCES SIE_25_CHAMP (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_VALR_ELEMN_CONFG;
ALTER TABLE SIE_25_VALR_ELEMN_CONFG ADD (
  CONSTRAINT SIE_25_VALR_ELEMN_CONFG_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES SIE_12_DOMN (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_25_VALR_ELEMN_CONFG_FK2 
  FOREIGN KEY (REF_ELEMN_CONFG_PUBLC) 
  REFERENCES SIE_25_ELEMN_CONFG_PUBLC (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_25_VERSN_PUBLC;
ALTER TABLE SIE_25_VERSN_PUBLC ADD (
  CONSTRAINT SIE_25_VERSN_PUBLC_FK1 
  FOREIGN KEY (REF_PUBLC) 
  REFERENCES SIE_25_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_29_CONTR;
ALTER TABLE SIE_29_CONTR ADD (
  CONSTRAINT SIE_29_CONTR_FK50 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES SIE_11_PRODT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_AFECT_ITEM;
ALTER TABLE SIE_30_AFECT_ITEM ADD (
  CONSTRAINT SIE_30_AFECT_ITEM_FK1 
  FOREIGN KEY (REF_ITEM_CARNT_PRODT) 
  REFERENCES SIE_30_ITEM_CARNT_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_AFECT_ITEM_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_CARNT_APLIC;
ALTER TABLE SIE_30_CARNT_APLIC ADD (
  CONSTRAINT SIE_30_CARNT_PRODT_FK3 
  FOREIGN KEY (REF_UTILS_RESPN) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_CARNT_PRODT;
ALTER TABLE SIE_30_CARNT_PRODT ADD (
  CONSTRAINT SIE_30_CARNT_SYSTM_FK2 
  FOREIGN KEY (REF_UTILS_RESPN) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_CARNT_SPRIN;
ALTER TABLE SIE_30_CARNT_SPRIN ADD (
  CONSTRAINT SIE_30_CARNT_SPRIN_FK1 
  FOREIGN KEY (REF_CARNT_PRODT) 
  REFERENCES SIE_30_CARNT_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_CARNT_SPRIN_FK2 
  FOREIGN KEY (REF_UTILS_RESPN) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_CAS_UTILS;
ALTER TABLE SIE_30_CAS_UTILS ADD (
  CONSTRAINT SIE_30_CAS_UTILS_FK1 
  FOREIGN KEY (REF_CARNT_PRODT) 
  REFERENCES SIE_30_CARNT_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_CAS_UTILS_FK2 
  FOREIGN KEY (REF_STAT) 
  REFERENCES SIE_12_STAT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_CAS_UTILS_FK3 
  FOREIGN KEY (REF_UTILS_RESPN) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_EFORT_ITEM;
ALTER TABLE SIE_30_EFORT_ITEM ADD (
  CONSTRAINT SIE_30_EFORT_ITEM_FK1 
  FOREIGN KEY (REF_ITEM_CARNT_SPRIN) 
  REFERENCES SIE_30_ITEM_CARNT_SPRIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_EFORT_ITEM_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES SIE_12_UTILS (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_HISTR_EFORT_RESTN;
ALTER TABLE SIE_30_HISTR_EFORT_RESTN ADD (
  CONSTRAINT SIE_30_HISTR_EFORT_RESTN_FK1 
  FOREIGN KEY (REF_ITEM_CARNT_SPRIN) 
  REFERENCES SIE_30_ITEM_CARNT_SPRIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_ITEM_CARNT_PRODT;
ALTER TABLE SIE_30_ITEM_CARNT_PRODT ADD (
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_FK1 
  FOREIGN KEY (REF_CARNT_PRODT) 
  REFERENCES SIE_30_CARNT_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_FK2 
  FOREIGN KEY (REF_CAS_UTILS) 
  REFERENCES SIE_30_CAS_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_FK3 
  FOREIGN KEY (REF_DV_TAIL_RELTV) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_FK4 
  FOREIGN KEY (REF_DV_PRIOR) 
  REFERENCES SIE_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_FK5 
  FOREIGN KEY (REF_STAT) 
  REFERENCES SIE_12_STAT (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_ITEM_CARNT_SPRIN;
ALTER TABLE SIE_30_ITEM_CARNT_SPRIN ADD (
  CONSTRAINT SIE_30_ITEM_CARNT_SPRIN_FK1 
  FOREIGN KEY (REF_CARNT_SPRIN) 
  REFERENCES SIE_30_CARNT_SPRIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_ITEM_CARNT_SPRIN_FK2 
  FOREIGN KEY (REF_ITEM_CARNT_PRODT) 
  REFERENCES SIE_30_ITEM_CARNT_PRODT (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_ITEM_CARNT_SPRIN_FK3 
  FOREIGN KEY (REF_SIE_30_PAGE) 
  REFERENCES SIE_30_PAGE (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_PAGE;
ALTER TABLE SIE_30_PAGE ADD (
  CONSTRAINT SIE_30_PAGE_FK1 
  FOREIGN KEY (REF_SIE_13_PAGE) 
  REFERENCES SIE_13_PAGE (SEQNC)
  ENABLE VALIDATE);

Prompt Foreign Key Constraints on Table SIE_30_PAGE_ITEM;
ALTER TABLE SIE_30_PAGE_ITEM ADD (
  CONSTRAINT SIE_30_PAGE_ITEM_FK1 
  FOREIGN KEY (REF_SIE_30_PAGE) 
  REFERENCES SIE_30_PAGE (SEQNC)
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_PAGE_ITEM_FK2 
  FOREIGN KEY (REF_ITEM_CARNT_PRODT) 
  REFERENCES SIE_30_ITEM_CARNT_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE);
