SET DEFINE OFF;
Prompt Non-Foreign Key Constraints on Table SIE_01_ATRIB_MODL_COMNC;
ALTER TABLE SIE_01_ATRIB_MODL_COMNC ADD (
  CONSTRAINT SIE_01_ATRIB_MODL_COMNC_UK1
  UNIQUE (CODE, REF_MODL_COMNC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_CODE_ERR_ORACL;
ALTER TABLE SIE_01_CODE_ERR_ORACL ADD (
  CONSTRAINT SIE_01_CODE_ERR_ORCL_UK1
  UNIQUE (ERR_CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_DESTN;
ALTER TABLE SIE_01_DESTN ADD (
  CONSTRAINT SIE_01_DESTN_UK1
  UNIQUE (REF_ATRIB_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_EVENM_NOTFB;
ALTER TABLE SIE_01_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_EVENM_NOTFB_UK1
  UNIQUE (CODE, REF_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_HIERC_APLIC;
ALTER TABLE SIE_01_HIERC_APLIC ADD (
  CONSTRAINT SIE_12_HIERC_APLIC_UK1
  UNIQUE (REF_EVENM_NOTFB, REF_ATRIB_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_LANG;
ALTER TABLE SIE_01_LANG ADD (
  CONSTRAINT SIE_01_LANG_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_LANG_LANG;
ALTER TABLE SIE_01_LANG_LANG ADD (
  CONSTRAINT SIE_01_LANG_LANG_UK1
  UNIQUE (REF_LANG, REF_LANG_CIBLE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG;
ALTER TABLE SIE_01_MESG ADD (
  CONSTRAINT SIE_01_MESG_UK1
  UNIQUE (NUMR_MESG, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG_ERR_LIE;
ALTER TABLE SIE_01_MESG_ERR_LIE ADD (
  CONSTRAINT SIE_01_MESG_ERR_LIE_UK1
  UNIQUE (REF_CODE_ERR_ORACL, NOM_TABLE, NOM_COLN, NOM_CONTR, PAGE, REF_PRODT, TYPE_LIAIS, REF_MESG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG_LANG;
ALTER TABLE SIE_01_MESG_LANG ADD (
  CONSTRAINT SIE_01_MESG_LANG_UK1
  UNIQUE (REF_MESG, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MESG_TRADC_APEX;
ALTER TABLE SIE_01_MESG_TRADC_APEX ADD (
  CONSTRAINT SIE_01_MESG_TRADC_APEX_UK1
  UNIQUE (REF_PRODT, REF_LANG, NOM)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MODL_AFICH_NOTFC;
ALTER TABLE SIE_01_MODL_AFICH_NOTFC ADD (
  CONSTRAINT SIE_01_MODL_AFICH_NOTFC_UK1
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_MODL_COMNC;
ALTER TABLE SIE_01_MODL_COMNC ADD (
  CONSTRAINT SIE_01_MODL_COMNC_UK1
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_NOTFC;
ALTER TABLE SIE_01_NOTFC ADD (
  CONSTRAINT SIE_01_NOTFC_UK1
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE,
  CONSTRAINT SIE_01_NOTFC_UK2
  UNIQUE (REF_DOMN, INDEN_MESG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_OCURN_SA_EVENM_NOTFB;
ALTER TABLE SIE_01_OCURN_SA_EVENM_NOTFB ADD (
  CONSTRAINT SIE_01_OSA_EVENM_NOTFB_UK1
  UNIQUE (REF_HIERC_APLIC, REF_CONFG_EVENM_NOTFB, REF_SEQNC_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_01_RESLT_DESTN;
ALTER TABLE SIE_01_RESLT_DESTN ADD (
  CONSTRAINT SIE_01_RESLT_DESTN_UK1
  UNIQUE (REF_DESTN, IDENT_ACCES)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_03_CLAS_INTER;
ALTER TABLE SIE_03_CLAS_INTER ADD (
  CONSTRAINT SIE_03_CLAS_INTER_UK1
  UNIQUE (REF_PRODT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_04_CONTX_ETEND;
ALTER TABLE SIE_04_CONTX_ETEND ADD (
  CONSTRAINT SIE_04_CONTX_ETEND_UK1
  UNIQUE (REF_CONTX, NOM, PAGE_CIBLE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_07_SEMPH;
ALTER TABLE SIE_07_SEMPH ADD (
  CONSTRAINT SIE_07_SEMPH_UK1
  UNIQUE (CODE, VARBL1, VARBL2, VARBL3)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_07_VALR_AUDIT_STRUC_APLIC;
ALTER TABLE SIE_07_VALR_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT SIE_07_VALR_AUDIT_SA_UK1
  UNIQUE (REF_AUDIT_STRUC_APLIC, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_APLIC;
ALTER TABLE SIE_11_APLIC ADD (
  CONSTRAINT SIE_11_APLIC_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE,
  CONSTRAINT SIE_11_APLIC_UK2
  UNIQUE (NUMR_APLIC_APEX)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_ATRIB_ENTIT;
ALTER TABLE SIE_11_ATRIB_ENTIT ADD (
  CONSTRAINT SIE_11_ATRIB_ENTIT_UK1
  UNIQUE (REF_ENTIT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_ENTIT;
ALTER TABLE SIE_11_ENTIT ADD (
  CONSTRAINT SIE_11_ENTIT_UK1
  UNIQUE (REF_VERSN, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PARMT_AFW;
ALTER TABLE SIE_11_PARMT_AFW ADD (
  CONSTRAINT SIE_11_PARMT_AFW_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PLUGN;
ALTER TABLE SIE_11_PLUGN ADD (
  CONSTRAINT SIE_11_PLUGN_UK1
  UNIQUE (CODE_INTER)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PRODT;
ALTER TABLE SIE_11_PRODT ADD (
  CONSTRAINT SIE_11_PRODT_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PRODT_LANG;
ALTER TABLE SIE_11_PRODT_LANG ADD (
  CONSTRAINT SIE_11_PRODT_LANG_UK1
  UNIQUE (REF_PRODT, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_PRODT_RESRC;
ALTER TABLE SIE_11_PRODT_RESRC ADD (
  CONSTRAINT SIE_11_PRODT_RESRC_UK1
  UNIQUE (REF_PRODT, REF_FORMT, REF_CONDT_EXECT, REF_RESRC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_11_VERSN;
ALTER TABLE SIE_11_VERSN ADD (
  CONSTRAINT SIE_11_VERSN_UK1
  UNIQUE (REF_PRODT, REF_PLUGN, REF_APLIC, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_ACTIO_AUDIT;
ALTER TABLE SIE_12_ACTIO_AUDIT ADD (
  CONSTRAINT SIE_12_ACTIO_AUDIT_UK1
  UNIQUE (REF_STRUC_APLIC, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_ATRIB_STRUC_APLIC;
ALTER TABLE SIE_12_ATRIB_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_ATRIB_STRUC_APLIC_UK1
  UNIQUE (NOM_COLN, REF_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DOMN;
ALTER TABLE SIE_12_DOMN ADD (
  CONSTRAINT SIE_12_DOMN_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_DOMN_FONCT;
ALTER TABLE SIE_12_DOMN_FONCT ADD (
  CONSTRAINT SIE_12_DOMN_FONCT_UK1
  UNIQUE (REF_FONCT, REF_DOMN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_EVOLT_STAT;
ALTER TABLE SIE_12_EVOLT_STAT ADD (
  CONSTRAINT SIE_12_EVOLT_STAT_UK1
  UNIQUE (REF_STAT_EVOLT, REF_STAT, INDIC_CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FAVR;
ALTER TABLE SIE_12_FAVR ADD (
  CONSTRAINT SIE_12_FAVR_UK1
  UNIQUE (REF_UTILS, REF_STRUC_APLIC, REF_SEQNC_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FONCT;
ALTER TABLE SIE_12_FONCT ADD (
  CONSTRAINT SIE_12_FONCT_UK1
  UNIQUE (REF_PRODT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_FONCT_STRUC_APLIC;
ALTER TABLE SIE_12_FONCT_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_FONCT_STRUC_APLIC_UK1
  UNIQUE (REF_FONCT, REF_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_GROUP_STAT;
ALTER TABLE SIE_12_GROUP_STAT ADD (
  CONSTRAINT SIE_12_GROUP_STAT_UK1
  UNIQUE (REF_PRODT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_GROUP_UTILS;
ALTER TABLE SIE_12_GROUP_UTILS ADD (
  CONSTRAINT SIE_12_GROUP_UTILS_UK1
  UNIQUE (CODE, REF_DOMN, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_GR_UT_OPERT_OPTIO_DOMN;
ALTER TABLE SIE_12_GR_UT_OPERT_OPTIO_DOMN ADD (
  CONSTRAINT SIE_12_GU_OPER_OPT_DOMN_UK1
  UNIQUE (REF_GROUP_UTILS, REF_OPERT, REF_OPERT_OPTIO, REF_DOMN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STAT;
ALTER TABLE SIE_12_STAT ADD (
  CONSTRAINT SIE_12_STAT_UK2
  UNIQUE (REF_STRUC_APLIC, REF_GROUP_STAT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STRUC_APLIC;
ALTER TABLE SIE_12_STRUC_APLIC ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_STRUC_APLIC_LANG;
ALTER TABLE SIE_12_STRUC_APLIC_LANG ADD (
  CONSTRAINT SIE_12_STRUC_APLIC_LANG_UK1
  UNIQUE (REF_STRUC_APLIC, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_TYPE_STRUC;
ALTER TABLE SIE_12_TYPE_STRUC ADD (
  CONSTRAINT SIE_12_TYPE_STRUC_UK1
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_12_UTILS;
ALTER TABLE SIE_12_UTILS ADD (
  CONSTRAINT SIE_12_UTILS_UK1
  UNIQUE (CODE_UTILS)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_UTILS_UK2
  UNIQUE (COURL)
  ENABLE VALIDATE,
  CONSTRAINT SIE_12_UTILS_UK3
  UNIQUE (CODE_UTILS_BASE_DON)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_CONDT_EXECT;
ALTER TABLE SIE_13_CONDT_EXECT ADD (
  CONSTRAINT SIE_13_CONDT_EXECT_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_CONDT_PILTB;
ALTER TABLE SIE_13_CONDT_PILTB ADD (
  CONSTRAINT SIE_13_CONDT_PILTB_UK1
  UNIQUE (REF_PAGE, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_DOSR_VIRTL;
ALTER TABLE SIE_13_DOSR_VIRTL ADD (
  CONSTRAINT SIE_13_DOSR_VIRTL_UK1
  UNIQUE (REF_PRODT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_EMPLA_DOSR_VIRTL;
ALTER TABLE SIE_13_EMPLA_DOSR_VIRTL ADD (
  CONSTRAINT SIE_13_EMPLA_DOSR_VIRTL_UK1
  UNIQUE (REF_DOSR_VIRTL, REF_VERSN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_FORMT_RESRC;
ALTER TABLE SIE_13_FORMT_RESRC ADD (
  CONSTRAINT SIE_13_FORMT_RESRC_UK1
  UNIQUE (REF_PRODT, REF_TYPE_FICHR, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_INSTA_PREFR;
ALTER TABLE SIE_13_INSTA_PREFR ADD (
  CONSTRAINT SIE_13_INSTA_PREFR_UK1
  UNIQUE (REF_PREFR, REF_UTILS, REF_SESN, REF_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_ITEM_MENU;
ALTER TABLE SIE_13_ITEM_MENU ADD (
  CONSTRAINT SIE_13_ITEM_MENU_UK1
  UNIQUE (CODE, REF_MENU)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_LIEN_CONDT_PILTB;
ALTER TABLE SIE_13_LIEN_CONDT_PILTB ADD (
  CONSTRAINT SIE_13_LIEN_CONDT_PILTB_UK1
  UNIQUE (REF_CONDT_PILTB, REF_PAGE_ITEM)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_LISTE_NAVGT;
ALTER TABLE SIE_13_LISTE_NAVGT ADD (
  CONSTRAINT SIE_13_LISTE_NAVGT_UK1
  UNIQUE (REF_PAGE, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_MENU;
ALTER TABLE SIE_13_MENU ADD (
  CONSTRAINT SIE_13_MENU_UK1
  UNIQUE (CODE, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_MIME_TYPE;
ALTER TABLE SIE_13_MIME_TYPE ADD (
  CONSTRAINT SIE_13_MIME_TYPE_UK1
  UNIQUE (EXT, MIME_TYPE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_OPERT;
ALTER TABLE SIE_13_OPERT ADD (
  CONSTRAINT SIE_13_OPERT_UK1
  UNIQUE (REF_PRODT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_OPERT_OPTIO;
ALTER TABLE SIE_13_OPERT_OPTIO ADD (
  CONSTRAINT SIE_13_OPERT_OPTIO_UK1
  UNIQUE (REF_OPERT, CODE)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_OPERT_OPTIO_UK2
  UNIQUE (REF_OPERT, PREPN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE;
ALTER TABLE SIE_13_PAGE ADD (
  CONSTRAINT SIE_13_PAGE_UK1
  UNIQUE (REF_APLIC, NUMR_APEX)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_IR;
ALTER TABLE SIE_13_PAGE_IR ADD (
  CONSTRAINT SIE_13_PAGE_IR_UK1
  UNIQUE (REF_PAGE)
  ENABLE VALIDATE,
  CONSTRAINT SIE_13_PAGE_IR_UK2
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_ITEM;
ALTER TABLE SIE_13_PAGE_ITEM ADD (
  CONSTRAINT SIE_13_PAGE_ITEM_UK1
  UNIQUE (REF_PAGE, NOM_APEX, ID_APEX)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_ITEM_LANG;
ALTER TABLE SIE_13_PAGE_ITEM_LANG ADD (
  CONSTRAINT SIE_13_PAGE_ITEM_LANG_UK1
  UNIQUE (REF_PAGE_ITEM, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_LANG;
ALTER TABLE SIE_13_PAGE_LANG ADD (
  CONSTRAINT SIE_13_PAGE_LANG_UK1
  UNIQUE (REF_PAGE, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_PAGE_PREFR_NAVGT;
ALTER TABLE SIE_13_PAGE_PREFR_NAVGT ADD (
  CONSTRAINT SIE_13_PAGE_PREFR_NAVGT_UK1
  UNIQUE (REF_PAGE, REF_PAGE_IR)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_REGN_PILTB;
ALTER TABLE SIE_13_REGN_PILTB ADD (
  CONSTRAINT SIE_13_REGN_PILTB_UK1
  UNIQUE (REF_PAGE, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_REGN_PILTB_LANG;
ALTER TABLE SIE_13_REGN_PILTB_LANG ADD (
  CONSTRAINT SIE_13_REGN_PILTB_LANG_UK1
  UNIQUE (REF_REGN_PILTB, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_RESRC;
ALTER TABLE SIE_13_RESRC ADD (
  CONSTRAINT SIE_13_RESRC_UK1
  UNIQUE (REF_STRUC_APLIC, REF_PRODT, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_13_TYPE_FICHR;
ALTER TABLE SIE_13_TYPE_FICHR ADD (
  CONSTRAINT SIE_13_TYPE_FICHR_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_DOMN_VALR;
ALTER TABLE SIE_14_DOMN_VALR ADD (
  CONSTRAINT SIE_14_DOMN_VALR_UK1
  UNIQUE (CODE, REF_PRODT, REF_DOMN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_FORMT;
ALTER TABLE SIE_14_FORMT ADD (
  CONSTRAINT SIE_14_FORMT_UK1
  UNIQUE (REF_PRODT, DEFNT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_14_TYPE_DOMN_VALR;
ALTER TABLE SIE_14_TYPE_DOMN_VALR ADD (
  CONSTRAINT SIE_14_TYPE_DOMN_VALR_UK1
  UNIQUE (CODE, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_COMPT_AXIAT;
ALTER TABLE SIE_17_COMPT_AXIAT ADD (
  CONSTRAINT SIE_17_COMPT_AXIAT_UK1
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE,
  CONSTRAINT SIE_17_COMPT_AXIAT_UK2
  UNIQUE (REF_DOMN, NUMR)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_17_PROFL_COURL;
ALTER TABLE SIE_17_PROFL_COURL ADD (
  CONSTRAINT SIE_17_PROFL_COURL_UK2
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_BOUTN;
ALTER TABLE SIE_19_BOUTN ADD (
  CONSTRAINT SIE_19_BOUTN_UK1
  UNIQUE (REF_DISPN_FONCT, REF_LANG, ITEM_SUBST)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_CLE;
ALTER TABLE SIE_19_CLE ADD (
  CONSTRAINT SIE_19_CLE_UK1
  UNIQUE (REF_DISPN_FONCT, REF_LANG, INDIC_INTER, CODE_KEYPR, CODE_KEYDW, INDIC_SHIFT, INDIC_ALT, INDIC_CTRL)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_DISPN_FONCT;
ALTER TABLE SIE_19_DISPN_FONCT ADD (
  CONSTRAINT SIE_19_DISPN_FONCT_UK1
  UNIQUE (REF_FONCT, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_FONCT;
ALTER TABLE SIE_19_FONCT ADD (
  CONSTRAINT SIE_19_FONCT_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_19_FONCT_LANG;
ALTER TABLE SIE_19_FONCT_LANG ADD (
  CONSTRAINT SIE_19_FONCT_LANG_UK1
  UNIQUE (REF_FONCT, REF_LANG)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_ARBRE;
ALTER TABLE SIE_21_PLUGN_ARBRE ADD (
  CONSTRAINT SIE_21_PLUGN_ARBRE_UK1
  UNIQUE (CODE, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_ARBRE_NOEUD;
ALTER TABLE SIE_21_PLUGN_ARBRE_NOEUD ADD (
  CONSTRAINT SIE_21_PLUGN_ARBRE_NOEUD_UK1
  UNIQUE (REF_PLUGN_ARBRE, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_CALND;
ALTER TABLE SIE_21_PLUGN_CALND ADD (
  CONSTRAINT SIE_21_PLUGN_CALND_UK1
  UNIQUE (CODE, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_CALND_COULR;
ALTER TABLE SIE_21_PLUGN_CALND_COULR ADD (
  CONSTRAINT SIE_21_PLUGN_CALND_COULR_UK1
  UNIQUE (ORDRE_PRESN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_ITEM_MENU;
ALTER TABLE SIE_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT SIE_21_PLUGN_ITEM_MENU_UK1
  UNIQUE (REF_ITEM_MENU, REF_PLUGN_MENU)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_21_PLUGN_MENU;
ALTER TABLE SIE_21_PLUGN_MENU ADD (
  CONSTRAINT SIE_21_PLUGN_MENU_UK1
  UNIQUE (CODE, REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_APLIC_MODL_RECHR;
ALTER TABLE SIE_23_APLIC_MODL_RECHR ADD (
  CONSTRAINT SIE_23_APLIC_MODL_RECHR_UK1
  UNIQUE (REF_MODL_RECHR, REF_STRUC_APLIC_RECHR)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_DETL_APLIC_MODL_RECHR;
ALTER TABLE SIE_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT SIE_23_DETL_APLIC_MODL_REC_UK1
  UNIQUE (REF_APLIC_MODL_RECHR, REF_ATRIB_STRUC_APLIC, REF_PATRN_RECHR, PERTN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_23_DETL_RESLT_RECHR;
ALTER TABLE SIE_23_DETL_RESLT_RECHR ADD (
  CONSTRAINT SIE_23_DETL_RESLT_RECHR_UK1
  UNIQUE (REF_RECHR, REF_ENONC_RECHR, REF_DETL_APLIC_MODL_RECHR, REF_SEQNC_STRUC_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_CHAMP;
ALTER TABLE SIE_25_CHAMP ADD (
  CONSTRAINT SIE_25_CHAMP_UK1
  UNIQUE (CODE, REF_VERSN_PUBLC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_CHAMP_PUBLC_TRAVL;
ALTER TABLE SIE_25_CHAMP_PUBLC_TRAVL ADD (
  CONSTRAINT SIE_25_CHAMP_PUBLC_TRAVL_UK1
  UNIQUE (REF_PUBLC_TRAVL, REF_CHAMP)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_DOMN_TYPE_PUBLC;
ALTER TABLE SIE_25_DOMN_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_DOMN_TYPE_PUBLC_UK1
  UNIQUE (REF_DOMN, REF_TYPE_PUBLC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_ELEMN_CONFG_PUBLC;
ALTER TABLE SIE_25_ELEMN_CONFG_PUBLC ADD (
  CONSTRAINT SIE_25_ELEMN_CONFG_PUBLC_UK1
  UNIQUE (REF_TYPE_PUBLC, CODE, DNR_REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_ENGIN;
ALTER TABLE SIE_25_ENGIN ADD (
  CONSTRAINT SIE_25_ENGIN_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_ENGIN_VERSN_PUBLC;
ALTER TABLE SIE_25_ENGIN_VERSN_PUBLC ADD (
  CONSTRAINT SIE_25_ENGIN_VERSN_PUBLC_UK1
  UNIQUE (REF_VERSN_PUBLC, REF_ENGIN, DNR_REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_GROUP_PUBLC;
ALTER TABLE SIE_25_GROUP_PUBLC ADD (
  CONSTRAINT SIE_25_GROUP_PUBLC_UK1
  UNIQUE (CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PARMT_TYPE_PUBLC;
ALTER TABLE SIE_25_PARMT_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_PARMT_TYPE_PUBLC_UK1
  UNIQUE (REF_TYPE_PUBLC, REF_ENGIN, CODE, DNR_REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_PUBLC;
ALTER TABLE SIE_25_PUBLC ADD (
  CONSTRAINT SIE_25_PUBLC_UK1
  UNIQUE (CODE, DNR_REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_TYPE_PUBLC;
ALTER TABLE SIE_25_TYPE_PUBLC ADD (
  CONSTRAINT SIE_25_TYPE_PUBLC_UK1
  UNIQUE (CODE, DNR_REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_TYPE_TRAVL;
ALTER TABLE SIE_25_TYPE_TRAVL ADD (
  CONSTRAINT SIE_25_TYPE_TRAVL_UK1
  UNIQUE (REF_DOMN, CODE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_VALR_ELEMN_CONFG;
ALTER TABLE SIE_25_VALR_ELEMN_CONFG ADD (
  CONSTRAINT SIE_25_VALR_ELEMN_CONFG_UK1
  UNIQUE (REF_ELEMN_CONFG_PUBLC, REF_DOMN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_25_VERSN_PUBLC;
ALTER TABLE SIE_25_VERSN_PUBLC ADD (
  CONSTRAINT SIE_25_VERSN_PUBLC_UK1
  UNIQUE (CODE, DNR_REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_AFECT_ITEM;
ALTER TABLE SIE_30_AFECT_ITEM ADD (
  CONSTRAINT SIE_30_AFECT_ITEM_UK1
  UNIQUE (REF_ITEM_CARNT_PRODT, REF_UTILS)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CARNT_APLIC;
ALTER TABLE SIE_30_CARNT_APLIC ADD (
  CONSTRAINT SIE_30_CARNT_PRODT_UK1
  UNIQUE (REF_APLIC)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CARNT_PRODT;
ALTER TABLE SIE_30_CARNT_PRODT ADD (
  CONSTRAINT SIE_30_CARNT_SYSTM_UK1
  UNIQUE (REF_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CARNT_SPRIN;
ALTER TABLE SIE_30_CARNT_SPRIN ADD (
  CONSTRAINT SIE_30_CARNT_SPRIN_UK1
  UNIQUE (REF_VERSN, DATE_FIN_PREVU, DATE_DEBUT_PREVU, REF_CARNT_PRODT)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_CAS_UTILS;
ALTER TABLE SIE_30_CAS_UTILS ADD (
  CONSTRAINT SIE_30_CAS_UTILS_UK1
  UNIQUE (REF_CARNT_PRODT, CODE)
  ENABLE VALIDATE,
  CONSTRAINT SIE_30_CAS_UTILS_UK2
  UNIQUE (REF_CARNT_PRODT, NOM)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_EFORT_ITEM;
ALTER TABLE SIE_30_EFORT_ITEM ADD (
  CONSTRAINT SIE_30_EFORT_ITEM_UK1
  UNIQUE (DATE_EFORT, REF_UTILS, REF_ITEM_CARNT_SPRIN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_HISTR_EFORT_RESTN;
ALTER TABLE SIE_30_HISTR_EFORT_RESTN ADD (
  CONSTRAINT SIE_30_HISTR_EFORT_RESTN_UK1
  UNIQUE (DATE_HEURE_SAISI, REF_ITEM_CARNT_SPRIN)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_ITEM_CARNT_PRODT;
ALTER TABLE SIE_30_ITEM_CARNT_PRODT ADD (
  CONSTRAINT SIE_30_ITEM_CARNT_PRODT_UK1
  UNIQUE (REF_CARNT_PRODT, NOM)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_ITEM_CARNT_SPRIN;
ALTER TABLE SIE_30_ITEM_CARNT_SPRIN ADD (
  CONSTRAINT SIE_30_ITEM_CARNT_SPRIN_UK1
  UNIQUE (REF_CARNT_SPRIN, NOM)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_PAGE;
ALTER TABLE SIE_30_PAGE ADD (
  CONSTRAINT SIE_30_PAGE_UK1
  UNIQUE (REF_SIE_13_PAGE)
  ENABLE VALIDATE);

Prompt Non-Foreign Key Constraints on Table SIE_30_PAGE_ITEM;
ALTER TABLE SIE_30_PAGE_ITEM ADD (
  CONSTRAINT SIE_30_PAGE_ITEM_UK1
  UNIQUE (REF_ITEM_CARNT_PRODT, REF_SIE_30_PAGE)
  ENABLE VALIDATE);