SET DEFINE OFF;
Prompt Index SIE_01_ATRIB_MODL_COMNC_FK1;
CREATE INDEX SIE_01_ATRIB_MODL_COMNC_FK1 ON SIE_01_ATRIB_MODL_COMNC
(REF_MODL_COMNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_ATRIB_MODL_COMNC_PK;
CREATE UNIQUE INDEX SIE_01_ATRIB_MODL_COMNC_PK ON SIE_01_ATRIB_MODL_COMNC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_ATRIB_MODL_COMNC_UK1;
CREATE UNIQUE INDEX SIE_01_ATRIB_MODL_COMNC_UK1 ON SIE_01_ATRIB_MODL_COMNC
(CODE, REF_MODL_COMNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CODE_ERR_ORCL_PK;
CREATE UNIQUE INDEX SIE_01_CODE_ERR_ORCL_PK ON SIE_01_CODE_ERR_ORACL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CODE_ERR_ORCL_UK1;
CREATE UNIQUE INDEX SIE_01_CODE_ERR_ORCL_UK1 ON SIE_01_CODE_ERR_ORACL
(ERR_CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CONFG_EVENM_NOTFB_FK1;
CREATE INDEX SIE_01_CONFG_EVENM_NOTFB_FK1 ON SIE_01_CONFG_EVENM_NOTFB
(REF_EVENM_NOTFB)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CONFG_EVENM_NOTFB_FK2;
CREATE INDEX SIE_01_CONFG_EVENM_NOTFB_FK2 ON SIE_01_CONFG_EVENM_NOTFB
(REF_TYPE_COMNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CONFG_EVENM_NOTFB_FK3;
CREATE INDEX SIE_01_CONFG_EVENM_NOTFB_FK3 ON SIE_01_CONFG_EVENM_NOTFB
(REF_PROFL_COURL)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CONFG_EVENM_NOTFB_FK4;
CREATE INDEX SIE_01_CONFG_EVENM_NOTFB_FK4 ON SIE_01_CONFG_EVENM_NOTFB
(REF_COMPT_TWILI)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CONFG_EVENM_NOTFB_FK5;
CREATE INDEX SIE_01_CONFG_EVENM_NOTFB_FK5 ON SIE_01_CONFG_EVENM_NOTFB
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_CONFG_EVENM_NOTFB_PK;
CREATE UNIQUE INDEX SIE_01_CONFG_EVENM_NOTFB_PK ON SIE_01_CONFG_EVENM_NOTFB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EN_FK1;
CREATE INDEX SIE_01_DESTN_CONFG_EN_FK1 ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(REF_DV_NATR_DESTN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EN_FK2;
CREATE INDEX SIE_01_DESTN_CONFG_EN_FK2 ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(REF_CONFG_EVENM_NOTFB)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EN_FK3;
CREATE INDEX SIE_01_DESTN_CONFG_EN_FK3 ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(REF_DESTN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EN_PK;
CREATE UNIQUE INDEX SIE_01_DESTN_CONFG_EN_PK ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EVENM_FK4;
CREATE INDEX SIE_01_DESTN_CONFG_EVENM_FK4 ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(REF_RESLT_DESTN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EVENM_FK5;
CREATE INDEX SIE_01_DESTN_CONFG_EVENM_FK5 ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(REF_ATRIB_SA_NOM_FORMT)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_CONFG_EVENM_FK6;
CREATE INDEX SIE_01_DESTN_CONFG_EVENM_FK6 ON SIE_01_DESTN_CONFG_EVENM_NOTFB
(REF_ATRIB_SA_ADRES_DESTN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_EVENM_NOTFB_PK;
CREATE UNIQUE INDEX SIE_01_DESTN_EVENM_NOTFB_PK ON SIE_01_DESTN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_DESTN_FK2;
CREATE INDEX SIE_01_DESTN_FK2 ON SIE_01_DESTN
(REF_ATRIB_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_ELEMN_CONFG_EN;
CREATE UNIQUE INDEX SIE_01_ELEMN_CONFG_EN ON SIE_01_ELEMN_CONFG_EVENM_NOTFB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_ELEMN_CONFG_EN_FK1;
CREATE INDEX SIE_01_ELEMN_CONFG_EN_FK1 ON SIE_01_ELEMN_CONFG_EVENM_NOTFB
(REF_CONFG_EVENM_NOTFB)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_EVENM_NOTFB_FK1;
CREATE INDEX SIE_01_EVENM_NOTFB_FK1 ON SIE_01_EVENM_NOTFB
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_EVENM_NOTFB_PK;
CREATE UNIQUE INDEX SIE_01_EVENM_NOTFB_PK ON SIE_01_EVENM_NOTFB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_EVENM_NOTFB_UK1;
CREATE UNIQUE INDEX SIE_01_EVENM_NOTFB_UK1 ON SIE_01_EVENM_NOTFB
(CODE, REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_LANG_LANG_FK1;
CREATE INDEX SIE_01_LANG_LANG_FK1 ON SIE_01_LANG_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_LANG_LANG_FK2;
CREATE INDEX SIE_01_LANG_LANG_FK2 ON SIE_01_LANG_LANG
(REF_LANG_CIBLE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_LANG_LANG_PK;
CREATE UNIQUE INDEX SIE_01_LANG_LANG_PK ON SIE_01_LANG_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_LANG_LANG_UK1;
CREATE UNIQUE INDEX SIE_01_LANG_LANG_UK1 ON SIE_01_LANG_LANG
(REF_LANG, REF_LANG_CIBLE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_LANG_PK;
CREATE UNIQUE INDEX SIE_01_LANG_PK ON SIE_01_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_LANG_UK1;
CREATE UNIQUE INDEX SIE_01_LANG_UK1 ON SIE_01_LANG
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_FK2;
CREATE INDEX SIE_01_MESG_ERR_LIE_FK2 ON SIE_01_MESG_ERR_LIE
(REF_MESG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_FK3;
CREATE INDEX SIE_01_MESG_ERR_LIE_FK3 ON SIE_01_MESG_ERR_LIE
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_PK;
CREATE UNIQUE INDEX SIE_01_MESG_ERR_LIE_PK ON SIE_01_MESG_ERR_LIE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_UK1;
CREATE UNIQUE INDEX SIE_01_MESG_ERR_LIE_UK1 ON SIE_01_MESG_ERR_LIE
(REF_CODE_ERR_ORACL, NOM_TABLE, NOM_COLN, NOM_CONTR, PAGE, 
REF_PRODT, TYPE_LIAIS, REF_MESG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_X1;
CREATE INDEX SIE_01_MESG_ERR_LIE_X1 ON SIE_01_MESG_ERR_LIE
(TYPE_LIAIS)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_X2;
CREATE INDEX SIE_01_MESG_ERR_LIE_X2 ON SIE_01_MESG_ERR_LIE
(NOM_TABLE, NOM_COLN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_X3;
CREATE INDEX SIE_01_MESG_ERR_LIE_X3 ON SIE_01_MESG_ERR_LIE
(NOM_CONTR)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_ERR_LIE_X4;
CREATE INDEX SIE_01_MESG_ERR_LIE_X4 ON SIE_01_MESG_ERR_LIE
(PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_FK1;
CREATE INDEX SIE_01_MESG_FK1 ON SIE_01_MESG
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_INFOR_FK1;
CREATE INDEX SIE_01_MESG_INFOR_FK1 ON SIE_01_MESG_INFOR
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_INFOR_FK2;
CREATE INDEX SIE_01_MESG_INFOR_FK2 ON SIE_01_MESG_INFOR
(SESS_ID)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_INFOR_FK3;
CREATE INDEX SIE_01_MESG_INFOR_FK3 ON SIE_01_MESG_INFOR
(REF_MESG_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_LANG_FK1;
CREATE INDEX SIE_01_MESG_LANG_FK1 ON SIE_01_MESG_LANG
(REF_MESG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_LANG_FK2;
CREATE INDEX SIE_01_MESG_LANG_FK2 ON SIE_01_MESG_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_LANG_PK;
CREATE UNIQUE INDEX SIE_01_MESG_LANG_PK ON SIE_01_MESG_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_LANG_UK1;
CREATE UNIQUE INDEX SIE_01_MESG_LANG_UK1 ON SIE_01_MESG_LANG
(REF_MESG, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_PK;
CREATE UNIQUE INDEX SIE_01_MESG_PK ON SIE_01_MESG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_TRADC_APEX_FK1;
CREATE INDEX SIE_01_MESG_TRADC_APEX_FK1 ON SIE_01_MESG_TRADC_APEX
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_TRADC_APEX_PK;
CREATE UNIQUE INDEX SIE_01_MESG_TRADC_APEX_PK ON SIE_01_MESG_TRADC_APEX
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MESG_TRADC_APEX_UK1;
CREATE UNIQUE INDEX SIE_01_MESG_TRADC_APEX_UK1 ON SIE_01_MESG_TRADC_APEX
(REF_PRODT, REF_LANG, NOM)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_FK1;
CREATE INDEX SIE_01_MODL_AFICH_NOTFC_FK1 ON SIE_01_MODL_AFICH_NOTFC
(REF_RESRC_ICON)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_FK2;
CREATE INDEX SIE_01_MODL_AFICH_NOTFC_FK2 ON SIE_01_MODL_AFICH_NOTFC
(REF_FORMT_RESRC_ICON)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_FK3;
CREATE INDEX SIE_01_MODL_AFICH_NOTFC_FK3 ON SIE_01_MODL_AFICH_NOTFC
(REF_OCURN_RESRC_ICON)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_FK5;
CREATE INDEX SIE_01_MODL_AFICH_NOTFC_FK5 ON SIE_01_MODL_AFICH_NOTFC
(REF_TYPE_COMNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_FK6;
CREATE INDEX SIE_01_MODL_AFICH_NOTFC_FK6 ON SIE_01_MODL_AFICH_NOTFC
(REF_MODL_COMNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_PK;
CREATE UNIQUE INDEX SIE_01_MODL_AFICH_NOTFC_PK ON SIE_01_MODL_AFICH_NOTFC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_AFICH_NOTFC_UK1;
CREATE UNIQUE INDEX SIE_01_MODL_AFICH_NOTFC_UK1 ON SIE_01_MODL_AFICH_NOTFC
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_COMNC_FK1;
CREATE INDEX SIE_01_MODL_COMNC_FK1 ON SIE_01_MODL_COMNC
(REF_TYPE_COMNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_COMNC_PK;
CREATE UNIQUE INDEX SIE_01_MODL_COMNC_PK ON SIE_01_MODL_COMNC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_COMNC_UK1;
CREATE UNIQUE INDEX SIE_01_MODL_COMNC_UK1 ON SIE_01_MODL_COMNC
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_MESG_NOTFC_FK1;
CREATE INDEX SIE_01_MODL_MESG_NOTFC_FK1 ON SIE_01_MODL_MESG_NOTFC
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_MODL_MESG_NOTFC_PK;
CREATE UNIQUE INDEX SIE_01_MODL_MESG_NOTFC_PK ON SIE_01_MODL_MESG_NOTFC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_NOTFC_FK1;
CREATE INDEX SIE_01_NOTFC_FK1 ON SIE_01_NOTFC
(REF_MODL_AFICH_NOTFC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_NOTFC_PK;
CREATE UNIQUE INDEX SIE_01_NOTFC_PK ON SIE_01_NOTFC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_NOTFC_UK1;
CREATE UNIQUE INDEX SIE_01_NOTFC_UK1 ON SIE_01_NOTFC
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_NOTFC_UK2;
CREATE UNIQUE INDEX SIE_01_NOTFC_UK2 ON SIE_01_NOTFC
(REF_DOMN, INDEN_MESG)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_OCURN_SA_EVENM_NOTF_FK2;
CREATE INDEX SIE_01_OCURN_SA_EVENM_NOTF_FK2 ON SIE_01_OCURN_SA_EVENM_NOTFB
(REF_CONFG_EVENM_NOTFB)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_OSA_EVENM_NOTFB_UK1;
CREATE UNIQUE INDEX SIE_01_OSA_EVENM_NOTFB_UK1 ON SIE_01_OCURN_SA_EVENM_NOTFB
(REF_HIERC_APLIC, REF_CONFG_EVENM_NOTFB, REF_SEQNC_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_RESLT_DESTN_FK3;
CREATE INDEX SIE_01_RESLT_DESTN_FK3 ON SIE_01_RESLT_DESTN
(DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_RESLT_DESTN_FK4;
CREATE INDEX SIE_01_RESLT_DESTN_FK4 ON SIE_01_RESLT_DESTN
(REF_STRUC_APLIC_ACCES)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_RESLT_DESTN_PK;
CREATE UNIQUE INDEX SIE_01_RESLT_DESTN_PK ON SIE_01_RESLT_DESTN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_RESLT_DESTN_UK1;
CREATE UNIQUE INDEX SIE_01_RESLT_DESTN_UK1 ON SIE_01_RESLT_DESTN
(REF_DESTN, IDENT_ACCES)
LOGGING
NOPARALLEL;


Prompt Index SIE_01_TYPE_COMNC_PK;
CREATE UNIQUE INDEX SIE_01_TYPE_COMNC_PK ON SIE_01_TYPE_COMNC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_CLAS_INTER;
CREATE UNIQUE INDEX SIE_03_CLAS_INTER ON SIE_03_CLAS_INTER
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_CLAS_INTER_FK2;
CREATE INDEX SIE_03_CLAS_INTER_FK2 ON SIE_03_CLAS_INTER
(REF_PROFL_COURL)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_CLAS_INTER_UK1;
CREATE UNIQUE INDEX SIE_03_CLAS_INTER_UK1 ON SIE_03_CLAS_INTER
(REF_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_JOURN_STRUC_APLIC_FK1;
CREATE INDEX SIE_03_JOURN_STRUC_APLIC_FK1 ON SIE_03_JOURN_STRUC_APLIC
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_LIEN_CLAS_INTER_UTIL_PK;
CREATE UNIQUE INDEX SIE_03_LIEN_CLAS_INTER_UTIL_PK ON SIE_03_LIEN_CLAS_INTER_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_LIEN_CLAS_INTER_UTI_FK1;
CREATE INDEX SIE_03_LIEN_CLAS_INTER_UTI_FK1 ON SIE_03_LIEN_CLAS_INTER_UTILS
(REF_GROUP_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_03_LIEN_CLAS_INTER_UTI_FK2;
CREATE INDEX SIE_03_LIEN_CLAS_INTER_UTI_FK2 ON SIE_03_LIEN_CLAS_INTER_UTILS
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_CONTX_ETEND_FK1;
CREATE INDEX SIE_04_CONTX_ETEND_FK1 ON SIE_04_CONTX_ETEND
(REF_CONTX)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_CONTX_ETEND_PK;
CREATE UNIQUE INDEX SIE_04_CONTX_ETEND_PK ON SIE_04_CONTX_ETEND
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_CONTX_ETEND_UK1;
CREATE UNIQUE INDEX SIE_04_CONTX_ETEND_UK1 ON SIE_04_CONTX_ETEND
(REF_CONTX, NOM, PAGE_CIBLE)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_CONTX_PK;
CREATE UNIQUE INDEX SIE_04_CONTX_PK ON SIE_04_CONTX
(REF_FIL_ARIAN)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_FIL_ARIAN_FK1;
CREATE INDEX SIE_04_FIL_ARIAN_FK1 ON SIE_04_FIL_ARIAN
(SESSION_ID)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_FIL_ARIAN_FK2;
CREATE INDEX SIE_04_FIL_ARIAN_FK2 ON SIE_04_FIL_ARIAN
(REF_ELEMN_SUP)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_FIL_ARIAN_FK3;
CREATE INDEX SIE_04_FIL_ARIAN_FK3 ON SIE_04_FIL_ARIAN
(REF_NAVGT_HISTR)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_FIL_ARIAN_IDX1;
CREATE INDEX SIE_04_FIL_ARIAN_IDX1 ON SIE_04_FIL_ARIAN
(SESSION_ID, TIMST)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_FIL_ARIAN_PK;
CREATE UNIQUE INDEX SIE_04_FIL_ARIAN_PK ON SIE_04_FIL_ARIAN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_NAVGT_HISTR_FK1;
CREATE INDEX SIE_04_NAVGT_HISTR_FK1 ON SIE_04_NAVGT_HISTR
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_04_NAVGT_HISTR_PK;
CREATE UNIQUE INDEX SIE_04_NAVGT_HISTR_PK ON SIE_04_NAVGT_HISTR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_AUDIT_STRUC_APLIC_FK1;
CREATE INDEX SIE_07_AUDIT_STRUC_APLIC_FK1 ON SIE_07_AUDIT_STRUC_APLIC
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_AUDIT_STRUC_APLIC_FK2;
CREATE INDEX SIE_07_AUDIT_STRUC_APLIC_FK2 ON SIE_07_AUDIT_STRUC_APLIC
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_AUDIT_STRUC_APLIC_FK3;
CREATE INDEX SIE_07_AUDIT_STRUC_APLIC_FK3 ON SIE_07_AUDIT_STRUC_APLIC
(REF_ACTIO_AUDIT)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_AUDIT_STRUC_APLIC_FK4;
CREATE INDEX SIE_07_AUDIT_STRUC_APLIC_FK4 ON SIE_07_AUDIT_STRUC_APLIC
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_AUDIT_STRUC_APLIC_FK5;
CREATE INDEX SIE_07_AUDIT_STRUC_APLIC_FK5 ON SIE_07_AUDIT_STRUC_APLIC
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_AUDIT_STRUC_APLIC_PK;
CREATE UNIQUE INDEX SIE_07_AUDIT_STRUC_APLIC_PK ON SIE_07_AUDIT_STRUC_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_ETAT_SESN_FK1;
CREATE INDEX SIE_07_ETAT_SESN_FK1 ON SIE_07_ETAT_SESN
(SESSION_ID)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_INSTA_SEMPH_FK1;
CREATE INDEX SIE_07_INSTA_SEMPH_FK1 ON SIE_07_INSTA_SEMPH
(REF_SEMPH)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_INSTA_SEMPH_FK2;
CREATE INDEX SIE_07_INSTA_SEMPH_FK2 ON SIE_07_INSTA_SEMPH
(ID_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_INSTA_SEMPH_PK;
CREATE UNIQUE INDEX SIE_07_INSTA_SEMPH_PK ON SIE_07_INSTA_SEMPH
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_SEMPH_PK;
CREATE UNIQUE INDEX SIE_07_SEMPH_PK ON SIE_07_SEMPH
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_SEMPH_UK1;
CREATE UNIQUE INDEX SIE_07_SEMPH_UK1 ON SIE_07_SEMPH
(CODE, VARBL1, VARBL2, VARBL3)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_VALR_AUDIT_SA_PK;
CREATE UNIQUE INDEX SIE_07_VALR_AUDIT_SA_PK ON SIE_07_VALR_AUDIT_STRUC_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_07_VALR_AUDIT_SA_UK1;
CREATE UNIQUE INDEX SIE_07_VALR_AUDIT_SA_UK1 ON SIE_07_VALR_AUDIT_STRUC_APLIC
(REF_AUDIT_STRUC_APLIC, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_APLIC_FK1;
CREATE INDEX SIE_11_APLIC_FK1 ON SIE_11_APLIC
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_APLIC_FK3;
CREATE INDEX SIE_11_APLIC_FK3 ON SIE_11_APLIC
(REF_APLIC_AUTHE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_APLIC_FK4;
CREATE INDEX SIE_11_APLIC_FK4 ON SIE_11_APLIC
(REF_PAGE_CONXN)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_APLIC_PK;
CREATE UNIQUE INDEX SIE_11_APLIC_PK ON SIE_11_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_APLIC_UK1;
CREATE UNIQUE INDEX SIE_11_APLIC_UK1 ON SIE_11_APLIC
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_APLIC_UK2;
CREATE UNIQUE INDEX SIE_11_APLIC_UK2 ON SIE_11_APLIC
(NUMR_APLIC_APEX)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_ATRIB_ENTIT_FK2;
CREATE INDEX SIE_11_ATRIB_ENTIT_FK2 ON SIE_11_ATRIB_ENTIT
(REF_ENTIT_REFRN)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_ATRIB_ENTIT_PK;
CREATE UNIQUE INDEX SIE_11_ATRIB_ENTIT_PK ON SIE_11_ATRIB_ENTIT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_ATRIB_ENTIT_UK1;
CREATE UNIQUE INDEX SIE_11_ATRIB_ENTIT_UK1 ON SIE_11_ATRIB_ENTIT
(REF_ENTIT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_ENTIT_FK2;
CREATE INDEX SIE_11_ENTIT_FK2 ON SIE_11_ENTIT
(REF_ATRIB_ENTIT_SUPR)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_ENTIT_PK;
CREATE UNIQUE INDEX SIE_11_ENTIT_PK ON SIE_11_ENTIT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_ENTIT_UK1;
CREATE UNIQUE INDEX SIE_11_ENTIT_UK1 ON SIE_11_ENTIT
(REF_VERSN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PARMT_AFW_PK1;
CREATE UNIQUE INDEX SIE_11_PARMT_AFW_PK1 ON SIE_11_PARMT_AFW
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PARMT_AFW_UK1;
CREATE UNIQUE INDEX SIE_11_PARMT_AFW_UK1 ON SIE_11_PARMT_AFW
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PLUGN_FK1;
CREATE INDEX SIE_11_PLUGN_FK1 ON SIE_11_PLUGN
(REF_VERSN)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PLUGN_PK;
CREATE UNIQUE INDEX SIE_11_PLUGN_PK ON SIE_11_PLUGN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PLUGN_UK1;
CREATE UNIQUE INDEX SIE_11_PLUGN_UK1 ON SIE_11_PLUGN
(CODE_INTER)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK1;
CREATE INDEX SIE_11_PRODT_FK1 ON SIE_11_PRODT
(REF_GROUP_UTILS_ADMIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK10;
CREATE INDEX SIE_11_PRODT_FK10 ON SIE_11_PRODT
(REF_MESG_RANGE_MODF)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK11;
CREATE INDEX SIE_11_PRODT_FK11 ON SIE_11_PRODT
(REF_MESG_RANGE_INSER)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK12;
CREATE INDEX SIE_11_PRODT_FK12 ON SIE_11_PRODT
(REF_MESG_AUCUN_DON_TROUV)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK13;
CREATE INDEX SIE_11_PRODT_FK13 ON SIE_11_PRODT
(REF_MESG_TROP_DON_TROUV)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK14;
CREATE INDEX SIE_11_PRODT_FK14 ON SIE_11_PRODT
(REF_MESG_AUDIT_CREAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK15;
CREATE INDEX SIE_11_PRODT_FK15 ON SIE_11_PRODT
(REF_MESG_AUDIT_MODFC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK16;
CREATE INDEX SIE_11_PRODT_FK16 ON SIE_11_PRODT
(REF_MESG_AUDIT_SUPRS)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK3;
CREATE INDEX SIE_11_PRODT_FK3 ON SIE_11_PRODT
(REF_VERSN)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK6;
CREATE INDEX SIE_11_PRODT_FK6 ON SIE_11_PRODT
(REF_MESG_SUCS)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK7;
CREATE INDEX SIE_11_PRODT_FK7 ON SIE_11_PRODT
(REF_MESG_ECHEC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK8;
CREATE INDEX SIE_11_PRODT_FK8 ON SIE_11_PRODT
(REF_MESG_FETCH)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_FK9;
CREATE INDEX SIE_11_PRODT_FK9 ON SIE_11_PRODT
(REF_MESG_RANGE_SUPRM)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_LANG_FK2;
CREATE INDEX SIE_11_PRODT_LANG_FK2 ON SIE_11_PRODT_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_LANG_PK;
CREATE UNIQUE INDEX SIE_11_PRODT_LANG_PK ON SIE_11_PRODT_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_LANG_UK1;
CREATE UNIQUE INDEX SIE_11_PRODT_LANG_UK1 ON SIE_11_PRODT_LANG
(REF_PRODT, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_PK;
CREATE UNIQUE INDEX SIE_11_PRODT_PK ON SIE_11_PRODT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_RESRC_FK2;
CREATE INDEX SIE_11_PRODT_RESRC_FK2 ON SIE_11_PRODT_RESRC
(REF_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_RESRC_FK3;
CREATE INDEX SIE_11_PRODT_RESRC_FK3 ON SIE_11_PRODT_RESRC
(REF_FORMT)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_RESRC_PK;
CREATE UNIQUE INDEX SIE_11_PRODT_RESRC_PK ON SIE_11_PRODT_RESRC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_RESRC_UK1;
CREATE UNIQUE INDEX SIE_11_PRODT_RESRC_UK1 ON SIE_11_PRODT_RESRC
(REF_PRODT, REF_FORMT, REF_CONDT_EXECT, REF_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_PRODT_UK1;
CREATE UNIQUE INDEX SIE_11_PRODT_UK1 ON SIE_11_PRODT
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_UTILS_FK1;
CREATE INDEX SIE_11_UTILS_FK1 ON SIE_11_UTILS
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_UTILS_FK2;
CREATE INDEX SIE_11_UTILS_FK2 ON SIE_11_UTILS
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_UTILS_PK;
CREATE UNIQUE INDEX SIE_11_UTILS_PK ON SIE_11_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_VERSN_FK2;
CREATE INDEX SIE_11_VERSN_FK2 ON SIE_11_VERSN
(REF_PLUGN)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_VERSN_FK90;
CREATE INDEX SIE_11_VERSN_FK90 ON SIE_11_VERSN
(REF_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_VERSN_PK;
CREATE UNIQUE INDEX SIE_11_VERSN_PK ON SIE_11_VERSN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_11_VERSN_UK1;
CREATE UNIQUE INDEX SIE_11_VERSN_UK1 ON SIE_11_VERSN
(REF_PRODT, REF_PLUGN, REF_APLIC, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ACTIO_AUDIT_FK2;
CREATE INDEX SIE_12_ACTIO_AUDIT_FK2 ON SIE_12_ACTIO_AUDIT
(REF_MESG)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ACTIO_AUDIT_PK;
CREATE UNIQUE INDEX SIE_12_ACTIO_AUDIT_PK ON SIE_12_ACTIO_AUDIT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ACTIO_AUDIT_UK1;
CREATE UNIQUE INDEX SIE_12_ACTIO_AUDIT_UK1 ON SIE_12_ACTIO_AUDIT
(REF_STRUC_APLIC, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ARBRE_FK2;
CREATE INDEX SIE_12_ARBRE_FK2 ON SIE_12_ARBRE
(REF_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ARBRE_NOEUD_FK1;
CREATE INDEX SIE_12_ARBRE_NOEUD_FK1 ON SIE_12_ARBRE_NOEUD
(REF_ARBRE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ARBRE_NOEUD_PK;
CREATE UNIQUE INDEX SIE_12_ARBRE_NOEUD_PK ON SIE_12_ARBRE_NOEUD
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ARBRE_PK;
CREATE UNIQUE INDEX SIE_12_ARBRE_PK ON SIE_12_ARBRE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ATRIB_STRUC_APLIC_FK1;
CREATE INDEX SIE_12_ATRIB_STRUC_APLIC_FK1 ON SIE_12_ATRIB_STRUC_APLIC
(REF_DV_NATR_INFOR)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ATRIB_STRUC_APLIC_FK2;
CREATE INDEX SIE_12_ATRIB_STRUC_APLIC_FK2 ON SIE_12_ATRIB_STRUC_APLIC
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ATRIB_STRUC_APLIC_FK3;
CREATE INDEX SIE_12_ATRIB_STRUC_APLIC_FK3 ON SIE_12_ATRIB_STRUC_APLIC
(REF_ATRIB_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ATRIB_STRUC_APLIC_PK;
CREATE UNIQUE INDEX SIE_12_ATRIB_STRUC_APLIC_PK ON SIE_12_ATRIB_STRUC_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_ATRIB_STRUC_APLIC_UK1;
CREATE UNIQUE INDEX SIE_12_ATRIB_STRUC_APLIC_UK1 ON SIE_12_ATRIB_STRUC_APLIC
(NOM_COLN, REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_COMPT_PAYPL_PK;
CREATE UNIQUE INDEX SIE_12_COMPT_PAYPL_PK ON SIE_12_COMPT_PAYPL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_COMPT_PAYPL_UK1;
CREATE UNIQUE INDEX SIE_12_COMPT_PAYPL_UK1 ON SIE_12_COMPT_PAYPL
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DEFNT_ACCES_FK2;
CREATE INDEX SIE_12_DEFNT_ACCES_FK2 ON SIE_12_DEFNT_ACCES
(REF_GROUP_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DEFNT_ACCES_FK4;
CREATE INDEX SIE_12_DEFNT_ACCES_FK4 ON SIE_12_DEFNT_ACCES
(REF_OPERT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DEFNT_ACCES_FK6;
CREATE INDEX SIE_12_DEFNT_ACCES_FK6 ON SIE_12_DEFNT_ACCES
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DEFNT_ACCES_FK7;
CREATE INDEX SIE_12_DEFNT_ACCES_FK7 ON SIE_12_DEFNT_ACCES
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DEFNT_ACCES_PK;
CREATE UNIQUE INDEX SIE_12_DEFNT_ACCES_PK ON SIE_12_DEFNT_ACCES
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DETL_FORML_PK;
CREATE UNIQUE INDEX SIE_12_DETL_FORML_PK ON SIE_12_DETL_FORML
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DETL_FORML_UK1;
CREATE UNIQUE INDEX SIE_12_DETL_FORML_UK1 ON SIE_12_DETL_FORML
(REF_FORML, ORDRE_PRESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FK1;
CREATE INDEX SIE_12_DOMN_FK1 ON SIE_12_DOMN
(REF_MODL_RECHR_DEFT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FK2;
CREATE INDEX SIE_12_DOMN_FK2 ON SIE_12_DOMN
(TYPE_TRAVL_DEFT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FK4;
CREATE INDEX SIE_12_DOMN_FK4 ON SIE_12_DOMN
(REF_PROFL_COURL_NOTFC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FK5;
CREATE INDEX SIE_12_DOMN_FK5 ON SIE_12_DOMN
(REF_PROFL_SMS_NOTFC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FK6;
CREATE INDEX SIE_12_DOMN_FK6 ON SIE_12_DOMN
(REF_COMPT_AXIAT_DEFT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FONCT_PK;
CREATE UNIQUE INDEX SIE_12_DOMN_FONCT_PK ON SIE_12_DOMN_FONCT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_FONCT_UK1;
CREATE UNIQUE INDEX SIE_12_DOMN_FONCT_UK1 ON SIE_12_DOMN_FONCT
(REF_FONCT, REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_PK;
CREATE UNIQUE INDEX SIE_12_DOMN_PK ON SIE_12_DOMN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_UK1;
CREATE UNIQUE INDEX SIE_12_DOMN_UK1 ON SIE_12_DOMN
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_UTILS_FK1;
CREATE INDEX SIE_12_DOMN_UTILS_FK1 ON SIE_12_DOMN_UTILS
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_UTILS_FK2;
CREATE INDEX SIE_12_DOMN_UTILS_FK2 ON SIE_12_DOMN_UTILS
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_DOMN_UTILS_PK;
CREATE UNIQUE INDEX SIE_12_DOMN_UTILS_PK ON SIE_12_DOMN_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_EVOLT_STAT_PK;
CREATE UNIQUE INDEX SIE_12_EVOLT_STAT_PK ON SIE_12_EVOLT_STAT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_EVOLT_STAT_UK1;
CREATE UNIQUE INDEX SIE_12_EVOLT_STAT_UK1 ON SIE_12_EVOLT_STAT
(REF_STAT_EVOLT, REF_STAT, INDIC_CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FAVR_FK1;
CREATE INDEX SIE_12_FAVR_FK1 ON SIE_12_FAVR
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FAVR_FK2;
CREATE INDEX SIE_12_FAVR_FK2 ON SIE_12_FAVR
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FAVR_PK;
CREATE UNIQUE INDEX SIE_12_FAVR_PK ON SIE_12_FAVR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FAVR_UK1;
CREATE UNIQUE INDEX SIE_12_FAVR_UK1 ON SIE_12_FAVR
(REF_UTILS, REF_STRUC_APLIC, REF_SEQNC_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FONCT_PK;
CREATE UNIQUE INDEX SIE_12_FONCT_PK ON SIE_12_FONCT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FONCT_STRUC_APLIC_PK;
CREATE UNIQUE INDEX SIE_12_FONCT_STRUC_APLIC_PK ON SIE_12_FONCT_STRUC_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FONCT_STRUC_APLIC_UK1;
CREATE UNIQUE INDEX SIE_12_FONCT_STRUC_APLIC_UK1 ON SIE_12_FONCT_STRUC_APLIC
(REF_FONCT, REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FONCT_UK1;
CREATE UNIQUE INDEX SIE_12_FONCT_UK1 ON SIE_12_FONCT
(REF_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FORML_IDX1;
CREATE INDEX SIE_12_FORML_IDX1 ON SIE_12_FORML
(CODE, REF_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_FORML_PK;
CREATE UNIQUE INDEX SIE_12_FORML_PK ON SIE_12_FORML
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GROUP_STAT_PK;
CREATE UNIQUE INDEX SIE_12_GROUP_STAT_PK ON SIE_12_GROUP_STAT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GROUP_STAT_UK1;
CREATE UNIQUE INDEX SIE_12_GROUP_STAT_UK1 ON SIE_12_GROUP_STAT
(REF_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GROUP_UTILS_FK2;
CREATE INDEX SIE_12_GROUP_UTILS_FK2 ON SIE_12_GROUP_UTILS
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GROUP_UTILS_FK3;
CREATE INDEX SIE_12_GROUP_UTILS_FK3 ON SIE_12_GROUP_UTILS
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GROUP_UTILS_PK;
CREATE UNIQUE INDEX SIE_12_GROUP_UTILS_PK ON SIE_12_GROUP_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GROUP_UTILS_UK1;
CREATE UNIQUE INDEX SIE_12_GROUP_UTILS_UK1 ON SIE_12_GROUP_UTILS
(CODE, REF_DOMN, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GU_OPER_OPT_DOMN_PK;
CREATE UNIQUE INDEX SIE_12_GU_OPER_OPT_DOMN_PK ON SIE_12_GR_UT_OPERT_OPTIO_DOMN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_GU_OPER_OPT_DOMN_UK1;
CREATE UNIQUE INDEX SIE_12_GU_OPER_OPT_DOMN_UK1 ON SIE_12_GR_UT_OPERT_OPTIO_DOMN
(REF_GROUP_UTILS, REF_OPERT, REF_OPERT_OPTIO, REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HIERC_APLIC_FK2;
CREATE INDEX SIE_12_HIERC_APLIC_FK2 ON SIE_01_HIERC_APLIC
(REF_ATRIB_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HIERC_APLIC_PK;
CREATE UNIQUE INDEX SIE_12_HIERC_APLIC_PK ON SIE_01_HIERC_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HIERC_APLIC_UK1;
CREATE UNIQUE INDEX SIE_12_HIERC_APLIC_UK1 ON SIE_01_HIERC_APLIC
(REF_EVENM_NOTFB, REF_ATRIB_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HISTR_ACCES_FK1;
CREATE INDEX SIE_12_HISTR_ACCES_FK1 ON SIE_12_HISTR_ACCES
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HISTR_ACCES_FK2;
CREATE INDEX SIE_12_HISTR_ACCES_FK2 ON SIE_12_HISTR_ACCES
(REF_DV_TYPE_EVENM)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HISTR_ACCES_FK3;
CREATE INDEX SIE_12_HISTR_ACCES_FK3 ON SIE_12_HISTR_ACCES
(REF_UTILS_POUR)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_HISTR_ACCES_PK;
CREATE UNIQUE INDEX SIE_12_HISTR_ACCES_PK ON SIE_12_HISTR_ACCES
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_GROUP_UTILS_FK1;
CREATE INDEX SIE_12_LIEN_GROUP_UTILS_FK1 ON SIE_12_LIEN_GROUP_UTILS
(REF_GROUP)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_GROUP_UTILS_FK2;
CREATE INDEX SIE_12_LIEN_GROUP_UTILS_FK2 ON SIE_12_LIEN_GROUP_UTILS
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_GROUP_UTILS_FK3;
CREATE INDEX SIE_12_LIEN_GROUP_UTILS_FK3 ON SIE_12_LIEN_GROUP_UTILS
(REF_GROUP_UTILS_LIE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_GROUP_UTILS_PK;
CREATE UNIQUE INDEX SIE_12_LIEN_GROUP_UTILS_PK ON SIE_12_LIEN_GROUP_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_STRUC_FK1;
CREATE INDEX SIE_12_LIEN_STRUC_FK1 ON SIE_12_LIEN_STRUC
(REF_STRUC_ADMIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_STRUC_FK3;
CREATE INDEX SIE_12_LIEN_STRUC_FK3 ON SIE_12_LIEN_STRUC
(REF_STRUC_LIE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_LIEN_STRUC_PK;
CREATE UNIQUE INDEX SIE_12_LIEN_STRUC_PK ON SIE_12_LIEN_STRUC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_MEMBR_STRUC_FK1;
CREATE INDEX SIE_12_MEMBR_STRUC_FK1 ON SIE_12_MEMBR_STRUC
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_MEMBR_STRUC_FK2;
CREATE INDEX SIE_12_MEMBR_STRUC_FK2 ON SIE_12_MEMBR_STRUC
(REF_STRUC_ADMIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_MEMBR_STRUC_PK;
CREATE UNIQUE INDEX SIE_12_MEMBR_STRUC_PK ON SIE_12_MEMBR_STRUC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_PAYPL_RETR_APLIC_PK;
CREATE UNIQUE INDEX SIE_12_PAYPL_RETR_APLIC_PK ON SIE_12_PAYPL_RETR_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_PAYPL_RETR_APLIC_UK1;
CREATE UNIQUE INDEX SIE_12_PAYPL_RETR_APLIC_UK1 ON SIE_12_PAYPL_RETR_APLIC
(REF_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_PAYPL_RETR_APLIC_UK2;
CREATE UNIQUE INDEX SIE_12_PAYPL_RETR_APLIC_UK2 ON SIE_12_PAYPL_RETR_APLIC
(REF_STRUC_APLIC, REF_SEQNC_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_REQT_INTER_UTILS_FK1;
CREATE INDEX SIE_12_REQT_INTER_UTILS_FK1 ON SIE_12_REQT_INTER_UTILS
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_REQT_INTER_UTILS_FK2;
CREATE INDEX SIE_12_REQT_INTER_UTILS_FK2 ON SIE_12_REQT_INTER_UTILS
(REF_DV_TYPE_REQT_INTER)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_REQT_INTER_UTILS_FK3;
CREATE INDEX SIE_12_REQT_INTER_UTILS_FK3 ON SIE_12_REQT_INTER_UTILS
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_REQT_INTER_UTILS_FK4;
CREATE INDEX SIE_12_REQT_INTER_UTILS_FK4 ON SIE_12_REQT_INTER_UTILS
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_REQT_INTER_UTILS_PK;
CREATE UNIQUE INDEX SIE_12_REQT_INTER_UTILS_PK ON SIE_12_REQT_INTER_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_SESN_FK2;
CREATE INDEX SIE_12_SESN_FK2 ON SIE_12_SESN
(REF_ID_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_SESN_FK3;
CREATE INDEX SIE_12_SESN_FK3 ON SIE_12_SESN
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_SESN_PK;
CREATE UNIQUE INDEX SIE_12_SESN_PK ON SIE_12_SESN
(ID_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STAT_FK1;
CREATE INDEX SIE_12_STAT_FK1 ON SIE_12_STAT
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STAT_FK2;
CREATE INDEX SIE_12_STAT_FK2 ON SIE_12_STAT
(REF_GROUP_STAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STAT_PK;
CREATE UNIQUE INDEX SIE_12_STAT_PK ON SIE_12_STAT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STAT_UK2;
CREATE UNIQUE INDEX SIE_12_STAT_UK2 ON SIE_12_STAT
(REF_STRUC_APLIC, REF_GROUP_STAT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_ADMIN_FK1;
CREATE INDEX SIE_12_STRUC_ADMIN_FK1 ON SIE_12_STRUC_ADMIN
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_ADMIN_FK2;
CREATE INDEX SIE_12_STRUC_ADMIN_FK2 ON SIE_12_STRUC_ADMIN
(REF_TYPE_STRUC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_ADMIN_FK3;
CREATE INDEX SIE_12_STRUC_ADMIN_FK3 ON SIE_12_STRUC_ADMIN
(REF_RESPN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_ADMIN_PK;
CREATE UNIQUE INDEX SIE_12_STRUC_ADMIN_PK ON SIE_12_STRUC_ADMIN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_DESTN_FK1;
CREATE INDEX SIE_12_STRUC_APLIC_DESTN_FK1 ON SIE_12_STRUC_APLIC_DESTN
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_DESTN_FK2;
CREATE INDEX SIE_12_STRUC_APLIC_DESTN_FK2 ON SIE_12_STRUC_APLIC_DESTN
(REF_DESTN)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_DESTN_PK;
CREATE UNIQUE INDEX SIE_12_STRUC_APLIC_DESTN_PK ON SIE_12_STRUC_APLIC_DESTN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_FK1;
CREATE INDEX SIE_12_STRUC_APLIC_FK1 ON SIE_12_STRUC_APLIC
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_FK2;
CREATE INDEX SIE_12_STRUC_APLIC_FK2 ON SIE_12_STRUC_APLIC
(REF_MESG_ERR_SUPRS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_FK3;
CREATE INDEX SIE_12_STRUC_APLIC_FK3 ON SIE_12_STRUC_APLIC
(REF_PAGE_LISTE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_FK4;
CREATE INDEX SIE_12_STRUC_APLIC_FK4 ON SIE_12_STRUC_APLIC
(REF_PAGE_FORML)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_FK6;
CREATE INDEX SIE_12_STRUC_APLIC_FK6 ON SIE_12_STRUC_APLIC
(DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_LANG_FK2;
CREATE INDEX SIE_12_STRUC_APLIC_LANG_FK2 ON SIE_12_STRUC_APLIC_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_LANG_PK;
CREATE UNIQUE INDEX SIE_12_STRUC_APLIC_LANG_PK ON SIE_12_STRUC_APLIC_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_LANG_UK1;
CREATE UNIQUE INDEX SIE_12_STRUC_APLIC_LANG_UK1 ON SIE_12_STRUC_APLIC_LANG
(REF_STRUC_APLIC, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_PK;
CREATE UNIQUE INDEX SIE_12_STRUC_APLIC_PK ON SIE_12_STRUC_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_STRUC_APLIC_UK1;
CREATE UNIQUE INDEX SIE_12_STRUC_APLIC_UK1 ON SIE_12_STRUC_APLIC
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_TYPE_STRUC_PK;
CREATE UNIQUE INDEX SIE_12_TYPE_STRUC_PK ON SIE_12_TYPE_STRUC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_TYPE_STRUC_UK1;
CREATE UNIQUE INDEX SIE_12_TYPE_STRUC_UK1 ON SIE_12_TYPE_STRUC
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_UTILS_PK;
CREATE UNIQUE INDEX SIE_12_UTILS_PK ON SIE_12_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_UTILS_UK1;
CREATE UNIQUE INDEX SIE_12_UTILS_UK1 ON SIE_12_UTILS
(CODE_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_UTILS_UK2;
CREATE UNIQUE INDEX SIE_12_UTILS_UK2 ON SIE_12_UTILS
(COURL)
LOGGING
NOPARALLEL;


Prompt Index SIE_12_UTILS_UK3;
CREATE UNIQUE INDEX SIE_12_UTILS_UK3 ON SIE_12_UTILS
(CODE_UTILS_BASE_DON)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_CONDT_EXECT_PK;
CREATE UNIQUE INDEX SIE_13_CONDT_EXECT_PK ON SIE_13_CONDT_EXECT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_CONDT_EXECT_UK1;
CREATE UNIQUE INDEX SIE_13_CONDT_EXECT_UK1 ON SIE_13_CONDT_EXECT
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_CONDT_PILTB_FK1;
CREATE INDEX SIE_13_CONDT_PILTB_FK1 ON SIE_13_CONDT_PILTB
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_CONDT_PILTB_FK2;
CREATE INDEX SIE_13_CONDT_PILTB_FK2 ON SIE_13_CONDT_PILTB
(REF_PAGE_ITEM_FOCUS)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_CONDT_PILTB_PK;
CREATE UNIQUE INDEX SIE_13_CONDT_PILTB_PK ON SIE_13_CONDT_PILTB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_CONDT_PILTB_UK1;
CREATE UNIQUE INDEX SIE_13_CONDT_PILTB_UK1 ON SIE_13_CONDT_PILTB
(REF_PAGE, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_DOSR_VIRTL_PK;
CREATE UNIQUE INDEX SIE_13_DOSR_VIRTL_PK ON SIE_13_DOSR_VIRTL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_DOSR_VIRTL_UK1;
CREATE UNIQUE INDEX SIE_13_DOSR_VIRTL_UK1 ON SIE_13_DOSR_VIRTL
(REF_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EMPLA_DOSR_VIRTL_FK2;
CREATE INDEX SIE_13_EMPLA_DOSR_VIRTL_FK2 ON SIE_13_EMPLA_DOSR_VIRTL
(REF_VERSN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EMPLA_DOSR_VIRTL_PK;
CREATE UNIQUE INDEX SIE_13_EMPLA_DOSR_VIRTL_PK ON SIE_13_EMPLA_DOSR_VIRTL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EMPLA_DOSR_VIRTL_UK1;
CREATE UNIQUE INDEX SIE_13_EMPLA_DOSR_VIRTL_UK1 ON SIE_13_EMPLA_DOSR_VIRTL
(REF_DOSR_VIRTL, REF_VERSN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EXPOR_APLIC_FK1;
CREATE INDEX SIE_13_EXPOR_APLIC_FK1 ON SIE_13_EXPOR_APLIC
(REF_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EXPOR_APLIC_FK2;
CREATE INDEX SIE_13_EXPOR_APLIC_FK2 ON SIE_13_EXPOR_APLIC
(REF_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EXPOR_APLIC_PK;
CREATE UNIQUE INDEX SIE_13_EXPOR_APLIC_PK ON SIE_13_EXPOR_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EXPOR_PAGE_FK1;
CREATE INDEX SIE_13_EXPOR_PAGE_FK1 ON SIE_13_EXPOR_PAGE
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_EXPOR_PAGE_FK2;
CREATE INDEX SIE_13_EXPOR_PAGE_FK2 ON SIE_13_EXPOR_PAGE
(REF_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_FORMT_RESRC_FK2;
CREATE INDEX SIE_13_FORMT_RESRC_FK2 ON SIE_13_FORMT_RESRC
(REF_TYPE_FICHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_FORMT_RESRC_PK;
CREATE UNIQUE INDEX SIE_13_FORMT_RESRC_PK ON SIE_13_FORMT_RESRC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_FORMT_RESRC_UK1;
CREATE UNIQUE INDEX SIE_13_FORMT_RESRC_UK1 ON SIE_13_FORMT_RESRC
(REF_PRODT, REF_TYPE_FICHR, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_INSTA_PREFR_FK1;
CREATE INDEX SIE_13_INSTA_PREFR_FK1 ON SIE_13_INSTA_PREFR
(REF_PREFR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_INSTA_PREFR_FK2;
CREATE INDEX SIE_13_INSTA_PREFR_FK2 ON SIE_13_INSTA_PREFR
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_INSTA_PREFR_FK3;
CREATE INDEX SIE_13_INSTA_PREFR_FK3 ON SIE_13_INSTA_PREFR
(REF_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_INSTA_PREFR_FK4;
CREATE INDEX SIE_13_INSTA_PREFR_FK4 ON SIE_13_INSTA_PREFR
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_INSTA_PREFR_PK;
CREATE UNIQUE INDEX SIE_13_INSTA_PREFR_PK ON SIE_13_INSTA_PREFR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_INSTA_PREFR_UK1;
CREATE UNIQUE INDEX SIE_13_INSTA_PREFR_UK1 ON SIE_13_INSTA_PREFR
(REF_PREFR, REF_UTILS, REF_SESN, REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK01;
CREATE INDEX SIE_13_ITEM_MENU_FK01 ON SIE_13_ITEM_MENU
(REF_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK03;
CREATE INDEX SIE_13_ITEM_MENU_FK03 ON SIE_13_ITEM_MENU
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK04;
CREATE INDEX SIE_13_ITEM_MENU_FK04 ON SIE_13_ITEM_MENU
(REF_DV_VALR_REQST)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK05;
CREATE INDEX SIE_13_ITEM_MENU_FK05 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SCPC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK06;
CREATE INDEX SIE_13_ITEM_MENU_FK06 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SSPC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK07;
CREATE INDEX SIE_13_ITEM_MENU_FK07 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SAPC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK08;
CREATE INDEX SIE_13_ITEM_MENU_FK08 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SCPI)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK09;
CREATE INDEX SIE_13_ITEM_MENU_FK09 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SSPI)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK10;
CREATE INDEX SIE_13_ITEM_MENU_FK10 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SAPI)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK11;
CREATE INDEX SIE_13_ITEM_MENU_FK11 ON SIE_13_ITEM_MENU
(REF_DV_VALR_SNPI)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK12;
CREATE INDEX SIE_13_ITEM_MENU_FK12 ON SIE_13_ITEM_MENU
(REF_ITEM_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK17;
CREATE INDEX SIE_13_ITEM_MENU_FK17 ON SIE_13_ITEM_MENU
(REF_DV_VALR_URL)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK18;
CREATE INDEX SIE_13_ITEM_MENU_FK18 ON SIE_13_ITEM_MENU
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK3;
CREATE INDEX SIE_13_ITEM_MENU_FK3 ON SIE_13_ITEM_MENU
(REF_DV_VALR_INSTA_LIBL)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK4;
CREATE INDEX SIE_13_ITEM_MENU_FK4 ON SIE_13_ITEM_MENU
(REF_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK6;
CREATE INDEX SIE_13_ITEM_MENU_FK6 ON SIE_13_ITEM_MENU
(REF_FORMT_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK7;
CREATE INDEX SIE_13_ITEM_MENU_FK7 ON SIE_13_ITEM_MENU
(REF_OCURN_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_FK90;
CREATE INDEX SIE_13_ITEM_MENU_FK90 ON SIE_13_ITEM_MENU
(REF_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_PK;
CREATE UNIQUE INDEX SIE_13_ITEM_MENU_PK ON SIE_13_ITEM_MENU
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_ITEM_MENU_UK1;
CREATE UNIQUE INDEX SIE_13_ITEM_MENU_UK1 ON SIE_13_ITEM_MENU
(CODE, REF_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LIEN_CONDT_PILTB_FK1;
CREATE INDEX SIE_13_LIEN_CONDT_PILTB_FK1 ON SIE_13_LIEN_CONDT_PILTB
(REF_PAGE_ITEM)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LIEN_CONDT_PILTB_FK2;
CREATE INDEX SIE_13_LIEN_CONDT_PILTB_FK2 ON SIE_13_LIEN_CONDT_PILTB
(REF_CONDT_PILTB)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LIEN_CONDT_PILTB_PK;
CREATE UNIQUE INDEX SIE_13_LIEN_CONDT_PILTB_PK ON SIE_13_LIEN_CONDT_PILTB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LIEN_CONDT_PILTB_UK1;
CREATE UNIQUE INDEX SIE_13_LIEN_CONDT_PILTB_UK1 ON SIE_13_LIEN_CONDT_PILTB
(REF_CONDT_PILTB, REF_PAGE_ITEM)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LISTE_NAVGT_FK1;
CREATE INDEX SIE_13_LISTE_NAVGT_FK1 ON SIE_13_LISTE_NAVGT
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LISTE_NAVGT_PK;
CREATE UNIQUE INDEX SIE_13_LISTE_NAVGT_PK ON SIE_13_LISTE_NAVGT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_LISTE_NAVGT_UK1;
CREATE UNIQUE INDEX SIE_13_LISTE_NAVGT_UK1 ON SIE_13_LISTE_NAVGT
(REF_PAGE, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_MENU_FK02;
CREATE INDEX SIE_13_MENU_FK02 ON SIE_13_MENU
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_MENU_PK;
CREATE UNIQUE INDEX SIE_13_MENU_PK ON SIE_13_MENU
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_MENU_UK1;
CREATE UNIQUE INDEX SIE_13_MENU_UK1 ON SIE_13_MENU
(CODE, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_MIME_TYPE_FK1;
CREATE INDEX SIE_13_MIME_TYPE_FK1 ON SIE_13_MIME_TYPE
(REF_TYPE_FICHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_MIME_TYPE_PK;
CREATE UNIQUE INDEX SIE_13_MIME_TYPE_PK ON SIE_13_MIME_TYPE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_MIME_TYPE_UK1;
CREATE UNIQUE INDEX SIE_13_MIME_TYPE_UK1 ON SIE_13_MIME_TYPE
(EXT, MIME_TYPE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_ELEMN_FK1;
CREATE INDEX SIE_13_NAVGT_ELEMN_FK1 ON SIE_13_NAVGT_ELEMN
(REF_NAVGT)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_ELEMN_IX1;
CREATE INDEX SIE_13_NAVGT_ELEMN_IX1 ON SIE_13_NAVGT_ELEMN
(SEQNC_ELEMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_ELEMN_PK;
CREATE UNIQUE INDEX SIE_13_NAVGT_ELEMN_PK ON SIE_13_NAVGT_ELEMN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_FK1;
CREATE INDEX SIE_13_NAVGT_FK1 ON SIE_13_NAVGT
(REF_ID_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_FK2;
CREATE INDEX SIE_13_NAVGT_FK2 ON SIE_13_NAVGT
(REF_FIL_ARIAN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_FK3;
CREATE INDEX SIE_13_NAVGT_FK3 ON SIE_13_NAVGT
(REF_RAPRT_INTER)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_NAVGT_PK;
CREATE UNIQUE INDEX SIE_13_NAVGT_PK ON SIE_13_NAVGT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OCURN_RESRC_FK1;
CREATE INDEX SIE_13_OCURN_RESRC_FK1 ON SIE_13_OCURN_RESRC
(REF_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OCURN_RESRC_FK2;
CREATE INDEX SIE_13_OCURN_RESRC_FK2 ON SIE_13_OCURN_RESRC
(REF_FORMT_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OCURN_RESRC_FK3;
CREATE INDEX SIE_13_OCURN_RESRC_FK3 ON SIE_13_OCURN_RESRC
(REF_MIME_TYPE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OCURN_RESRC_FK4;
CREATE INDEX SIE_13_OCURN_RESRC_FK4 ON SIE_13_OCURN_RESRC
(REF_VERSN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OCURN_RESRC_FK5;
CREATE INDEX SIE_13_OCURN_RESRC_FK5 ON SIE_13_OCURN_RESRC
(REF_DOSR_VIRTL)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OCURN_RESRC_PK;
CREATE UNIQUE INDEX SIE_13_OCURN_RESRC_PK ON SIE_13_OCURN_RESRC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OPERT_FK1;
CREATE INDEX SIE_13_OPERT_FK1 ON SIE_13_OPERT
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OPERT_OPTIO_PK;
CREATE UNIQUE INDEX SIE_13_OPERT_OPTIO_PK ON SIE_13_OPERT_OPTIO
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OPERT_OPTIO_UK1;
CREATE UNIQUE INDEX SIE_13_OPERT_OPTIO_UK1 ON SIE_13_OPERT_OPTIO
(REF_OPERT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OPERT_OPTIO_UK2;
CREATE UNIQUE INDEX SIE_13_OPERT_OPTIO_UK2 ON SIE_13_OPERT_OPTIO
(REF_OPERT, PREPN)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OPERT_PK;
CREATE UNIQUE INDEX SIE_13_OPERT_PK ON SIE_13_OPERT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_OPERT_UK1;
CREATE UNIQUE INDEX SIE_13_OPERT_UK1 ON SIE_13_OPERT
(REF_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK10;
CREATE INDEX SIE_13_PAGE_FK10 ON SIE_13_PAGE
(REF_MESG_RANGE_MODF_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK11;
CREATE INDEX SIE_13_PAGE_FK11 ON SIE_13_PAGE
(REF_MESG_RANGE_INSER_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK12;
CREATE INDEX SIE_13_PAGE_FK12 ON SIE_13_PAGE
(REF_MESG_AUCUN_DON_TROUV)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK13;
CREATE INDEX SIE_13_PAGE_FK13 ON SIE_13_PAGE
(REF_MESG_TROP_DON_TROUV)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK3;
CREATE INDEX SIE_13_PAGE_FK3 ON SIE_13_PAGE
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK4;
CREATE INDEX SIE_13_PAGE_FK4 ON SIE_13_PAGE
(REF_MESG_SUPRS_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK5;
CREATE INDEX SIE_13_PAGE_FK5 ON SIE_13_PAGE
(REF_PAGE_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK6;
CREATE INDEX SIE_13_PAGE_FK6 ON SIE_13_PAGE
(REF_MESG_SUCS_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK7;
CREATE INDEX SIE_13_PAGE_FK7 ON SIE_13_PAGE
(REF_MESG_ECHEC_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK8;
CREATE INDEX SIE_13_PAGE_FK8 ON SIE_13_PAGE
(REF_MESG_FETCH_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK9;
CREATE INDEX SIE_13_PAGE_FK9 ON SIE_13_PAGE
(REF_MESG_RANGE_SUPRM_SPECF)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_FK90;
CREATE INDEX SIE_13_PAGE_FK90 ON SIE_13_PAGE
(REF_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_IR_COLN_FK;
CREATE INDEX SIE_13_PAGE_IR_COLN_FK ON SIE_13_PAGE_IR_COLN
(REF_PAGE_IR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_IR_COLN_FK2;
CREATE INDEX SIE_13_PAGE_IR_COLN_FK2 ON SIE_13_PAGE_IR_COLN
(REF_MESG_AIDE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_IR_COLN_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_IR_COLN_PK ON SIE_13_PAGE_IR_COLN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_IR_FK1;
CREATE INDEX SIE_13_PAGE_IR_FK1 ON SIE_13_PAGE_IR
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_IR_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_IR_PK ON SIE_13_PAGE_IR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_IR_UK2;
CREATE UNIQUE INDEX SIE_13_PAGE_IR_UK2 ON SIE_13_PAGE_IR
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_FK1;
CREATE INDEX SIE_13_PAGE_ITEM_FK1 ON SIE_13_PAGE_ITEM
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_FK2;
CREATE INDEX SIE_13_PAGE_ITEM_FK2 ON SIE_13_PAGE_ITEM
(REF_MESG_AIDE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_FK3;
CREATE INDEX SIE_13_PAGE_ITEM_FK3 ON SIE_13_PAGE_ITEM
(REF_OPERT)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_LANG_FK2;
CREATE INDEX SIE_13_PAGE_ITEM_LANG_FK2 ON SIE_13_PAGE_ITEM_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_LANG_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_ITEM_LANG_PK ON SIE_13_PAGE_ITEM_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_LANG_UK1;
CREATE UNIQUE INDEX SIE_13_PAGE_ITEM_LANG_UK1 ON SIE_13_PAGE_ITEM_LANG
(REF_PAGE_ITEM, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_ITEM_PK ON SIE_13_PAGE_ITEM
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_ITEM_UK1;
CREATE UNIQUE INDEX SIE_13_PAGE_ITEM_UK1 ON SIE_13_PAGE_ITEM
(REF_PAGE, NOM_APEX, ID_APEX)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_LANG_FK2;
CREATE INDEX SIE_13_PAGE_LANG_FK2 ON SIE_13_PAGE_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_LANG_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_LANG_PK ON SIE_13_PAGE_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_LANG_UK1;
CREATE UNIQUE INDEX SIE_13_PAGE_LANG_UK1 ON SIE_13_PAGE_LANG
(REF_PAGE, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_PK ON SIE_13_PAGE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_PREFR_NAVGT_FK2;
CREATE INDEX SIE_13_PAGE_PREFR_NAVGT_FK2 ON SIE_13_PAGE_PREFR_NAVGT
(REF_PAGE_IR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_PREFR_NAVGT_PK;
CREATE UNIQUE INDEX SIE_13_PAGE_PREFR_NAVGT_PK ON SIE_13_PAGE_PREFR_NAVGT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_PREFR_NAVGT_UK1;
CREATE UNIQUE INDEX SIE_13_PAGE_PREFR_NAVGT_UK1 ON SIE_13_PAGE_PREFR_NAVGT
(REF_PAGE, REF_PAGE_IR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PAGE_UK1;
CREATE UNIQUE INDEX SIE_13_PAGE_UK1 ON SIE_13_PAGE
(REF_APLIC, NUMR_APEX)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PREFR_FK1;
CREATE INDEX SIE_13_PREFR_FK1 ON SIE_13_PREFR
(REF_DV_CONDT_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PREFR_FK2;
CREATE INDEX SIE_13_PREFR_FK2 ON SIE_13_PREFR
(REF_DV_CONDT_SAUVG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PREFR_FK3;
CREATE INDEX SIE_13_PREFR_FK3 ON SIE_13_PREFR
(REF_DV_TYPE_INSTA)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PREFR_FK4;
CREATE INDEX SIE_13_PREFR_FK4 ON SIE_13_PREFR
(REF_DV_VALR_INSTA)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PREFR_FK6;
CREATE INDEX SIE_13_PREFR_FK6 ON SIE_13_PREFR
(REF_ITEM)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_PREFR_PK;
CREATE UNIQUE INDEX SIE_13_PREFR_PK ON SIE_13_PREFR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_REGN_PILTB_FK2;
CREATE INDEX SIE_13_REGN_PILTB_FK2 ON SIE_13_REGN_PILTB
(REF_DV_TYPE_REGN_PILTB)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_REGN_PILTB_LANG_FK2;
CREATE INDEX SIE_13_REGN_PILTB_LANG_FK2 ON SIE_13_REGN_PILTB_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_REGN_PILTB_LANG_PK;
CREATE UNIQUE INDEX SIE_13_REGN_PILTB_LANG_PK ON SIE_13_REGN_PILTB_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_REGN_PILTB_LANG_UK1;
CREATE UNIQUE INDEX SIE_13_REGN_PILTB_LANG_UK1 ON SIE_13_REGN_PILTB_LANG
(REF_REGN_PILTB, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_REGN_PILTB_PK;
CREATE UNIQUE INDEX SIE_13_REGN_PILTB_PK ON SIE_13_REGN_PILTB
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_REGN_PILTB_UK1;
CREATE UNIQUE INDEX SIE_13_REGN_PILTB_UK1 ON SIE_13_REGN_PILTB
(REF_PAGE, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_RESRC_FK1;
CREATE INDEX SIE_13_RESRC_FK1 ON SIE_13_RESRC
(REF_TYPE_FICHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_RESRC_FK2;
CREATE INDEX SIE_13_RESRC_FK2 ON SIE_13_RESRC
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_RESRC_FK4;
CREATE INDEX SIE_13_RESRC_FK4 ON SIE_13_RESRC
(REF_DOSR_VIRTL)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_RESRC_PK;
CREATE UNIQUE INDEX SIE_13_RESRC_PK ON SIE_13_RESRC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_RESRC_UK1;
CREATE UNIQUE INDEX SIE_13_RESRC_UK1 ON SIE_13_RESRC
(REF_STRUC_APLIC, REF_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_TYPE_FICHR_PK;
CREATE UNIQUE INDEX SIE_13_TYPE_FICHR_PK ON SIE_13_TYPE_FICHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_13_TYPE_FICHR_UK1;
CREATE UNIQUE INDEX SIE_13_TYPE_FICHR_UK1 ON SIE_13_TYPE_FICHR
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DETL_DOMN_VALR_FK1;
CREATE INDEX SIE_14_DETL_DOMN_VALR_FK1 ON SIE_14_DETL_DOMN_VALR
(REF_DOMN_VALR)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DETL_DOMN_VALR_PK;
CREATE UNIQUE INDEX SIE_14_DETL_DOMN_VALR_PK ON SIE_14_DETL_DOMN_VALR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DOMN_VALR_FK1;
CREATE INDEX SIE_14_DOMN_VALR_FK1 ON SIE_14_DOMN_VALR
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DOMN_VALR_FK2;
CREATE INDEX SIE_14_DOMN_VALR_FK2 ON SIE_14_DOMN_VALR
(REF_FORMT)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DOMN_VALR_FK3;
CREATE INDEX SIE_14_DOMN_VALR_FK3 ON SIE_14_DOMN_VALR
(REF_TYPE_DOMN_VALR)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DOMN_VALR_PK;
CREATE UNIQUE INDEX SIE_14_DOMN_VALR_PK ON SIE_14_DOMN_VALR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_DOMN_VALR_UK1;
CREATE UNIQUE INDEX SIE_14_DOMN_VALR_UK1 ON SIE_14_DOMN_VALR
(CODE, REF_PRODT, REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_FORMT_PK;
CREATE UNIQUE INDEX SIE_14_FORMT_PK ON SIE_14_FORMT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_FORMT_UK1;
CREATE UNIQUE INDEX SIE_14_FORMT_UK1 ON SIE_14_FORMT
(REF_PRODT, DEFNT)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_TYPE_DOMN_VALR_FK1;
CREATE INDEX SIE_14_TYPE_DOMN_VALR_FK1 ON SIE_14_TYPE_DOMN_VALR
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_TYPE_DOMN_VALR_PK;
CREATE UNIQUE INDEX SIE_14_TYPE_DOMN_VALR_PK ON SIE_14_TYPE_DOMN_VALR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_14_TYPE_DOMN_VALR_UK1;
CREATE UNIQUE INDEX SIE_14_TYPE_DOMN_VALR_UK1 ON SIE_14_TYPE_DOMN_VALR
(CODE, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_ATACH_COURL_ENTRA_PK;
CREATE UNIQUE INDEX SIE_17_ATACH_COURL_ENTRA_PK ON SIE_17_ATACH_COURL_ENTRA
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COMPT_AXIAT_FK2;
CREATE INDEX SIE_17_COMPT_AXIAT_FK2 ON SIE_17_COMPT_AXIAT
(REF_PROFL_COURL)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COMPT_AXIAT_FK3;
CREATE INDEX SIE_17_COMPT_AXIAT_FK3 ON SIE_17_COMPT_AXIAT
(REF_PUBLC_PAGE_GARDE)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COMPT_AXIAT_PK;
CREATE UNIQUE INDEX SIE_17_COMPT_AXIAT_PK ON SIE_17_COMPT_AXIAT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COMPT_AXIAT_UK1;
CREATE UNIQUE INDEX SIE_17_COMPT_AXIAT_UK1 ON SIE_17_COMPT_AXIAT
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COMPT_AXIAT_UK2;
CREATE UNIQUE INDEX SIE_17_COMPT_AXIAT_UK2 ON SIE_17_COMPT_AXIAT
(REF_DOMN, NUMR)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COMPT_TWILI_PK;
CREATE UNIQUE INDEX SIE_17_COMPT_TWILI_PK ON SIE_17_COMPT_TWILI
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COOMPT_TWILI_FK1;
CREATE INDEX SIE_17_COOMPT_TWILI_FK1 ON SIE_17_COMPT_TWILI
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COURL_ENTRA_PK;
CREATE UNIQUE INDEX SIE_17_COURL_ENTRA_PK ON SIE_17_COURL_ENTRA
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COURL_PIECE_JOINT_FK1;
CREATE INDEX SIE_17_COURL_PIECE_JOINT_FK1 ON SIE_17_COURL_PIECE_JOINT
(REF_COURL)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_COURL_PIECE_JOINT_PK;
CREATE UNIQUE INDEX SIE_17_COURL_PIECE_JOINT_PK ON SIE_17_COURL_PIECE_JOINT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_FIL_ATENT_DESTN_FK1;
CREATE INDEX SIE_17_FIL_ATENT_DESTN_FK1 ON SIE_17_COURL_DESTN
(REF_FIL_ATENT)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_FIL_ATENT_DESTN_PK;
CREATE UNIQUE INDEX SIE_17_FIL_ATENT_DESTN_PK ON SIE_17_COURL_DESTN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_FIL_ATENT_PK;
CREATE UNIQUE INDEX SIE_17_FIL_ATENT_PK ON SIE_17_COURL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_PIECE_TELCP_AXIAT_FK1;
CREATE INDEX SIE_17_PIECE_TELCP_AXIAT_FK1 ON SIE_17_PIECE_TELCP_AXIAT
(REF_TELCP_AXIAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_PIECE_TELCP_AXIAT_PK;
CREATE UNIQUE INDEX SIE_17_PIECE_TELCP_AXIAT_PK ON SIE_17_PIECE_TELCP_AXIAT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_PROFL_COURL_PK;
CREATE UNIQUE INDEX SIE_17_PROFL_COURL_PK ON SIE_17_PROFL_COURL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_PROFL_COURL_UK2;
CREATE UNIQUE INDEX SIE_17_PROFL_COURL_UK2 ON SIE_17_PROFL_COURL
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_PROPR_COURL_ENTRA_PK;
CREATE UNIQUE INDEX SIE_17_PROPR_COURL_ENTRA_PK ON SIE_17_PROPR_COURL_ENTRA
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_SMS_TWILI_ENTRA_PK;
CREATE UNIQUE INDEX SIE_17_SMS_TWILI_ENTRA_PK ON SIE_17_SMS_TWILI_ENTRA
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_SMS_TWILI_FK1;
CREATE INDEX SIE_17_SMS_TWILI_FK1 ON SIE_17_SMS_TWILI
(REF_COMPT_TWILI)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_SMS_TWILI_IX1;
CREATE INDEX SIE_17_SMS_TWILI_IX1 ON SIE_17_SMS_TWILI
(ID_SESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_SMS_TWILI_IX2;
CREATE INDEX SIE_17_SMS_TWILI_IX2 ON SIE_17_SMS_TWILI
(STAT_SOUMS)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_SMS_TWILI_PK;
CREATE UNIQUE INDEX SIE_17_SMS_TWILI_PK ON SIE_17_SMS_TWILI
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_TELCP_AXIAT_FK1;
CREATE INDEX SIE_17_TELCP_AXIAT_FK1 ON SIE_17_TELCP_AXIAT
(REF_COMPT_AXIAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_17_TELCP_AXIAT_PK;
CREATE UNIQUE INDEX SIE_17_TELCP_AXIAT_PK ON SIE_17_TELCP_AXIAT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_BOUTN_FK2;
CREATE INDEX SIE_19_BOUTN_FK2 ON SIE_19_BOUTN
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_BOUTN_FK3;
CREATE INDEX SIE_19_BOUTN_FK3 ON SIE_19_BOUTN
(REF_DV_TYPE_MESG_AIDE_CONTX)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_BOUTN_PK;
CREATE UNIQUE INDEX SIE_19_BOUTN_PK ON SIE_19_BOUTN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_BOUTN_UK1;
CREATE UNIQUE INDEX SIE_19_BOUTN_UK1 ON SIE_19_BOUTN
(REF_DISPN_FONCT, REF_LANG, ITEM_SUBST)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_CLE_FK3;
CREATE INDEX SIE_19_CLE_FK3 ON SIE_19_CLE
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_CLE_PK;
CREATE UNIQUE INDEX SIE_19_CLE_PK ON SIE_19_CLE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_CLE_UK1;
CREATE UNIQUE INDEX SIE_19_CLE_UK1 ON SIE_19_CLE
(REF_DISPN_FONCT, REF_LANG, INDIC_INTER, CODE_KEYPR, CODE_KEYDW, 
INDIC_SHIFT, INDIC_ALT, INDIC_CTRL)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_DISPN_FONCT_FK1;
CREATE INDEX SIE_19_DISPN_FONCT_FK1 ON SIE_19_DISPN_FONCT
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_DISPN_FONCT_FK2;
CREATE INDEX SIE_19_DISPN_FONCT_FK2 ON SIE_19_DISPN_FONCT
(REF_FONCT)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_DISPN_FONCT_PK;
CREATE UNIQUE INDEX SIE_19_DISPN_FONCT_PK ON SIE_19_DISPN_FONCT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_DISPN_FONCT_UK1;
CREATE UNIQUE INDEX SIE_19_DISPN_FONCT_UK1 ON SIE_19_DISPN_FONCT
(REF_FONCT, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_DESCR_FK1;
CREATE INDEX SIE_19_FONCT_DESCR_FK1 ON SIE_19_FONCT_LANG
(REF_FONCT)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_DESCR_FK2;
CREATE INDEX SIE_19_FONCT_DESCR_FK2 ON SIE_19_FONCT_LANG
(REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK1;
CREATE INDEX SIE_19_FONCT_FK1 ON SIE_19_FONCT
(REF_DV_TYPE_ATRIB1)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK2;
CREATE INDEX SIE_19_FONCT_FK2 ON SIE_19_FONCT
(REF_DV_TYPE_ATRIB2)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK3;
CREATE INDEX SIE_19_FONCT_FK3 ON SIE_19_FONCT
(REF_DV_TYPE_ATRIB3)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK4;
CREATE INDEX SIE_19_FONCT_FK4 ON SIE_19_FONCT
(REF_DV_TYPE_ATRIB4)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK5;
CREATE INDEX SIE_19_FONCT_FK5 ON SIE_19_FONCT
(REF_DV_TYPE_ATRIB5)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK6;
CREATE INDEX SIE_19_FONCT_FK6 ON SIE_19_FONCT
(REF_DV_TYPE_ACTIO)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_FK7;
CREATE INDEX SIE_19_FONCT_FK7 ON SIE_19_FONCT
(REF_DV_TYPE_EXPRE)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_LANG_PK;
CREATE UNIQUE INDEX SIE_19_FONCT_LANG_PK ON SIE_19_FONCT_LANG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_LANG_UK1;
CREATE UNIQUE INDEX SIE_19_FONCT_LANG_UK1 ON SIE_19_FONCT_LANG
(REF_FONCT, REF_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_PK;
CREATE UNIQUE INDEX SIE_19_FONCT_PK ON SIE_19_FONCT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_FONCT_UK1;
CREATE UNIQUE INDEX SIE_19_FONCT_UK1 ON SIE_19_FONCT
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_SPECF_FONCT_FK1;
CREATE INDEX SIE_19_SPECF_FONCT_FK1 ON SIE_19_SPECF_FONCT
(REF_DISPN_FONCT)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_SPECF_FONCT_FK2;
CREATE INDEX SIE_19_SPECF_FONCT_FK2 ON SIE_19_SPECF_FONCT
(REF_ITEM)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_SPECF_FONCT_FK3;
CREATE INDEX SIE_19_SPECF_FONCT_FK3 ON SIE_19_SPECF_FONCT
(REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_SPECF_FONCT_FK4;
CREATE INDEX SIE_19_SPECF_FONCT_FK4 ON SIE_19_SPECF_FONCT
(REF_DV_TYPE_SUBST)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_SPECF_FONCT_FK98;
CREATE INDEX SIE_19_SPECF_FONCT_FK98 ON SIE_19_SPECF_FONCT
(DNR_REF_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_19_SPECF_FONCT_PK;
CREATE UNIQUE INDEX SIE_19_SPECF_FONCT_PK ON SIE_19_SPECF_FONCT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DEPLM_FK1;
CREATE INDEX SIE_20_DEPLM_FK1 ON SIE_20_DEPLM
(REF_MODL)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DEPLM_FK2;
CREATE INDEX SIE_20_DEPLM_FK2 ON SIE_20_DEPLM
(REF_MODL_PARMT)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DEPLM_FK3;
CREATE INDEX SIE_20_DEPLM_FK3 ON SIE_20_DEPLM
(REF_PRODT_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DETL_DOCMN_FK1;
CREATE INDEX SIE_20_DETL_DOCMN_FK1 ON SIE_20_DETL_DOCMN
(REF_DOCMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DETL_DOCMN_FK2;
CREATE INDEX SIE_20_DETL_DOCMN_FK2 ON SIE_20_DETL_DOCMN
(REF_SECTN_DOCMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DETL_DOCMN_FK3;
CREATE INDEX SIE_20_DETL_DOCMN_FK3 ON SIE_20_DETL_DOCMN
(REF_DETL_DOCMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DOCMN_FK2;
CREATE INDEX SIE_20_DOCMN_FK2 ON SIE_20_DOCMN
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_DOCMN_FK4;
CREATE INDEX SIE_20_DOCMN_FK4 ON SIE_20_DOCMN
(REF_PRODT_LANG)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_MODL_EXCEP;
CREATE INDEX SIE_20_MODL_EXCEP ON SIE_20_MODL_EXCEP
(REF_MODL)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_MODL_FK1;
CREATE INDEX SIE_20_MODL_FK1 ON SIE_20_MODL
(REF_VERSN)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_MODL_FK2;
CREATE INDEX SIE_20_MODL_FK2 ON SIE_20_MODL
(REF_MODL)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_MODL_FK3;
CREATE INDEX SIE_20_MODL_FK3 ON SIE_20_MODL
(REF_DV_TYPE_MODL)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_MODL_PARMT_FK1;
CREATE INDEX SIE_20_MODL_PARMT_FK1 ON SIE_20_MODL_PARMT
(REF_MODL)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_MODL_PARMT_FK2;
CREATE INDEX SIE_20_MODL_PARMT_FK2 ON SIE_20_MODL_PARMT
(REF_DV_TYPE_DON)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_SECTN_DOCMN_FK1;
CREATE INDEX SIE_20_SECTN_DOCMN_FK1 ON SIE_20_SECTN_DOCMN
(REF_SECTN_DOCMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_SECTN_DOCMN_FK2;
CREATE INDEX SIE_20_SECTN_DOCMN_FK2 ON SIE_20_SECTN_DOCMN
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_20_SECTN_DOCMN_FK3;
CREATE INDEX SIE_20_SECTN_DOCMN_FK3 ON SIE_20_SECTN_DOCMN
(REF_FORMT)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_FK2;
CREATE INDEX SIE_21_PLUGN_ARBRE_FK2 ON SIE_21_PLUGN_ARBRE
(REF_PLUGN_ARBRE_NOEUD)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_FK3;
CREATE INDEX SIE_21_PLUGN_ARBRE_FK3 ON SIE_21_PLUGN_ARBRE
(REF_FORMT_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_FK4;
CREATE INDEX SIE_21_PLUGN_ARBRE_FK4 ON SIE_21_PLUGN_ARBRE
(REF_DV_CURSR_AIDE_INSTA)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_NOEUD_FK2;
CREATE INDEX SIE_21_PLUGN_ARBRE_NOEUD_FK2 ON SIE_21_PLUGN_ARBRE_NOEUD
(REF_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_NOEUD_FK3;
CREATE INDEX SIE_21_PLUGN_ARBRE_NOEUD_FK3 ON SIE_21_PLUGN_ARBRE_NOEUD
(REF_OCURN_RESRC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_NOEUD_PK;
CREATE UNIQUE INDEX SIE_21_PLUGN_ARBRE_NOEUD_PK ON SIE_21_PLUGN_ARBRE_NOEUD
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_NOEUD_UK1;
CREATE UNIQUE INDEX SIE_21_PLUGN_ARBRE_NOEUD_UK1 ON SIE_21_PLUGN_ARBRE_NOEUD
(REF_PLUGN_ARBRE, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_PK;
CREATE UNIQUE INDEX SIE_21_PLUGN_ARBRE_PK ON SIE_21_PLUGN_ARBRE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ARBRE_UK1;
CREATE UNIQUE INDEX SIE_21_PLUGN_ARBRE_UK1 ON SIE_21_PLUGN_ARBRE
(CODE, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_CALND_COULR_UK1;
CREATE UNIQUE INDEX SIE_21_PLUGN_CALND_COULR_UK1 ON SIE_21_PLUGN_CALND_COULR
(ORDRE_PRESN)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_CALND_FK2;
CREATE INDEX SIE_21_PLUGN_CALND_FK2 ON SIE_21_PLUGN_CALND
(REF_DV_VUE_DEFT)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_CALND_PK;
CREATE UNIQUE INDEX SIE_21_PLUGN_CALND_PK ON SIE_21_PLUGN_CALND
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_CALND_TYPE_FK1;
CREATE INDEX SIE_21_PLUGN_CALND_TYPE_FK1 ON SIE_21_PLUGN_CALND_TYPE
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_CALND_TYPE_PK;
CREATE UNIQUE INDEX SIE_21_PLUGN_CALND_TYPE_PK ON SIE_21_PLUGN_CALND_TYPE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_CALND_UK1;
CREATE UNIQUE INDEX SIE_21_PLUGN_CALND_UK1 ON SIE_21_PLUGN_CALND
(CODE, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ITEM_MENU_FK2;
CREATE INDEX SIE_21_PLUGN_ITEM_MENU_FK2 ON SIE_21_PLUGN_ITEM_MENU
(REF_PLUGN_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ITEM_MENU_FK3;
CREATE INDEX SIE_21_PLUGN_ITEM_MENU_FK3 ON SIE_21_PLUGN_ITEM_MENU
(REF_DV_CONTN_ITEM_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ITEM_MENU_FK4;
CREATE INDEX SIE_21_PLUGN_ITEM_MENU_FK4 ON SIE_21_PLUGN_ITEM_MENU
(REF_DV_ALIGN)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ITEM_MENU_PK;
CREATE UNIQUE INDEX SIE_21_PLUGN_ITEM_MENU_PK ON SIE_21_PLUGN_ITEM_MENU
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_ITEM_MENU_UK1;
CREATE UNIQUE INDEX SIE_21_PLUGN_ITEM_MENU_UK1 ON SIE_21_PLUGN_ITEM_MENU
(REF_ITEM_MENU, REF_PLUGN_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_FK2;
CREATE INDEX SIE_21_PLUGN_MENU_FK2 ON SIE_21_PLUGN_MENU
(REF_DV_TYPE_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_FK3;
CREATE INDEX SIE_21_PLUGN_MENU_FK3 ON SIE_21_PLUGN_MENU
(REF_DV_COULR_PRINC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_FK4;
CREATE INDEX SIE_21_PLUGN_MENU_FK4 ON SIE_21_PLUGN_MENU
(REF_DV_COULR_THEME)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_FK5;
CREATE INDEX SIE_21_PLUGN_MENU_FK5 ON SIE_21_PLUGN_MENU
(REF_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_FK6;
CREATE INDEX SIE_21_PLUGN_MENU_FK6 ON SIE_21_PLUGN_MENU
(REF_DV_FORMT_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_FK7;
CREATE INDEX SIE_21_PLUGN_MENU_FK7 ON SIE_21_PLUGN_MENU
(REF_DV_ORIEN_MENU)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_PK;
CREATE UNIQUE INDEX SIE_21_PLUGN_MENU_PK ON SIE_21_PLUGN_MENU
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_21_PLUGN_MENU_UK1;
CREATE UNIQUE INDEX SIE_21_PLUGN_MENU_UK1 ON SIE_21_PLUGN_MENU
(CODE, REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_APLIC_MODL_RECHR_FK1;
CREATE INDEX SIE_23_APLIC_MODL_RECHR_FK1 ON SIE_23_APLIC_MODL_RECHR
(REF_MODL_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_APLIC_MODL_RECHR_FK2;
CREATE INDEX SIE_23_APLIC_MODL_RECHR_FK2 ON SIE_23_APLIC_MODL_RECHR
(REF_STRUC_APLIC_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_APLIC_MODL_RECHR_FK3;
CREATE INDEX SIE_23_APLIC_MODL_RECHR_FK3 ON SIE_23_APLIC_MODL_RECHR
(REF_ATRIB_STRUC_APLIC_AFICH)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_APLIC_MODL_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_APLIC_MODL_RECHR_PK ON SIE_23_APLIC_MODL_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_APLIC_MODL_RECHR_UK1;
CREATE UNIQUE INDEX SIE_23_APLIC_MODL_RECHR_UK1 ON SIE_23_APLIC_MODL_RECHR
(REF_MODL_RECHR, REF_STRUC_APLIC_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_APLIC_MODL_REC_FK1;
CREATE INDEX SIE_23_DETL_APLIC_MODL_REC_FK1 ON SIE_23_DETL_APLIC_MODL_RECHR
(REF_APLIC_MODL_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_APLIC_MODL_REC_FK2;
CREATE INDEX SIE_23_DETL_APLIC_MODL_REC_FK2 ON SIE_23_DETL_APLIC_MODL_RECHR
(REF_ATRIB_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_APLIC_MODL_REC_FK3;
CREATE INDEX SIE_23_DETL_APLIC_MODL_REC_FK3 ON SIE_23_DETL_APLIC_MODL_RECHR
(REF_PATRN_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_APLIC_MODL_REC_PK;
CREATE UNIQUE INDEX SIE_23_DETL_APLIC_MODL_REC_PK ON SIE_23_DETL_APLIC_MODL_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_APLIC_MODL_REC_UK1;
CREATE UNIQUE INDEX SIE_23_DETL_APLIC_MODL_REC_UK1 ON SIE_23_DETL_APLIC_MODL_RECHR
(REF_APLIC_MODL_RECHR, REF_ATRIB_STRUC_APLIC, REF_PATRN_RECHR, PERTN)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_RESLT_RECHR_FK1;
CREATE INDEX SIE_23_DETL_RESLT_RECHR_FK1 ON SIE_23_DETL_RESLT_RECHR
(REF_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_RESLT_RECHR_FK2;
CREATE INDEX SIE_23_DETL_RESLT_RECHR_FK2 ON SIE_23_DETL_RESLT_RECHR
(REF_ENONC_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_RESLT_RECHR_FK3;
CREATE INDEX SIE_23_DETL_RESLT_RECHR_FK3 ON SIE_23_DETL_RESLT_RECHR
(REF_DETL_APLIC_MODL_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_RESLT_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_DETL_RESLT_RECHR_PK ON SIE_23_DETL_RESLT_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_DETL_RESLT_RECHR_UK1;
CREATE UNIQUE INDEX SIE_23_DETL_RESLT_RECHR_UK1 ON SIE_23_DETL_RESLT_RECHR
(REF_RECHR, REF_ENONC_RECHR, REF_DETL_APLIC_MODL_RECHR, REF_SEQNC_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_ENONC_RECHR_FK1;
CREATE INDEX SIE_23_ENONC_RECHR_FK1 ON SIE_23_ENONC_RECHR
(REF_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_ENONC_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_ENONC_RECHR_PK ON SIE_23_ENONC_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_MODL_RECHR_FK1;
CREATE INDEX SIE_23_MODL_RECHR_FK1 ON SIE_23_MODL_RECHR
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_MODL_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_MODL_RECHR_PK ON SIE_23_MODL_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_PATRN_RECHR_FK50;
CREATE INDEX SIE_23_PATRN_RECHR_FK50 ON SIE_23_PATRN_RECHR
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_PATRN_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_PATRN_RECHR_PK ON SIE_23_PATRN_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_RECHR_FK1;
CREATE INDEX SIE_23_RECHR_FK1 ON SIE_23_RECHR
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_RECHR_FK2;
CREATE INDEX SIE_23_RECHR_FK2 ON SIE_23_RECHR
(REF_MODL_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_RECHR_PK ON SIE_23_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_RESLT_RECHR_PK;
CREATE UNIQUE INDEX SIE_23_RESLT_RECHR_PK ON SIE_23_RESLT_RECHR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_SOMR_RECHR_FK1;
CREATE INDEX SIE_23_SOMR_RECHR_FK1 ON SIE_23_RESLT_RECHR
(REF_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_23_SOMR_RECHR_FK2;
CREATE INDEX SIE_23_SOMR_RECHR_FK2 ON SIE_23_RESLT_RECHR
(REF_APLIC_MODL_RECHR)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_FK1;
CREATE INDEX SIE_25_CHAMP_FK1 ON SIE_25_CHAMP
(REF_VERSN_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_FK2;
CREATE INDEX SIE_25_CHAMP_FK2 ON SIE_25_CHAMP
(REF_FORMT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_FK3;
CREATE INDEX SIE_25_CHAMP_FK3 ON SIE_25_CHAMP
(REF_DV_TYPE_CHAMP)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_PK;
CREATE UNIQUE INDEX SIE_25_CHAMP_PK ON SIE_25_CHAMP
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_PUBLC_TRAVL_FK1;
CREATE INDEX SIE_25_CHAMP_PUBLC_TRAVL_FK1 ON SIE_25_CHAMP_PUBLC_TRAVL
(REF_CHAMP)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_PUBLC_TRAVL_PK;
CREATE UNIQUE INDEX SIE_25_CHAMP_PUBLC_TRAVL_PK ON SIE_25_CHAMP_PUBLC_TRAVL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_PUBLC_TRAVL_UK1;
CREATE UNIQUE INDEX SIE_25_CHAMP_PUBLC_TRAVL_UK1 ON SIE_25_CHAMP_PUBLC_TRAVL
(REF_PUBLC_TRAVL, REF_CHAMP)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_CHAMP_UK1;
CREATE UNIQUE INDEX SIE_25_CHAMP_UK1 ON SIE_25_CHAMP
(CODE, REF_VERSN_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_DOMN_TYPE_PUBLC_FK1;
CREATE INDEX SIE_25_DOMN_TYPE_PUBLC_FK1 ON SIE_25_DOMN_TYPE_PUBLC
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_DOMN_TYPE_PUBLC_FK2;
CREATE INDEX SIE_25_DOMN_TYPE_PUBLC_FK2 ON SIE_25_DOMN_TYPE_PUBLC
(REF_TYPE_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_DOMN_TYPE_PUBLC_FK3;
CREATE INDEX SIE_25_DOMN_TYPE_PUBLC_FK3 ON SIE_25_DOMN_TYPE_PUBLC
(REF_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_DOMN_TYPE_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_DOMN_TYPE_PUBLC_PK ON SIE_25_DOMN_TYPE_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_DOMN_TYPE_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_DOMN_TYPE_PUBLC_UK1 ON SIE_25_DOMN_TYPE_PUBLC
(REF_DOMN, REF_TYPE_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ELEMN_CONFG_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_ELEMN_CONFG_PUBLC_PK ON SIE_25_ELEMN_CONFG_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ELEMN_CONFG_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_ELEMN_CONFG_PUBLC_UK1 ON SIE_25_ELEMN_CONFG_PUBLC
(REF_TYPE_PUBLC, CODE, DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_PK;
CREATE UNIQUE INDEX SIE_25_ENGIN_PK ON SIE_25_ENGIN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_UK1;
CREATE UNIQUE INDEX SIE_25_ENGIN_UK1 ON SIE_25_ENGIN
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_UK2;
CREATE UNIQUE INDEX SIE_25_ENGIN_UK2 ON SIE_25_ENGIN
(REF_DV_FORMT_SORT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_VERSN_PUBLC_FK1;
CREATE INDEX SIE_25_ENGIN_VERSN_PUBLC_FK1 ON SIE_25_ENGIN_VERSN_PUBLC
(REF_VERSN_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_VERSN_PUBLC_FK2;
CREATE INDEX SIE_25_ENGIN_VERSN_PUBLC_FK2 ON SIE_25_ENGIN_VERSN_PUBLC
(REF_ENGIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_VERSN_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_ENGIN_VERSN_PUBLC_PK ON SIE_25_ENGIN_VERSN_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_ENGIN_VERSN_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_ENGIN_VERSN_PUBLC_UK1 ON SIE_25_ENGIN_VERSN_PUBLC
(REF_VERSN_PUBLC, REF_ENGIN, DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_GROUP_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_GROUP_PUBLC_PK ON SIE_25_GROUP_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_GROUP_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_GROUP_PUBLC_UK1 ON SIE_25_GROUP_PUBLC
(CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_JOURN_TRAVL_EXECT_FK1;
CREATE INDEX SIE_25_JOURN_TRAVL_EXECT_FK1 ON SIE_25_JOURN_TRAVL_EXECT
(REF_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_JOURN_TRAVL_EXECT_FK2;
CREATE INDEX SIE_25_JOURN_TRAVL_EXECT_FK2 ON SIE_25_JOURN_TRAVL_EXECT
(REF_PUBLC_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_JOURN_TRAVL_EXECT_FK3;
CREATE INDEX SIE_25_JOURN_TRAVL_EXECT_FK3 ON SIE_25_JOURN_TRAVL_EXECT
(REF_DV_TYPE_ECRIT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_JOURN_TRAVL_EXECT_PK;
CREATE UNIQUE INDEX SIE_25_JOURN_TRAVL_EXECT_PK ON SIE_25_JOURN_TRAVL_EXECT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_OCURN_PARMT_PUB_TRA_FK1;
CREATE INDEX SIE_25_OCURN_PARMT_PUB_TRA_FK1 ON SIE_25_OCURN_PARMT_PUBLC_TRAVL
(REF_PARMT_PUBLC_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_OCURN_PARMT_PUB_TRA_PK;
CREATE UNIQUE INDEX SIE_25_OCURN_PARMT_PUB_TRA_PK ON SIE_25_OCURN_PARMT_PUBLC_TRAVL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_PUBLC_TRAVL_E_FK1;
CREATE INDEX SIE_25_PARMT_PUBLC_TRAVL_E_FK1 ON SIE_25_PARMT_PUBLC_TRAVL_EXECT
(REF_TRAVL_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_PUBLC_TRAVL_E_FK2;
CREATE INDEX SIE_25_PARMT_PUBLC_TRAVL_E_FK2 ON SIE_25_PARMT_PUBLC_TRAVL_EXECT
(REF_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_PUBLC_TRAVL_E_PK;
CREATE UNIQUE INDEX SIE_25_PARMT_PUBLC_TRAVL_E_PK ON SIE_25_PARMT_PUBLC_TRAVL_EXECT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_PUBLC_TRAVL_FK1;
CREATE INDEX SIE_25_PARMT_PUBLC_TRAVL_FK1 ON SIE_25_PARMT_PUBLC_TRAVL
(REF_PUBLC_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_PUBLC_TRAVL_FK2;
CREATE INDEX SIE_25_PARMT_PUBLC_TRAVL_FK2 ON SIE_25_PARMT_PUBLC_TRAVL
(REF_PARMT_TYPE_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_PUBLC_TRAVL_PK;
CREATE UNIQUE INDEX SIE_25_PARMT_PUBLC_TRAVL_PK ON SIE_25_PARMT_PUBLC_TRAVL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_TYPE_PUBLC_FK2;
CREATE INDEX SIE_25_PARMT_TYPE_PUBLC_FK2 ON SIE_25_PARMT_TYPE_PUBLC
(REF_ENGIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_TYPE_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_PARMT_TYPE_PUBLC_PK ON SIE_25_PARMT_TYPE_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PARMT_TYPE_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_PARMT_TYPE_PUBLC_UK1 ON SIE_25_PARMT_TYPE_PUBLC
(REF_TYPE_PUBLC, REF_ENGIN, CODE, DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_FK1;
CREATE INDEX SIE_25_PUBLC_FK1 ON SIE_25_PUBLC
(REF_TYPE_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_FK2;
CREATE INDEX SIE_25_PUBLC_FK2 ON SIE_25_PUBLC
(REF_GROUP_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_PUBLC_PK ON SIE_25_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_TRAVL_FK1;
CREATE INDEX SIE_25_PUBLC_TRAVL_FK1 ON SIE_25_PUBLC_TRAVL
(REF_VERSN_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_TRAVL_FK2;
CREATE INDEX SIE_25_PUBLC_TRAVL_FK2 ON SIE_25_PUBLC_TRAVL
(REF_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_TRAVL_FK3;
CREATE INDEX SIE_25_PUBLC_TRAVL_FK3 ON SIE_25_PUBLC_TRAVL
(REF_STAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_TRAVL_FK7;
CREATE INDEX SIE_25_PUBLC_TRAVL_FK7 ON SIE_25_PUBLC_TRAVL
(REF_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_TRAVL_PK;
CREATE UNIQUE INDEX SIE_25_PUBLC_TRAVL_PK ON SIE_25_PUBLC_TRAVL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_PUBLC_UK1 ON SIE_25_PUBLC
(CODE, DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TRAVL_FK1;
CREATE INDEX SIE_25_TRAVL_FK1 ON SIE_25_TRAVL
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TRAVL_FK2;
CREATE INDEX SIE_25_TRAVL_FK2 ON SIE_25_TRAVL
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TRAVL_FK3;
CREATE INDEX SIE_25_TRAVL_FK3 ON SIE_25_TRAVL
(REF_STAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TRAVL_FK4;
CREATE INDEX SIE_25_TRAVL_FK4 ON SIE_25_TRAVL
(REF_TYPE_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TRAVL_PK;
CREATE UNIQUE INDEX SIE_25_TRAVL_PK ON SIE_25_TRAVL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TYPE_PUBLC_FK1;
CREATE INDEX SIE_25_TYPE_PUBLC_FK1 ON SIE_25_TYPE_PUBLC
(REF_STRUC_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TYPE_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_TYPE_PUBLC_PK ON SIE_25_TYPE_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TYPE_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_TYPE_PUBLC_UK1 ON SIE_25_TYPE_PUBLC
(CODE, DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TYPE_TRAVL_FK1;
CREATE INDEX SIE_25_TYPE_TRAVL_FK1 ON SIE_25_TYPE_TRAVL
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TYPE_TRAVL_PK;
CREATE UNIQUE INDEX SIE_25_TYPE_TRAVL_PK ON SIE_25_TYPE_TRAVL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_TYPE_TRAVL_UK1;
CREATE UNIQUE INDEX SIE_25_TYPE_TRAVL_UK1 ON SIE_25_TYPE_TRAVL
(REF_DOMN, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_CHAMP_FK1;
CREATE INDEX SIE_25_VALR_CHAMP_FK1 ON SIE_25_VALR_CHAMP
(REF_PUBLC_TRAVL)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_CHAMP_FK2;
CREATE INDEX SIE_25_VALR_CHAMP_FK2 ON SIE_25_VALR_CHAMP
(REF_CHAMP)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_CHAMP_PK;
CREATE UNIQUE INDEX SIE_25_VALR_CHAMP_PK ON SIE_25_VALR_CHAMP
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_ELEMN_CONFG_FK1;
CREATE INDEX SIE_25_VALR_ELEMN_CONFG_FK1 ON SIE_25_VALR_ELEMN_CONFG
(REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_ELEMN_CONFG_FK2;
CREATE INDEX SIE_25_VALR_ELEMN_CONFG_FK2 ON SIE_25_VALR_ELEMN_CONFG
(REF_ELEMN_CONFG_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_ELEMN_CONFG_PK;
CREATE UNIQUE INDEX SIE_25_VALR_ELEMN_CONFG_PK ON SIE_25_VALR_ELEMN_CONFG
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VALR_ELEMN_CONFG_UK1;
CREATE UNIQUE INDEX SIE_25_VALR_ELEMN_CONFG_UK1 ON SIE_25_VALR_ELEMN_CONFG
(REF_ELEMN_CONFG_PUBLC, REF_DOMN)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VERSN_PUBLC_FK1;
CREATE INDEX SIE_25_VERSN_PUBLC_FK1 ON SIE_25_VERSN_PUBLC
(REF_PUBLC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VERSN_PUBLC_PK;
CREATE UNIQUE INDEX SIE_25_VERSN_PUBLC_PK ON SIE_25_VERSN_PUBLC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_25_VERSN_PUBLC_UK1;
CREATE UNIQUE INDEX SIE_25_VERSN_PUBLC_UK1 ON SIE_25_VERSN_PUBLC
(CODE, DNR_REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_29_CONTR_FK50;
CREATE INDEX SIE_29_CONTR_FK50 ON SIE_29_CONTR
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_29_CONTR_PK;
CREATE UNIQUE INDEX SIE_29_CONTR_PK ON SIE_29_CONTR
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_AFECT_ITEM_FK2;
CREATE INDEX SIE_30_AFECT_ITEM_FK2 ON SIE_30_AFECT_ITEM
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_AFECT_ITEM_PK;
CREATE UNIQUE INDEX SIE_30_AFECT_ITEM_PK ON SIE_30_AFECT_ITEM
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_AFECT_ITEM_UK1;
CREATE UNIQUE INDEX SIE_30_AFECT_ITEM_UK1 ON SIE_30_AFECT_ITEM
(REF_ITEM_CARNT_PRODT, REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_PRODT_FK1;
CREATE INDEX SIE_30_CARNT_PRODT_FK1 ON SIE_30_CARNT_APLIC
(REF_CARNT_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_PRODT_FK3;
CREATE INDEX SIE_30_CARNT_PRODT_FK3 ON SIE_30_CARNT_APLIC
(REF_UTILS_RESPN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_PRODT_PK;
CREATE UNIQUE INDEX SIE_30_CARNT_PRODT_PK ON SIE_30_CARNT_APLIC
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_PRODT_UK1;
CREATE UNIQUE INDEX SIE_30_CARNT_PRODT_UK1 ON SIE_30_CARNT_APLIC
(REF_APLIC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SPRIN_FK1;
CREATE INDEX SIE_30_CARNT_SPRIN_FK1 ON SIE_30_CARNT_SPRIN
(REF_CARNT_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SPRIN_FK2;
CREATE INDEX SIE_30_CARNT_SPRIN_FK2 ON SIE_30_CARNT_SPRIN
(REF_UTILS_RESPN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SPRIN_PK;
CREATE UNIQUE INDEX SIE_30_CARNT_SPRIN_PK ON SIE_30_CARNT_SPRIN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SPRIN_UK1;
CREATE UNIQUE INDEX SIE_30_CARNT_SPRIN_UK1 ON SIE_30_CARNT_SPRIN
(REF_VERSN, DATE_FIN_PREVU, DATE_DEBUT_PREVU, REF_CARNT_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SYSTM_FK2;
CREATE INDEX SIE_30_CARNT_SYSTM_FK2 ON SIE_30_CARNT_PRODT
(REF_UTILS_RESPN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SYSTM_PK;
CREATE UNIQUE INDEX SIE_30_CARNT_SYSTM_PK ON SIE_30_CARNT_PRODT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CARNT_SYSTM_UK1;
CREATE UNIQUE INDEX SIE_30_CARNT_SYSTM_UK1 ON SIE_30_CARNT_PRODT
(REF_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CAS_UTILS_FK2;
CREATE INDEX SIE_30_CAS_UTILS_FK2 ON SIE_30_CAS_UTILS
(REF_STAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CAS_UTILS_FK3;
CREATE INDEX SIE_30_CAS_UTILS_FK3 ON SIE_30_CAS_UTILS
(REF_UTILS_RESPN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CAS_UTILS_PK;
CREATE UNIQUE INDEX SIE_30_CAS_UTILS_PK ON SIE_30_CAS_UTILS
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CAS_UTILS_UK1;
CREATE UNIQUE INDEX SIE_30_CAS_UTILS_UK1 ON SIE_30_CAS_UTILS
(REF_CARNT_PRODT, CODE)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_CAS_UTILS_UK2;
CREATE UNIQUE INDEX SIE_30_CAS_UTILS_UK2 ON SIE_30_CAS_UTILS
(REF_CARNT_PRODT, NOM)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_EFORT_ITEM_FK1;
CREATE INDEX SIE_30_EFORT_ITEM_FK1 ON SIE_30_EFORT_ITEM
(REF_ITEM_CARNT_SPRIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_EFORT_ITEM_FK2;
CREATE INDEX SIE_30_EFORT_ITEM_FK2 ON SIE_30_EFORT_ITEM
(REF_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_EFORT_ITEM_PK;
CREATE UNIQUE INDEX SIE_30_EFORT_ITEM_PK ON SIE_30_EFORT_ITEM
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_EFORT_ITEM_UK1;
CREATE UNIQUE INDEX SIE_30_EFORT_ITEM_UK1 ON SIE_30_EFORT_ITEM
(DATE_EFORT, REF_UTILS, REF_ITEM_CARNT_SPRIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_HISTR_EFORT_RESTN_FK1;
CREATE INDEX SIE_30_HISTR_EFORT_RESTN_FK1 ON SIE_30_HISTR_EFORT_RESTN
(REF_ITEM_CARNT_SPRIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_HISTR_EFORT_RESTN_PK;
CREATE UNIQUE INDEX SIE_30_HISTR_EFORT_RESTN_PK ON SIE_30_HISTR_EFORT_RESTN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_HISTR_EFORT_RESTN_UK1;
CREATE UNIQUE INDEX SIE_30_HISTR_EFORT_RESTN_UK1 ON SIE_30_HISTR_EFORT_RESTN
(DATE_HEURE_SAISI, REF_ITEM_CARNT_SPRIN)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_PRODT_FK2;
CREATE INDEX SIE_30_ITEM_CARNT_PRODT_FK2 ON SIE_30_ITEM_CARNT_PRODT
(REF_CAS_UTILS)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_PRODT_FK3;
CREATE INDEX SIE_30_ITEM_CARNT_PRODT_FK3 ON SIE_30_ITEM_CARNT_PRODT
(REF_DV_TAIL_RELTV)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_PRODT_FK4;
CREATE INDEX SIE_30_ITEM_CARNT_PRODT_FK4 ON SIE_30_ITEM_CARNT_PRODT
(REF_DV_PRIOR)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_PRODT_FK5;
CREATE INDEX SIE_30_ITEM_CARNT_PRODT_FK5 ON SIE_30_ITEM_CARNT_PRODT
(REF_STAT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_PRODT_PK;
CREATE UNIQUE INDEX SIE_30_ITEM_CARNT_PRODT_PK ON SIE_30_ITEM_CARNT_PRODT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_PRODT_UK1;
CREATE UNIQUE INDEX SIE_30_ITEM_CARNT_PRODT_UK1 ON SIE_30_ITEM_CARNT_PRODT
(REF_CARNT_PRODT, NOM)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_SPRIN_FK2;
CREATE INDEX SIE_30_ITEM_CARNT_SPRIN_FK2 ON SIE_30_ITEM_CARNT_SPRIN
(REF_ITEM_CARNT_PRODT)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_SPRIN_FK3;
CREATE INDEX SIE_30_ITEM_CARNT_SPRIN_FK3 ON SIE_30_ITEM_CARNT_SPRIN
(REF_SIE_30_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_SPRIN_PK;
CREATE UNIQUE INDEX SIE_30_ITEM_CARNT_SPRIN_PK ON SIE_30_ITEM_CARNT_SPRIN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_ITEM_CARNT_SPRIN_UK1;
CREATE UNIQUE INDEX SIE_30_ITEM_CARNT_SPRIN_UK1 ON SIE_30_ITEM_CARNT_SPRIN
(REF_CARNT_SPRIN, NOM)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_PAGE_ITEM_FK1;
CREATE INDEX SIE_30_PAGE_ITEM_FK1 ON SIE_30_PAGE_ITEM
(REF_SIE_30_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_PAGE_ITEM_PK;
CREATE UNIQUE INDEX SIE_30_PAGE_ITEM_PK ON SIE_30_PAGE_ITEM
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_PAGE_ITEM_UK1;
CREATE UNIQUE INDEX SIE_30_PAGE_ITEM_UK1 ON SIE_30_PAGE_ITEM
(REF_ITEM_CARNT_PRODT, REF_SIE_30_PAGE)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_PAGE_PK;
CREATE UNIQUE INDEX SIE_30_PAGE_PK ON SIE_30_PAGE
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index SIE_30_PAGE_UK1;
CREATE UNIQUE INDEX SIE_30_PAGE_UK1 ON SIE_30_PAGE
(REF_SIE_13_PAGE)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_deplm_pk";
CREATE UNIQUE INDEX "sie_20_deplm_pk" ON SIE_20_DEPLM
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_detl_docmn_pk";
CREATE UNIQUE INDEX "sie_20_detl_docmn_pk" ON SIE_20_DETL_DOCMN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_docmn_pk";
CREATE UNIQUE INDEX "sie_20_docmn_pk" ON SIE_20_DOCMN
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_modl_excep_pk";
CREATE UNIQUE INDEX "sie_20_modl_excep_pk" ON SIE_20_MODL_EXCEP
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_modl_parmt_pk";
CREATE UNIQUE INDEX "sie_20_modl_parmt_pk" ON SIE_20_MODL_PARMT
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_modl_pk";
CREATE UNIQUE INDEX "sie_20_modl_pk" ON SIE_20_MODL
(SEQNC)
LOGGING
NOPARALLEL;


Prompt Index "sie_20_sectn_docmn_pk";
CREATE UNIQUE INDEX "sie_20_sectn_docmn_pk" ON SIE_20_SECTN_DOCMN
(SEQNC)
LOGGING
NOPARALLEL;
