--Executer en tant que SYS
set define on
set verify off
set feedback off
whenever sqlerror exit sql.sqlcode rollback

prompt
prompt ...Doit etre connecte en tant que SYS
prompt

declare
  vva_schem_conct 			varchar2(30);
  kva_schem_afw_exist		varchar2(30) default 'SYS';
  vnu_exist					number;
  vnu_afw_exist				pls_integer;
begin
  select username into vva_schem_conct from user_users where rownum = 1; 
  
  select 1 into vnu_afw_exist from dual where vva_schem_conct = kva_schem_afw_exist;
end;
/

acc schem char prompt 'Schema a installer synonym AFW_040215:   '

Prompt Synonym VS_STAT_PUBLC_TRAVL;
CREATE OR REPLACE SYNONYM &schem.VS_STAT_PUBLC_TRAVL FOR afw_040215.VS_STAT_PUBLC_TRAVL;


Prompt Synonym VS_SIE_25_PAR_PUB_TRA_EXECT;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_25_PAR_PUB_TRA_EXECT FOR afw_040215.VS_SIE_25_PAR_PUB_TRA_EXECT;


Prompt Synonym VS_SIE_14_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_14_DOMN_VALR FOR afw_040215.VS_SIE_14_DOMN_VALR;


Prompt Synonym VS_SIE_13_PAGE;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_13_PAGE FOR afw_040215.VS_SIE_13_PAGE;


Prompt Synonym VS_SIE_07_CONDT_APEX;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_07_CONDT_APEX FOR afw_040215.VS_SIE_07_CONDT_APEX;


Prompt Synonym VS_SIE_01_TABLE;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_01_TABLE FOR afw_040215.VS_SIE_01_TABLE;


Prompt Synonym VS_SIE_01_CONTR;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_01_CONTR FOR afw_040215.VS_SIE_01_CONTR;


Prompt Synonym VS_SIE_01_COLN_TABLE;
CREATE OR REPLACE SYNONYM &schem.VS_SIE_01_COLN_TABLE FOR afw_040215.VS_SIE_01_COLN_TABLE;


Prompt Synonym VS_GROUP_LIE_UTILS_CONCT;
CREATE OR REPLACE SYNONYM &schem.VS_GROUP_LIE_UTILS_CONCT FOR afw_040215.VS_GROUP_LIE_UTILS_CONCT;


Prompt Synonym VD_SIE_25_TYPE_TRAVL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_TYPE_TRAVL FOR afw_040215.VD_SIE_25_TYPE_TRAVL;


Prompt Synonym VD_SIE_25_TYPE_PUBLC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_TYPE_PUBLC FOR afw_040215.VD_SIE_25_TYPE_PUBLC;


Prompt Synonym VD_SIE_25_TRAVL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_TRAVL FOR afw_040215.VD_SIE_25_TRAVL;


Prompt Synonym VD_SIE_25_PUBLC_TRAVL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_PUBLC_TRAVL FOR afw_040215.VD_SIE_25_PUBLC_TRAVL;


Prompt Synonym VD_SIE_25_PUBLC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_PUBLC FOR afw_040215.VD_SIE_25_PUBLC;


Prompt Synonym VD_SIE_25_PARMT_PUBLC_TRAVL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_PARMT_PUBLC_TRAVL FOR afw_040215.VD_SIE_25_PARMT_PUBLC_TRAVL;


Prompt Synonym VD_SIE_25_OCURN_PARMT_PUBLC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_OCURN_PARMT_PUBLC FOR afw_040215.VD_SIE_25_OCURN_PARMT_PUBLC;


Prompt Synonym VD_SIE_25_DOMN_TYPE_PUBLC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_25_DOMN_TYPE_PUBLC FOR afw_040215.VD_SIE_25_DOMN_TYPE_PUBLC;


Prompt Synonym VD_SIE_23_SOMR_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_SOMR_RECHR FOR afw_040215.VD_SIE_23_SOMR_RECHR;


Prompt Synonym VD_SIE_23_RESLT_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_RESLT_RECHR FOR afw_040215.VD_SIE_23_RESLT_RECHR;


Prompt Synonym VD_SIE_23_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_RECHR FOR afw_040215.VD_SIE_23_RECHR;


Prompt Synonym VD_SIE_23_PATRN_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_PATRN_RECHR FOR afw_040215.VD_SIE_23_PATRN_RECHR;


Prompt Synonym VD_SIE_23_MODL_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_MODL_RECHR FOR afw_040215.VD_SIE_23_MODL_RECHR;


Prompt Synonym VD_SIE_23_ENONC_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_ENONC_RECHR FOR afw_040215.VD_SIE_23_ENONC_RECHR;


Prompt Synonym VD_SIE_23_DETL_RESLT_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_DETL_RESLT_RECHR FOR afw_040215.VD_SIE_23_DETL_RESLT_RECHR;


Prompt Synonym VD_SIE_23_DETL_APLIC_MODL_RE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_DETL_APLIC_MODL_RE FOR afw_040215.VD_SIE_23_DETL_APLIC_MODL_RE;


Prompt Synonym VD_SIE_23_APLIC_MODL_RECHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_23_APLIC_MODL_RECHR FOR afw_040215.VD_SIE_23_APLIC_MODL_RECHR;


Prompt Synonym VD_SIE_21_PLUGN_MENU;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_MENU FOR afw_040215.VD_SIE_21_PLUGN_MENU;


Prompt Synonym VD_SIE_21_PLUGN_ITEM_MENU;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_ITEM_MENU FOR afw_040215.VD_SIE_21_PLUGN_ITEM_MENU;


Prompt Synonym VD_SIE_21_PLUGN_CALND_TYPE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_CALND_TYPE FOR afw_040215.VD_SIE_21_PLUGN_CALND_TYPE;


Prompt Synonym VD_SIE_21_PLUGN_CALND_COULR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_CALND_COULR FOR afw_040215.VD_SIE_21_PLUGN_CALND_COULR;


Prompt Synonym VD_SIE_21_PLUGN_CALND;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_CALND FOR afw_040215.VD_SIE_21_PLUGN_CALND;


Prompt Synonym VD_SIE_21_PLUGN_ARBRE_NOEUD;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_ARBRE_NOEUD FOR afw_040215.VD_SIE_21_PLUGN_ARBRE_NOEUD;


Prompt Synonym VD_SIE_21_PLUGN_ARBRE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_21_PLUGN_ARBRE FOR afw_040215.VD_SIE_21_PLUGN_ARBRE;


Prompt Synonym VD_SIE_20_RSS_ITEM;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_20_RSS_ITEM FOR afw_040215.VD_SIE_20_RSS_ITEM;


Prompt Synonym VD_SIE_20_RSS_CHANL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_20_RSS_CHANL FOR afw_040215.VD_SIE_20_RSS_CHANL;


Prompt Synonym VD_SIE_19_SPECF_FONCT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_19_SPECF_FONCT FOR afw_040215.VD_SIE_19_SPECF_FONCT;


Prompt Synonym VD_SIE_19_FONCT_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_19_FONCT_LANG FOR afw_040215.VD_SIE_19_FONCT_LANG;


Prompt Synonym VD_SIE_19_FONCT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_19_FONCT FOR afw_040215.VD_SIE_19_FONCT;


Prompt Synonym VD_SIE_19_DISPN_FONCT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_19_DISPN_FONCT FOR afw_040215.VD_SIE_19_DISPN_FONCT;


Prompt Synonym VD_SIE_19_CLE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_19_CLE FOR afw_040215.VD_SIE_19_CLE;


Prompt Synonym VD_SIE_19_BOUTN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_19_BOUTN FOR afw_040215.VD_SIE_19_BOUTN;


Prompt Synonym VD_SIE_17_TELCP_AXIAT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_TELCP_AXIAT FOR afw_040215.VD_SIE_17_TELCP_AXIAT;


Prompt Synonym VD_SIE_17_SMS_TWILI;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_SMS_TWILI FOR afw_040215.VD_SIE_17_SMS_TWILI;


Prompt Synonym VD_SIE_17_PROFL_COURL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_PROFL_COURL FOR afw_040215.VD_SIE_17_PROFL_COURL;


Prompt Synonym VD_SIE_17_COURL_DESTN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_COURL_DESTN FOR afw_040215.VD_SIE_17_COURL_DESTN;


Prompt Synonym VD_SIE_17_COURL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_COURL FOR afw_040215.VD_SIE_17_COURL;


Prompt Synonym VD_SIE_17_COMPT_TWILI;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_COMPT_TWILI FOR afw_040215.VD_SIE_17_COMPT_TWILI;


Prompt Synonym VD_SIE_17_COMPT_AXIAT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_17_COMPT_AXIAT FOR afw_040215.VD_SIE_17_COMPT_AXIAT;


Prompt Synonym VD_SIE_14_TYPE_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_TYPE_DOMN_VALR FOR afw_040215.VD_SIE_14_TYPE_DOMN_VALR;


Prompt Synonym VD_SIE_14_POPUP_LOV_IR_RETR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_POPUP_LOV_IR_RETR FOR afw_040215.VD_SIE_14_POPUP_LOV_IR_RETR;


Prompt Synonym VD_SIE_14_POPUP_LOV_IR_FILTR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_POPUP_LOV_IR_FILTR FOR afw_040215.VD_SIE_14_POPUP_LOV_IR_FILTR;


Prompt Synonym VD_SIE_14_POPUP_LOV_IR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_POPUP_LOV_IR FOR afw_040215.VD_SIE_14_POPUP_LOV_IR;


Prompt Synonym VD_SIE_14_FORMT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_FORMT FOR afw_040215.VD_SIE_14_FORMT;


Prompt Synonym VD_SIE_14_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_DOMN_VALR FOR afw_040215.VD_SIE_14_DOMN_VALR;


Prompt Synonym VD_SIE_14_DETL_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_14_DETL_DOMN_VALR FOR afw_040215.VD_SIE_14_DETL_DOMN_VALR;


Prompt Synonym VD_SIE_13_TYPE_FICHR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_TYPE_FICHR FOR afw_040215.VD_SIE_13_TYPE_FICHR;


Prompt Synonym VD_SIE_13_RESRC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_RESRC FOR afw_040215.VD_SIE_13_RESRC;


Prompt Synonym VD_SIE_13_REGN_PILTB_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_REGN_PILTB_LANG FOR afw_040215.VD_SIE_13_REGN_PILTB_LANG;


Prompt Synonym VD_SIE_13_REGN_PILTB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_REGN_PILTB FOR afw_040215.VD_SIE_13_REGN_PILTB;


Prompt Synonym VD_SIE_13_PREFR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PREFR FOR afw_040215.VD_SIE_13_PREFR;


Prompt Synonym VD_SIE_13_PAGE_REGN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE_REGN FOR afw_040215.VD_SIE_13_PAGE_REGN;


Prompt Synonym VD_SIE_13_PAGE_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE_LANG FOR afw_040215.VD_SIE_13_PAGE_LANG;


Prompt Synonym VD_SIE_13_PAGE_ITEM_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE_ITEM_LANG FOR afw_040215.VD_SIE_13_PAGE_ITEM_LANG;


Prompt Synonym VD_SIE_13_PAGE_ITEM;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE_ITEM FOR afw_040215.VD_SIE_13_PAGE_ITEM;


Prompt Synonym VD_SIE_13_PAGE_IR_COLN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE_IR_COLN FOR afw_040215.VD_SIE_13_PAGE_IR_COLN;


Prompt Synonym VD_SIE_13_PAGE_IR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE_IR FOR afw_040215.VD_SIE_13_PAGE_IR;


Prompt Synonym VD_SIE_13_PAGE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_PAGE FOR afw_040215.VD_SIE_13_PAGE;


Prompt Synonym VD_SIE_13_OPERT_OPTIO;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_OPERT_OPTIO FOR afw_040215.VD_SIE_13_OPERT_OPTIO;


Prompt Synonym VD_SIE_13_OPERT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_OPERT FOR afw_040215.VD_SIE_13_OPERT;


Prompt Synonym VD_SIE_13_OCURN_RESRC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_OCURN_RESRC FOR afw_040215.VD_SIE_13_OCURN_RESRC;


Prompt Synonym VD_SIE_13_NAVGT_ELEMN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_NAVGT_ELEMN FOR afw_040215.VD_SIE_13_NAVGT_ELEMN;


Prompt Synonym VD_SIE_13_NAVGT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_NAVGT FOR afw_040215.VD_SIE_13_NAVGT;


Prompt Synonym VD_SIE_13_MIME_TYPE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_MIME_TYPE FOR afw_040215.VD_SIE_13_MIME_TYPE;


Prompt Synonym VD_SIE_13_MENU;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_MENU FOR afw_040215.VD_SIE_13_MENU;


Prompt Synonym VD_SIE_13_LISTE_NAVGT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_LISTE_NAVGT FOR afw_040215.VD_SIE_13_LISTE_NAVGT;


Prompt Synonym VD_SIE_13_LIEN_GROUP_PAGE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_LIEN_GROUP_PAGE FOR afw_040215.VD_SIE_13_LIEN_GROUP_PAGE;


Prompt Synonym VD_SIE_13_LIEN_GROUP_OPERT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_LIEN_GROUP_OPERT FOR afw_040215.VD_SIE_13_LIEN_GROUP_OPERT;


Prompt Synonym VD_SIE_13_LIEN_CONDT_PILTB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_LIEN_CONDT_PILTB FOR afw_040215.VD_SIE_13_LIEN_CONDT_PILTB;


Prompt Synonym VD_SIE_13_ITEM_MENU;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_ITEM_MENU FOR afw_040215.VD_SIE_13_ITEM_MENU;


Prompt Synonym VD_SIE_13_INSTA_PREFR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_INSTA_PREFR FOR afw_040215.VD_SIE_13_INSTA_PREFR;


Prompt Synonym VD_SIE_13_GROUP_PAGE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_GROUP_PAGE FOR afw_040215.VD_SIE_13_GROUP_PAGE;


Prompt Synonym VD_SIE_13_GROUP_OPERT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_GROUP_OPERT FOR afw_040215.VD_SIE_13_GROUP_OPERT;


Prompt Synonym VD_SIE_13_FORMT_RESRC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_FORMT_RESRC FOR afw_040215.VD_SIE_13_FORMT_RESRC;


Prompt Synonym VD_SIE_13_EXPOR_PAGE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_EXPOR_PAGE FOR afw_040215.VD_SIE_13_EXPOR_PAGE;


Prompt Synonym VD_SIE_13_EMPLA_DOSR_VIRTL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_EMPLA_DOSR_VIRTL FOR afw_040215.VD_SIE_13_EMPLA_DOSR_VIRTL;


Prompt Synonym VD_SIE_13_CONDT_PILTB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_13_CONDT_PILTB FOR afw_040215.VD_SIE_13_CONDT_PILTB;


Prompt Synonym VD_SIE_12_UTILS;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_UTILS FOR afw_040215.VD_SIE_12_UTILS;


Prompt Synonym VD_SIE_12_TYPE_STRUC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_TYPE_STRUC FOR afw_040215.VD_SIE_12_TYPE_STRUC;


Prompt Synonym VD_SIE_12_STRUC_APLIC_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_STRUC_APLIC_LANG FOR afw_040215.VD_SIE_12_STRUC_APLIC_LANG;


Prompt Synonym VD_SIE_12_STRUC_APLIC_DESTN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_STRUC_APLIC_DESTN FOR afw_040215.VD_SIE_12_STRUC_APLIC_DESTN;


Prompt Synonym VD_SIE_12_STRUC_APLIC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_STRUC_APLIC FOR afw_040215.VD_SIE_12_STRUC_APLIC;


Prompt Synonym VD_SIE_12_STRUC_ADMIN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_STRUC_ADMIN FOR afw_040215.VD_SIE_12_STRUC_ADMIN;


Prompt Synonym VD_SIE_12_STAT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_STAT FOR afw_040215.VD_SIE_12_STAT;


Prompt Synonym VD_SIE_12_SESN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_SESN FOR afw_040215.VD_SIE_12_SESN;


Prompt Synonym VD_SIE_12_REQT_INTER_UTILS;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_REQT_INTER_UTILS FOR afw_040215.VD_SIE_12_REQT_INTER_UTILS;


Prompt Synonym VD_SIE_12_MEMBR_STRUC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_MEMBR_STRUC FOR afw_040215.VD_SIE_12_MEMBR_STRUC;


Prompt Synonym VD_SIE_12_LIEN_STRUC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_LIEN_STRUC FOR afw_040215.VD_SIE_12_LIEN_STRUC;


Prompt Synonym VD_SIE_12_LIEN_GROUP_UTILS;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_LIEN_GROUP_UTILS FOR afw_040215.VD_SIE_12_LIEN_GROUP_UTILS;


Prompt Synonym VD_SIE_12_HISTR_ACCES;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_HISTR_ACCES FOR afw_040215.VD_SIE_12_HISTR_ACCES;


Prompt Synonym VD_SIE_12_GR_UT_OPERT_OPT_DOM;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_GR_UT_OPERT_OPT_DOM FOR afw_040215.VD_SIE_12_GR_UT_OPERT_OPT_DOM;


Prompt Synonym VD_SIE_12_GROUP_UTILS;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_GROUP_UTILS FOR afw_040215.VD_SIE_12_GROUP_UTILS;


Prompt Synonym VD_SIE_12_GROUP_STAT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_GROUP_STAT FOR afw_040215.VD_SIE_12_GROUP_STAT;


Prompt Synonym VD_SIE_12_FAVR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_FAVR FOR afw_040215.VD_SIE_12_FAVR;


Prompt Synonym VD_SIE_12_EVOLT_STAT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_EVOLT_STAT FOR afw_040215.VD_SIE_12_EVOLT_STAT;


Prompt Synonym VD_SIE_12_DOMN_UTILS;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_DOMN_UTILS FOR afw_040215.VD_SIE_12_DOMN_UTILS;


Prompt Synonym VD_SIE_12_DOMN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_DOMN FOR afw_040215.VD_SIE_12_DOMN;


Prompt Synonym VD_SIE_12_DEFNT_ACCES;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_DEFNT_ACCES FOR afw_040215.VD_SIE_12_DEFNT_ACCES;


Prompt Synonym VD_SIE_12_ATRIB_STRUC_APLIC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_ATRIB_STRUC_APLIC FOR afw_040215.VD_SIE_12_ATRIB_STRUC_APLIC;


Prompt Synonym VD_SIE_12_ARBRE_NOEUD;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_ARBRE_NOEUD FOR afw_040215.VD_SIE_12_ARBRE_NOEUD;


Prompt Synonym VD_SIE_12_ARBRE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_12_ARBRE FOR afw_040215.VD_SIE_12_ARBRE;


Prompt Synonym VD_SIE_11_UTILS;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_11_UTILS FOR afw_040215.VD_SIE_11_UTILS;


Prompt Synonym VD_SIE_11_SYSTM;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_11_SYSTM FOR afw_040215.VD_SIE_11_SYSTM;


Prompt Synonym VD_SIE_11_PRODT_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_11_PRODT_LANG FOR afw_040215.VD_SIE_11_PRODT_LANG;


Prompt Synonym VD_SIE_11_PRODT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_11_PRODT FOR afw_040215.VD_SIE_11_PRODT;


Prompt Synonym VD_SIE_11_APLIC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_11_APLIC FOR afw_040215.VD_SIE_11_APLIC;


Prompt Synonym VD_SIE_04_TYPE_CONTX;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_04_TYPE_CONTX FOR afw_040215.VD_SIE_04_TYPE_CONTX;


Prompt Synonym VD_SIE_04_FIL_ARIAN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_04_FIL_ARIAN FOR afw_040215.VD_SIE_04_FIL_ARIAN;


Prompt Synonym VD_SIE_04_CONTX_ETEND;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_04_CONTX_ETEND FOR afw_040215.VD_SIE_04_CONTX_ETEND;


Prompt Synonym VD_SIE_04_CONTX;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_04_CONTX FOR afw_040215.VD_SIE_04_CONTX;


Prompt Synonym VD_SIE_04_ARBRE_NOEUD;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_04_ARBRE_NOEUD FOR afw_040215.VD_SIE_04_ARBRE_NOEUD;


Prompt Synonym VD_SIE_04_ARBRE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_04_ARBRE FOR afw_040215.VD_SIE_04_ARBRE;


Prompt Synonym VD_SIE_03_JOURN_STRUC_APLIC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_03_JOURN_STRUC_APLIC FOR afw_040215.VD_SIE_03_JOURN_STRUC_APLIC;


Prompt Synonym VD_SIE_03_JOURN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_03_JOURN FOR afw_040215.VD_SIE_03_JOURN;


Prompt Synonym VD_SIE_01_TYPE_COMNC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_TYPE_COMNC FOR afw_040215.VD_SIE_01_TYPE_COMNC;


Prompt Synonym VD_SIE_01_RESLT_DESTN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_RESLT_DESTN FOR afw_040215.VD_SIE_01_RESLT_DESTN;


Prompt Synonym VD_SIE_01_OSA_EVENM_NOTFB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_OSA_EVENM_NOTFB FOR afw_040215.VD_SIE_01_OSA_EVENM_NOTFB;


Prompt Synonym VD_SIE_01_NOTFC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_NOTFC FOR afw_040215.VD_SIE_01_NOTFC;


Prompt Synonym VD_SIE_01_MODL_MESG_NOTFC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MODL_MESG_NOTFC FOR afw_040215.VD_SIE_01_MODL_MESG_NOTFC;


Prompt Synonym VD_SIE_01_MODL_COMNC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MODL_COMNC FOR afw_040215.VD_SIE_01_MODL_COMNC;


Prompt Synonym VD_SIE_01_MODL_AFICH_NOTFC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MODL_AFICH_NOTFC FOR afw_040215.VD_SIE_01_MODL_AFICH_NOTFC;


Prompt Synonym VD_SIE_01_MESG_TRADC_APEX;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MESG_TRADC_APEX FOR afw_040215.VD_SIE_01_MESG_TRADC_APEX;


Prompt Synonym VD_SIE_01_MESG_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MESG_LANG FOR afw_040215.VD_SIE_01_MESG_LANG;


Prompt Synonym VD_SIE_01_MESG_INFOR;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MESG_INFOR FOR afw_040215.VD_SIE_01_MESG_INFOR;


Prompt Synonym VD_SIE_01_MESG_ERR_LIE;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MESG_ERR_LIE FOR afw_040215.VD_SIE_01_MESG_ERR_LIE;


Prompt Synonym VD_SIE_01_MESG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_MESG FOR afw_040215.VD_SIE_01_MESG;


Prompt Synonym VD_SIE_01_LIEN_EVENM_NOTFB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_LIEN_EVENM_NOTFB FOR afw_040215.VD_SIE_01_LIEN_EVENM_NOTFB;


Prompt Synonym VD_SIE_01_LANG_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_LANG_LANG FOR afw_040215.VD_SIE_01_LANG_LANG;


Prompt Synonym VD_SIE_01_LANG;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_LANG FOR afw_040215.VD_SIE_01_LANG;


Prompt Synonym VD_SIE_01_HIERC_APLIC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_HIERC_APLIC FOR afw_040215.VD_SIE_01_HIERC_APLIC;


Prompt Synonym VD_SIE_01_EVENM_NOTFB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_EVENM_NOTFB FOR afw_040215.VD_SIE_01_EVENM_NOTFB;


Prompt Synonym VD_SIE_01_ELEMN_CONFG_EN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_ELEMN_CONFG_EN FOR afw_040215.VD_SIE_01_ELEMN_CONFG_EN;


Prompt Synonym VD_SIE_01_DESTN_CONFG_EN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_DESTN_CONFG_EN FOR afw_040215.VD_SIE_01_DESTN_CONFG_EN;


Prompt Synonym VD_SIE_01_DESTN;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_DESTN FOR afw_040215.VD_SIE_01_DESTN;


Prompt Synonym VD_SIE_01_CONFG_EVENM_NOTFB;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_CONFG_EVENM_NOTFB FOR afw_040215.VD_SIE_01_CONFG_EVENM_NOTFB;


Prompt Synonym VD_SIE_01_CODE_ERR_ORCL;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_CODE_ERR_ORCL FOR afw_040215.VD_SIE_01_CODE_ERR_ORCL;


Prompt Synonym VD_SIE_01_ATRIB_MODL_COMNC;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_01_ATRIB_MODL_COMNC FOR afw_040215.VD_SIE_01_ATRIB_MODL_COMNC;


Prompt Synonym VD_SIE_00_REPRT;
CREATE OR REPLACE SYNONYM &schem.VD_SIE_00_REPRT FOR afw_040215.VD_SIE_00_REPRT;


Prompt Synonym VDF_SIE_12_MEMBR_STRUC;
CREATE OR REPLACE SYNONYM &schem.VDF_SIE_12_MEMBR_STRUC FOR afw_040215.VDF_SIE_12_MEMBR_STRUC;


Prompt Synonym TC_SIE_26_LONG_TEXT;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_26_LONG_TEXT FOR afw_040215.TC_SIE_26_LONG_TEXT;


Prompt Synonym TC_SIE_25_PARMT_PUBLC_TRAVL;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_25_PARMT_PUBLC_TRAVL FOR afw_040215.TS_SIE_25_PARMT_PUBLC_TRAVL;


Prompt Synonym TC_SIE_14_TYPE_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_14_TYPE_DOMN_VALR FOR afw_040215.TC_SIE_14_TYPE_DOMN_VALR;


Prompt Synonym TC_SIE_14_FORMT;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_14_FORMT FOR afw_040215.TC_SIE_14_FORMT;


Prompt Synonym TC_SIE_14_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_14_DOMN_VALR FOR afw_040215.TC_SIE_14_DOMN_VALR;


Prompt Synonym TC_SIE_14_DETL_DOMN_VALR;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_14_DETL_DOMN_VALR FOR afw_040215.TC_SIE_14_DETL_DOMN_VALR;


Prompt Synonym TC_SIE_13_INSTA_PREFR;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_13_INSTA_PREFR FOR afw_040215.TC_SIE_13_INSTA_PREFR;


Prompt Synonym TC_SIE_13_EXPOR_PAGE_CORSP;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_13_EXPOR_PAGE_CORSP FOR afw_040215.TC_SIE_13_EXPOR_PAGE_CORSP;


Prompt Synonym TC_SIE_13_EXPOR_PAGE_APP;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_13_EXPOR_PAGE_APP FOR afw_040215.TC_SIE_13_EXPOR_PAGE_APP;


Prompt Synonym TC_SIE_13_EXPOR_PAGE;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_13_EXPOR_PAGE FOR afw_040215.TC_SIE_13_EXPOR_PAGE;


Prompt Synonym TC_SIE_12_STAT;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_12_STAT FOR afw_040215.TC_SIE_12_STAT;


Prompt Synonym TC_SIE_12_GROUP_UTILS;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_12_GROUP_UTILS FOR afw_040215.TC_SIE_12_GROUP_UTILS;


Prompt Synonym TC_SIE_12_EVOLT_STAT;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_12_EVOLT_STAT FOR afw_040215.TC_SIE_12_EVOLT_STAT;


Prompt Synonym TC_SIE_12_DEFNT_ACCES;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_12_DEFNT_ACCES FOR afw_040215.TC_SIE_12_DEFNT_ACCES;


Prompt Synonym TC_SIE_07_SEQNC;
CREATE OR REPLACE SYNONYM &schem.TC_SIE_07_SEQNC FOR afw_040215.TC_SIE_07_SEQNC;


Prompt Synonym SIE_25_TYPE_PUBLC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_TYPE_PUBLC_PKG FOR afw_040215.SIE_25_TYPE_PUBLC_PKG;


Prompt Synonym SIE_25_TRI_ALTER_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_TRI_ALTER_PKG FOR afw_040215.SIE_25_TRI_ALTER_PKG;


Prompt Synonym SIE_25_TRAVL_PUBLC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_TRAVL_PUBLC_PKG FOR afw_040215.SIE_25_TRAVL_PUBLC_PKG;


Prompt Synonym SIE_25_RAPRT_INTER_EXPOR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_RAPRT_INTER_EXPOR_PKG FOR afw_040215.SIE_25_RAPRT_INTER_EXPOR_PKG;


Prompt Synonym SIE_25_PUBLC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_PUBLC_PKG FOR afw_040215.SIE_25_PUBLC_PKG;


Prompt Synonym SIE_25_PUBLC_NOYAU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_PUBLC_NOYAU_PKG FOR afw_040215.SIE_25_PUBLC_NOYAU_PKG;


Prompt Synonym SIE_25_PUBLC_IMEDT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_PUBLC_IMEDT_PKG FOR afw_040215.SIE_25_PUBLC_IMEDT_PKG;


Prompt Synonym SIE_25_PLPDF_EXPOR_IR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_PLPDF_EXPOR_IR_PKG FOR afw_040215.SIE_25_PLPDF_EXPOR_IR_PKG;


Prompt Synonym SIE_25_PARMT_TYPE_PUBLC;
CREATE OR REPLACE SYNONYM &schem.SIE_25_PARMT_TYPE_PUBLC FOR afw_040215.SIE_25_PARMT_TYPE_PUBLC;


Prompt Synonym SIE_25_PARMT_PUBLC_TRAVL;
CREATE OR REPLACE SYNONYM &schem.SIE_25_PARMT_PUBLC_TRAVL FOR afw_040215.SIE_25_PARMT_PUBLC_TRAVL;


Prompt Synonym SIE_25_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_JAVSC_PKG FOR afw_040215.SIE_25_JAVSC_PKG;


Prompt Synonym SIE_25_FUSN_PDF_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_FUSN_PDF_PKG FOR afw_040215.SIE_25_FUSN_PDF_PKG;


Prompt Synonym SIE_25_DOMN_TYPE_PUBLC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_DOMN_TYPE_PUBLC_PKG FOR afw_040215.SIE_25_DOMN_TYPE_PUBLC_PKG;


Prompt Synonym SIE_25_APPEL_RAPRT_APEX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_25_APPEL_RAPRT_APEX_PKG FOR afw_040215.SIE_25_APPEL_RAPRT_APEX_PKG;


Prompt Synonym SIE_23_RECHR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_23_RECHR_PKG FOR afw_040215.SIE_23_RECHR_PKG;


Prompt Synonym SIE_23_EXECT_RECHR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_23_EXECT_RECHR_PKG FOR afw_040215.SIE_23_EXECT_RECHR_PKG;


Prompt Synonym SIE_22_GRAPH_FLASH_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_22_GRAPH_FLASH_PKG FOR afw_040215.SIE_22_GRAPH_FLASH_PKG;


Prompt Synonym SIE_21_UTIL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_UTIL_PKG FOR afw_040215.SIE_21_UTIL_PKG;


Prompt Synonym SIE_21_REGN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_REGN_PKG FOR afw_040215.SIE_21_REGN_PKG;


Prompt Synonym SIE_21_PROCS_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PROCS_PKG FOR afw_040215.SIE_21_PROCS_PKG;


Prompt Synonym SIE_21_PLUGN_MENU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_MENU_PKG FOR afw_040215.SIE_21_PLUGN_MENU_PKG;


Prompt Synonym SIE_21_PLUGN_DIALG_IFRAM_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_DIALG_IFRAM_PKG FOR afw_040215.SIE_21_PLUGN_DIALG_IFRAM_PKG;


Prompt Synonym SIE_21_PLUGN_CONFR_SAUVG_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_CONFR_SAUVG_PKG FOR afw_040215.SIE_21_PLUGN_CONFR_SAUVG_PKG;


Prompt Synonym SIE_21_PLUGN_CALND_TYPE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_CALND_TYPE_PKG FOR afw_040215.SIE_21_PLUGN_CALND_TYPE_PKG;


Prompt Synonym SIE_21_PLUGN_CALND_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_CALND_PKG FOR afw_040215.SIE_21_PLUGN_CALND_PKG;


Prompt Synonym SIE_21_PLUGN_CALND_COULR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_CALND_COULR_PKG FOR afw_040215.SIE_21_PLUGN_CALND_COULR_PKG;


Prompt Synonym SIE_21_PLUGN_BLOB_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_BLOB_PKG FOR afw_040215.SIE_21_PLUGN_BLOB_PKG;


Prompt Synonym SIE_21_PLUGN_ARBRE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_PLUGN_ARBRE_PKG FOR afw_040215.SIE_21_PLUGN_ARBRE_PKG;


Prompt Synonym SIE_21_ITEM_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_ITEM_PKG FOR afw_040215.SIE_21_ITEM_PKG;


Prompt Synonym SIE_21_AUTOR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_AUTOR_PKG FOR afw_040215.SIE_21_AUTOR_PKG;


Prompt Synonym SIE_21_AUTHE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_AUTHE_PKG FOR afw_040215.SIE_21_AUTHE_PKG;


Prompt Synonym SIE_21_ACTIO_DYNMQ_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_21_ACTIO_DYNMQ_PKG FOR afw_040215.SIE_21_ACTIO_DYNMQ_PKG;


Prompt Synonym SIE_19_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_19_JAVSC_PKG FOR afw_040215.SIE_19_JAVSC_PKG;


Prompt Synonym SIE_19_FONCT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_19_FONCT_PKG FOR afw_040215.SIE_19_FONCT_PKG;


Prompt Synonym SIE_19_CLE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_19_CLE_PKG FOR afw_040215.SIE_19_CLE_PKG;


Prompt Synonym SIE_19_BOUTN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_19_BOUTN_PKG FOR afw_040215.SIE_19_BOUTN_PKG;


Prompt Synonym SIE_18_TABLR_FORM_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_18_TABLR_FORM_PKG FOR afw_040215.SIE_18_TABLR_FORM_PKG;


Prompt Synonym SIE_18_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_18_JAVSC_PKG FOR afw_040215.SIE_18_JAVSC_PKG;


Prompt Synonym SIE_18_ITF_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_18_ITF_PKG FOR afw_040215.SIE_18_ITF_PKG;


Prompt Synonym SIE_17_TRAVL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_17_TRAVL_PKG FOR afw_040215.SIE_17_TRAVL_PKG;


Prompt Synonym SIE_17_SMS_TWILI;
CREATE OR REPLACE SYNONYM &schem.SIE_17_SMS_TWILI FOR afw_040215.SIE_17_SMS_TWILI;


Prompt Synonym SIE_17_PROFL_COURL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_17_PROFL_COURL_PKG FOR afw_040215.SIE_17_PROFL_COURL_PKG;


Prompt Synonym SIE_17_PROFL_COURL;
CREATE OR REPLACE SYNONYM &schem.SIE_17_PROFL_COURL FOR afw_040215.SIE_17_PROFL_COURL;


Prompt Synonym SIE_17_NOTFC_SMS_TWILIO_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_17_NOTFC_SMS_TWILIO_PKG FOR afw_040215.SIE_17_NOTFC_SMS_TWILIO_PKG;


Prompt Synonym SIE_17_ENVOI_TELCP_AXIAT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_17_ENVOI_TELCP_AXIAT_PKG FOR afw_040215.SIE_17_ENVOI_TELCP_AXIAT_PKG;


Prompt Synonym SIE_17_ENVOI_COURL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_17_ENVOI_COURL_PKG FOR afw_040215.SIE_17_ENVOI_COURL_PKG;


Prompt Synonym SIE_16_VUE_PARMT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_16_VUE_PARMT_PKG FOR afw_040215.SIE_16_VUE_PARMT_PKG;


Prompt Synonym SIE_16_LOV_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_16_LOV_PKG FOR afw_040215.SIE_16_LOV_PKG;


Prompt Synonym SIE_16_LOV_NOYAU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_16_LOV_NOYAU_PKG FOR afw_040215.SIE_16_LOV_NOYAU_PKG;


Prompt Synonym SIE_16_LOV_APEX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_16_LOV_APEX_PKG FOR afw_040215.SIE_16_LOV_APEX_PKG;


Prompt Synonym SIE_15_HTP_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_15_HTP_PKG FOR afw_040215.SIE_15_HTP_PKG;


Prompt Synonym SIE_15_FTP_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_15_FTP_PKG FOR afw_040215.SIE_15_FTP_PKG;


Prompt Synonym SIE_15_FTP_NOYAU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_15_FTP_NOYAU_PKG FOR afw_040215.SIE_15_FTP_NOYAU_PKG;


Prompt Synonym SIE_15_AJAX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_15_AJAX_PKG FOR afw_040215.SIE_15_AJAX_PKG;


Prompt Synonym SIE_14_POPUP_LOV_IR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_14_POPUP_LOV_IR_PKG FOR afw_040215.SIE_14_POPUP_LOV_IR_PKG;


Prompt Synonym SIE_14_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_14_JAVSC_PKG FOR afw_040215.SIE_14_JAVSC_PKG;


Prompt Synonym SIE_14_FORMT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_14_FORMT_PKG FOR afw_040215.SIE_14_FORMT_PKG;


Prompt Synonym SIE_14_DOMN_VALR_SYSTM_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_14_DOMN_VALR_SYSTM_PKG FOR afw_040215.SIE_14_DOMN_VALR_SYSTM_PKG;


Prompt Synonym SIE_14_DOMN_VALR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_14_DOMN_VALR_PKG FOR afw_040215.SIE_14_DOMN_VALR_PKG;


Prompt Synonym SIE_14_DOMN_VALR_CU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_14_DOMN_VALR_CU_PKG FOR afw_040215.SIE_14_DOMN_VALR_CU_PKG;


Prompt Synonym SIE_13_TYPE_FICHR;
CREATE OR REPLACE SYNONYM &schem.SIE_13_TYPE_FICHR FOR afw_040215.SIE_13_TYPE_FICHR;


Prompt Synonym SIE_13_RESRC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_RESRC_PKG FOR afw_040215.SIE_13_RESRC_PKG;


Prompt Synonym SIE_13_REGN_PILTB_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_REGN_PILTB_PKG FOR afw_040215.SIE_13_REGN_PILTB_PKG;


Prompt Synonym SIE_13_RAPRT_INTER_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_RAPRT_INTER_PKG FOR afw_040215.SIE_13_RAPRT_INTER_PKG;


Prompt Synonym SIE_13_RAPRT_INTER_CU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_RAPRT_INTER_CU_PKG FOR afw_040215.SIE_13_RAPRT_INTER_CU_PKG;


Prompt Synonym SIE_13_PREFR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PREFR_PKG FOR afw_040215.SIE_13_PREFR_PKG;


Prompt Synonym SIE_13_PLUGN_UTIL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PLUGN_UTIL_PKG FOR afw_040215.SIE_13_PLUGN_UTIL_PKG;


Prompt Synonym SIE_13_PLUGN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PLUGN_PKG FOR afw_040215.SIE_13_PLUGN_PKG;


Prompt Synonym SIE_13_PLUGN_CU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PLUGN_CU_PKG FOR afw_040215.SIE_13_PLUGN_CU_PKG;


Prompt Synonym SIE_13_PLUGN_ARBRE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PLUGN_ARBRE_PKG FOR afw_040215.SIE_13_PLUGN_ARBRE_PKG;


Prompt Synonym SIE_13_PAGE_REGN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PAGE_REGN_PKG FOR afw_040215.SIE_13_PAGE_REGN_PKG;


Prompt Synonym SIE_13_PAGE_PREFR_NAVGT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PAGE_PREFR_NAVGT_PKG FOR afw_040215.SIE_13_PAGE_PREFR_NAVGT_PKG;


Prompt Synonym SIE_13_PAGE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PAGE_PKG FOR afw_040215.SIE_13_PAGE_PKG;


Prompt Synonym SIE_13_PAGE_ITEM_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_PAGE_ITEM_PKG FOR afw_040215.SIE_13_PAGE_ITEM_PKG;


Prompt Synonym SIE_13_OPERT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_OPERT_PKG FOR afw_040215.SIE_13_OPERT_PKG;


Prompt Synonym SIE_13_NAVGT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_NAVGT_PKG FOR afw_040215.SIE_13_NAVGT_PKG;


Prompt Synonym SIE_13_NAVGT_NOYAU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_NAVGT_NOYAU_PKG FOR afw_040215.SIE_13_NAVGT_NOYAU_PKG;


Prompt Synonym SIE_13_MIME_TYPE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_MIME_TYPE_PKG FOR afw_040215.SIE_13_MIME_TYPE_PKG;


Prompt Synonym SIE_13_MIME_TYPE;
CREATE OR REPLACE SYNONYM &schem.SIE_13_MIME_TYPE FOR afw_040215.SIE_13_MIME_TYPE;


Prompt Synonym SIE_13_MENU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_MENU_PKG FOR afw_040215.SIE_13_MENU_PKG;


Prompt Synonym SIE_13_EXPOR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_EXPOR_PKG FOR afw_040215.SIE_13_EXPOR_PKG;


Prompt Synonym SIE_13_CONDT_PILTB_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_13_CONDT_PILTB_PKG FOR afw_040215.SIE_13_CONDT_PILTB_PKG;


Prompt Synonym SIE_12_UTILS_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_UTILS_PKG FOR afw_040215.SIE_12_UTILS_PKG;


Prompt Synonym SIE_12_UTILS;
CREATE OR REPLACE SYNONYM &schem.SIE_12_UTILS FOR afw_040215.SIE_12_UTILS;


Prompt Synonym SIE_12_STRUC_APLIC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_STRUC_APLIC_PKG FOR afw_040215.SIE_12_STRUC_APLIC_PKG;


Prompt Synonym SIE_12_STRUC_APLIC_CU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_STRUC_APLIC_CU_PKG FOR afw_040215.SIE_12_STRUC_APLIC_CU_PKG;


Prompt Synonym SIE_12_STAT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_STAT_PKG FOR afw_040215.SIE_12_STAT_PKG;


Prompt Synonym SIE_12_SESN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_SESN_PKG FOR afw_040215.SIE_12_SESN_PKG;


Prompt Synonym SIE_12_SESN;
CREATE OR REPLACE SYNONYM &schem.SIE_12_SESN FOR afw_040215.SIE_12_SESN;


Prompt Synonym SIE_12_SECRT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_SECRT_PKG FOR afw_040215.SIE_12_SECRT_PKG;


Prompt Synonym SIE_12_REQT_INTER_UTILS_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_REQT_INTER_UTILS_PKG FOR afw_040215.SIE_12_REQT_INTER_UTILS_PKG;


Prompt Synonym SIE_12_MOT_PASSE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_MOT_PASSE_PKG FOR afw_040215.SIE_12_MOT_PASSE_PKG;


Prompt Synonym SIE_12_MENU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_MENU_PKG FOR afw_040215.SIE_12_MENU_PKG;


Prompt Synonym SIE_12_MEMBR_STRUC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_MEMBR_STRUC_PKG FOR afw_040215.SIE_12_MEMBR_STRUC_PKG;


Prompt Synonym SIE_12_GROUP_UTILS_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_GROUP_UTILS_PKG FOR afw_040215.SIE_12_GROUP_UTILS_PKG;


Prompt Synonym SIE_12_GROUP_STAT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_GROUP_STAT_PKG FOR afw_040215.SIE_12_GROUP_STAT_PKG;


Prompt Synonym SIE_12_FAVR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_FAVR_PKG FOR afw_040215.SIE_12_FAVR_PKG;


Prompt Synonym SIE_12_DOMN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_DOMN_PKG FOR afw_040215.SIE_12_DOMN_PKG;


Prompt Synonym SIE_12_CALND_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_CALND_PKG FOR afw_040215.SIE_12_CALND_PKG;


Prompt Synonym SIE_12_AUTHE_APEX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_AUTHE_APEX_PKG FOR afw_040215.SIE_12_AUTHE_APEX_PKG;


Prompt Synonym SIE_12_ARBRE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_12_ARBRE_PKG FOR afw_040215.SIE_12_ARBRE_PKG;


Prompt Synonym SIE_11_VERSN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_VERSN_PKG FOR afw_040215.SIE_11_VERSN_PKG;


Prompt Synonym SIE_11_UTILS_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_UTILS_PKG FOR afw_040215.SIE_11_UTILS_PKG;


Prompt Synonym SIE_11_SYSTM_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_SYSTM_PKG FOR afw_040215.SIE_11_SYSTM_PKG;


Prompt Synonym SIE_11_PRODT_PUBLC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_PRODT_PUBLC_PKG FOR afw_040215.SIE_11_PRODT_PUBLC_PKG;


Prompt Synonym SIE_11_PRODT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_PRODT_PKG FOR afw_040215.SIE_11_PRODT_PKG;


Prompt Synonym SIE_11_AUTHE_APEX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_AUTHE_APEX_PKG FOR afw_040215.SIE_11_AUTHE_APEX_PKG;


Prompt Synonym SIE_11_APLIC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_11_APLIC_PKG FOR afw_040215.SIE_11_APLIC_PKG;


Prompt Synonym SIE_10_DBA_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_10_DBA_PKG FOR afw_040215.SIE_10_DBA_PKG;


Prompt Synonym SIE_09_PILE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_09_PILE_PKG FOR afw_040215.SIE_09_PILE_PKG;


Prompt Synonym SIE_08_URL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_08_URL_PKG FOR afw_040215.SIE_08_URL_PKG;


Prompt Synonym SIE_07_UTIL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_UTIL_PKG FOR afw_040215.SIE_07_UTIL_PKG;


Prompt Synonym SIE_07_UTIL_CU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_UTIL_CU_PKG FOR afw_040215.SIE_07_UTIL_CU_PKG;


Prompt Synonym SIE_07_UTIL_COMPR_ZIP_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_UTIL_COMPR_ZIP_PKG FOR afw_040215.SIE_07_UTIL_COMPR_ZIP_PKG;


Prompt Synonym SIE_07_UTIL_CHAIN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_UTIL_CHAIN_PKG FOR afw_040215.SIE_07_UTIL_CHAIN_PKG;


Prompt Synonym SIE_07_SQL_UTIL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_SQL_UTIL_PKG FOR afw_040215.SIE_07_SQL_UTIL_PKG;


Prompt Synonym SIE_07_SQL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_SQL_PKG FOR afw_040215.SIE_07_SQL_PKG;


Prompt Synonym SIE_07_SQL_NOYAU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_SQL_NOYAU_PKG FOR afw_040215.SIE_07_SQL_NOYAU_PKG;


Prompt Synonym SIE_07_SESN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_SESN_PKG FOR afw_040215.SIE_07_SESN_PKG;


Prompt Synonym SIE_07_SEMPH_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_SEMPH_PKG FOR afw_040215.SIE_07_SEMPH_PKG;


Prompt Synonym SIE_07_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_JAVSC_PKG FOR afw_040215.SIE_07_JAVSC_PKG;


Prompt Synonym SIE_07_CLOB_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_07_CLOB_PKG FOR afw_040215.SIE_07_CLOB_PKG;


Prompt Synonym SIE_06_RATIO_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_06_RATIO_PKG FOR afw_040215.SIE_06_RATIO_PKG;


Prompt Synonym SIE_05_FORML_NOYAU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_05_FORML_NOYAU_PKG FOR afw_040215.SIE_05_FORML_NOYAU_PKG;


Prompt Synonym SIE_04_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_04_JAVSC_PKG FOR afw_040215.SIE_04_JAVSC_PKG;


Prompt Synonym SIE_04_HISTR_NAVGT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_04_HISTR_NAVGT_PKG FOR afw_040215.SIE_04_HISTR_NAVGT_PKG;


Prompt Synonym SIE_04_FIL_ARIAN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_04_FIL_ARIAN_PKG FOR afw_040215.SIE_04_FIL_ARIAN_PKG;


Prompt Synonym SIE_04_CONTX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_04_CONTX_PKG FOR afw_040215.SIE_04_CONTX_PKG;


Prompt Synonym SIE_04_ARBRE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_04_ARBRE_PKG FOR afw_040215.SIE_04_ARBRE_PKG;


Prompt Synonym SIE_03_JOURN_UNITR_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_03_JOURN_UNITR_PKG FOR afw_040215.SIE_03_JOURN_UNITR_PKG;


Prompt Synonym SIE_03_JOURN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_03_JOURN_PKG FOR afw_040215.SIE_03_JOURN_PKG;


Prompt Synonym SIE_03_ENVOI_COURL_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_03_ENVOI_COURL_PKG FOR afw_040215.SIE_03_ENVOI_COURL_PKG;


Prompt Synonym SIE_01_VALDT_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_VALDT_PKG FOR afw_040215.SIE_01_VALDT_PKG;


Prompt Synonym SIE_01_TYPE_COMNC;
CREATE OR REPLACE SYNONYM &schem.SIE_01_TYPE_COMNC FOR afw_040215.SIE_01_TYPE_COMNC;


Prompt Synonym SIE_01_NOTFC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_NOTFC_PKG FOR afw_040215.SIE_01_NOTFC_PKG;


Prompt Synonym SIE_01_MESG_TRADC_APEX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_MESG_TRADC_APEX_PKG FOR afw_040215.SIE_01_MESG_TRADC_APEX_PKG;


Prompt Synonym SIE_01_LANG_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_LANG_PKG FOR afw_040215.SIE_01_LANG_PKG;


Prompt Synonym SIE_01_JAVSC_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_JAVSC_PKG FOR afw_040215.SIE_01_JAVSC_PKG;


Prompt Synonym SIE_01_GESTN_MESG_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_GESTN_MESG_PKG FOR afw_040215.SIE_01_GESTN_MESG_PKG;


Prompt Synonym SIE_01_GESTN_MESG_AIDE_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_GESTN_MESG_AIDE_PKG FOR afw_040215.SIE_01_GESTN_MESG_AIDE_PKG;


Prompt Synonym SIE_01_EVENM_NOTFB_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_EVENM_NOTFB_PKG FOR afw_040215.SIE_01_EVENM_NOTFB_PKG;


Prompt Synonym SIE_01_EVENM_NOTFB_CU_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_EVENM_NOTFB_CU_PKG FOR afw_040215.SIE_01_EVENM_NOTFB_CU_PKG;


Prompt Synonym SIE_01_ERR_APEX_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_ERR_APEX_PKG FOR afw_040215.SIE_01_ERR_APEX_PKG;


Prompt Synonym SIE_01_DESTN_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_DESTN_PKG FOR afw_040215.SIE_01_DESTN_PKG;


Prompt Synonym SIE_01_DESTN_EVENM_NOTFB_PKG;
CREATE OR REPLACE SYNONYM &schem.SIE_01_DESTN_EVENM_NOTFB_PKG FOR afw_040215.SIE_01_DESTN_EVENM_NOTFB_PKG;


Prompt Synonym OP;
CREATE OR REPLACE SYNONYM &schem.OP FOR afw_040215.OP;


Prompt Synonym ETE_B;
CREATE OR REPLACE SYNONYM &schem.ETE_B FOR afw_040215.ETE_B;


Prompt Synonym ETE;
CREATE OR REPLACE SYNONYM &schem.ETE FOR afw_040215.ETE;

prompt
prompt ...Termine synonym &schem...
prompt