SET DEFINE OFF;
Prompt Synonym AA;
CREATE OR REPLACE SYNONYM afw_040215.AA FOR APEX_040200.APEX_APPLICATION;


Prompt Synonym APEX_ACTIO_DYNMQ_ACTIO;
CREATE OR REPLACE SYNONYM afw_040215.APEX_ACTIO_DYNMQ_ACTIO FOR APEX_040200.WWV_FLOW_PAGE_DA_ACTIONS;


Prompt Synonym APEX_ACTIO_DYNMQ_EVENM;
CREATE OR REPLACE SYNONYM afw_040215.APEX_ACTIO_DYNMQ_EVENM FOR APEX_040200.WWV_FLOW_PAGE_DA_EVENTS;


Prompt Synonym APEX_APLIC;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC FOR APEX_040200.WWV_FLOWS;


Prompt Synonym APEX_APLIC_BREAD;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_BREAD FOR APEX_040200.WWV_FLOW_MENUS;


Prompt Synonym APEX_APLIC_BREAD_ITEM;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_BREAD_ITEM FOR APEX_040200.WWV_FLOW_MENU_OPTIONS;


Prompt Synonym APEX_APLIC_COMPT;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_COMPT FOR APEX_040200.WWV_FLOW_COMPUTATIONS;


Prompt Synonym APEX_APLIC_NAVGT_BAR;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_NAVGT_BAR FOR APEX_040200.WWV_FLOW_ICON_BAR;


Prompt Synonym APEX_APLIC_PROCS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_PROCS FOR APEX_040200.WWV_FLOW_PROCESSING;


Prompt Synonym APEX_APLIC_SHORT;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_SHORT FOR APEX_040200.WWV_FLOW_SHORTCUTS;


Prompt Synonym APEX_APLIC_THEME;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_THEME FOR APEX_040200.WWV_FLOW_THEMES;


Prompt Synonym APEX_APLIC_TREES;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_TREES FOR APEX_040200.WWV_FLOW_TREES;


Prompt Synonym APEX_AUTHE_SCHEM;
CREATE OR REPLACE SYNONYM afw_040215.APEX_AUTHE_SCHEM FOR APEX_040200.WWV_FLOW_CUSTOM_AUTH_SETUPS;


Prompt Synonym APEX_BOUTN_PAGE;
CREATE OR REPLACE SYNONYM afw_040215.APEX_BOUTN_PAGE FOR APEX_040200.WWV_FLOW_STEP_BUTTONS;


Prompt Synonym APEX_BOUTN_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_BOUTN_TEMPL FOR APEX_040200.WWV_FLOW_BUTTON_TEMPLATES;


Prompt Synonym APEX_BRANC_PAGE;
CREATE OR REPLACE SYNONYM afw_040215.APEX_BRANC_PAGE FOR APEX_040200.WWV_FLOW_STEP_BRANCHES;


Prompt Synonym APEX_CONDT;
CREATE OR REPLACE SYNONYM afw_040215.APEX_CONDT FOR APEX_040200.WWV_FLOW_CONDITIONS;


Prompt Synonym APEX_FLASH_CHART;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLASH_CHART FOR APEX_040200.WWV_FLOW_FLASH_CHARTS;


Prompt Synonym APEX_FLASH_CHART_5;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLASH_CHART_5 FOR APEX_040200.WWV_FLOW_FLASH_CHARTS_5;


Prompt Synonym APEX_FLASH_CHART_5_SERS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLASH_CHART_5_SERS FOR APEX_040200.WWV_FLOW_FLASH_CHART5_SERIES;


Prompt Synonym APEX_FLASH_CHART_SERS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLASH_CHART_SERS FOR APEX_040200.WWV_FLOW_FLASH_CHART_SERIES;


Prompt Synonym APEX_FLOW_GEN_API2;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_GEN_API2 FOR APEX_040200.WWV_FLOW_GEN_API2;


Prompt Synonym APEX_FLOW_LIST;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_LIST FOR APEX_040200.WWV_FLOW_LISTS;


Prompt Synonym APEX_FLOW_LIST_ITEM;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_LIST_ITEM FOR APEX_040200.WWV_FLOW_LIST_ITEMS;


Prompt Synonym APEX_FLOW_LIST_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_LIST_TEMPL FOR APEX_040200.WWV_FLOW_LIST_TEMPLATES;


Prompt Synonym APEX_FLOW_MENU_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_MENU_TEMPL FOR APEX_040200.WWV_FLOW_MENU_TEMPLATES;


Prompt Synonym APEX_FLOW_TABS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_TABS FOR APEX_040200.WWV_FLOW_TABS;


Prompt Synonym APEX_FLOW_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_TEMPL FOR APEX_040200.WWV_FLOW_TEMPLATES;


Prompt Synonym APEX_FLOW_WORKSHEET;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FLOW_WORKSHEET FOR APEX_040200.WWV_FLOW_WORKSHEET;


Prompt Synonym APEX_IR;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR FOR APEX_040200.WWV_FLOW_WORKSHEETS;


Prompt Synonym APEX_IR_API_PKG;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR_API_PKG FOR APEX_040200.WWV_FLOW_WORKSHEET_API;


Prompt Synonym APEX_IR_COLN;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR_COLN FOR APEX_040200.WWV_FLOW_WORKSHEET_COLUMNS;


Prompt Synonym APEX_IR_COMPT;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR_COMPT FOR APEX_040200.WWV_FLOW_WORKSHEET_COMPUTATION;


Prompt Synonym APEX_IR_CONDT;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR_CONDT FOR APEX_040200.WWV_FLOW_WORKSHEET_CONDITIONS;


Prompt Synonym APEX_IR_RPTS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR_RPTS FOR APEX_040200.WWV_FLOW_WORKSHEET_RPTS;


Prompt Synonym APEX_IR_STANDARD_PKG;
CREATE OR REPLACE SYNONYM afw_040215.APEX_IR_STANDARD_PKG FOR APEX_040200.WWV_FLOW_WORKSHEET_STANDARD;


Prompt Synonym APEX_ITEM_APLIC;
CREATE OR REPLACE SYNONYM afw_040215.APEX_ITEM_APLIC FOR APEX_040200.WWV_FLOW_ITEMS;


Prompt Synonym APEX_ITEM_PAGE;
CREATE OR REPLACE SYNONYM afw_040215.APEX_ITEM_PAGE FOR APEX_040200.WWV_FLOW_STEP_ITEMS;


Prompt Synonym APEX_ITEM_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_ITEM_TEMPL FOR APEX_040200.WWV_FLOW_FIELD_TEMPLATES;


Prompt Synonym APEX_JAVSC;
CREATE OR REPLACE SYNONYM afw_040215.APEX_JAVSC FOR APEX_040200.WWV_FLOW_JAVASCRIPT;


Prompt Synonym APEX_LOV;
CREATE OR REPLACE SYNONYM afw_040215.APEX_LOV FOR APEX_040200.WWV_FLOW_LISTS_OF_VALUES$;


Prompt Synonym APEX_PAGE;
CREATE OR REPLACE SYNONYM afw_040215.APEX_PAGE FOR APEX_040200.WWV_FLOW_STEPS;


Prompt Synonym APEX_PAGE_COMPT;
CREATE OR REPLACE SYNONYM afw_040215.APEX_PAGE_COMPT FOR APEX_040200.WWV_FLOW_STEP_COMPUTATIONS;


Prompt Synonym APEX_PAGE_PROCS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_PAGE_PROCS FOR APEX_040200.WWV_FLOW_STEP_PROCESSING;


Prompt Synonym APEX_PLUGN_UTIL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_PLUGN_UTIL FOR APEX_040200.WWV_FLOW_PLUGIN_UTIL;


Prompt Synonym APEX_POPUP_LOV_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_POPUP_LOV_TEMPL FOR APEX_040200.WWV_FLOW_POPUP_LOV_TEMPLATE;


Prompt Synonym APEX_PROCS;
CREATE OR REPLACE SYNONYM afw_040215.APEX_PROCS FOR APEX_040200.WWV_FLOW_STEP_PROCESSING;


Prompt Synonym APEX_REGN;
CREATE OR REPLACE SYNONYM afw_040215.APEX_REGN FOR APEX_040200.WWV_FLOW_PAGE_PLUGS;


Prompt Synonym APEX_REGN_COLN;
CREATE OR REPLACE SYNONYM afw_040215.APEX_REGN_COLN FOR APEX_040200.WWV_FLOW_REGION_REPORT_COLUMN;


Prompt Synonym APEX_REGN_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_REGN_TEMPL FOR APEX_040200.WWV_FLOW_PAGE_PLUG_TEMPLATES;


Prompt Synonym APEX_REGN_UPDAT_COLN;
CREATE OR REPLACE SYNONYM afw_040215.APEX_REGN_UPDAT_COLN FOR APEX_040200.WWV_FLOW_REGION_UPD_RPT_COLS;


Prompt Synonym APEX_ROW_TEMPL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_ROW_TEMPL FOR APEX_040200.WWV_FLOW_ROW_TEMPLATES;


Prompt Synonym APEX_SCHEM_AUTOR;
CREATE OR REPLACE SYNONYM afw_040215.APEX_SCHEM_AUTOR FOR APEX_040200.WWV_FLOW_SECURITY_SCHEMES;


Prompt Synonym APEX_SESN;
CREATE OR REPLACE SYNONYM afw_040215.APEX_SESN FOR APEX_040200.WWV_FLOW_SESSIONS$;


Prompt Synonym APEX_SESN_VALR_ITEM;
CREATE OR REPLACE SYNONYM afw_040215.APEX_SESN_VALR_ITEM FOR APEX_040200.WWV_FLOW_DATA;


Prompt Synonym APEX_TEXT_MESG;
CREATE OR REPLACE SYNONYM afw_040215.APEX_TEXT_MESG FOR APEX_040200.WWV_FLOW_MESSAGES$;


Prompt Synonym APEX_TRADC;
CREATE OR REPLACE SYNONYM afw_040215.APEX_TRADC FOR APEX_040200.WWV_FLOW_LANGUAGE_MAP;


Prompt Synonym APEX_VALR_LOV;
CREATE OR REPLACE SYNONYM afw_040215.APEX_VALR_LOV FOR APEX_040200.WWV_FLOW_LIST_OF_VALUES_DATA;


SET DEFINE OFF;
Prompt Synonym APEX_APLIC_UTIL;
CREATE OR REPLACE SYNONYM afw_040215.APEX_APLIC_UTIL FOR APEX_040200.WWV_FLOW_UTILITIES;


Prompt Synonym APEX_SOUMS_PAGE;
CREATE OR REPLACE SYNONYM afw_040215.APEX_SOUMS_PAGE FOR APEX_040200.WWV_FLOW_PAGE_SUBMISSIONS;

SET DEFINE OFF;
Prompt Synonym APEX_FICHR;
CREATE OR REPLACE SYNONYM afw_040215.APEX_FICHR FOR FLOWS_FILES.WWV_FLOW_FILE_OBJECTS$;
